#!/usr/bin/env python3
"""Generate ANTIQVITAS's exact-filename M3 start-manager mirror.

Setup managers are additive in EU5.  Replacing every installed start filename
is therefore the only locally verified way to prevent the 1337 snapshot from
surviving beneath the AD 1 database.  Content generators extend these roots in
later M3 batches; this first batch proves the empty roots are valid on build
24187685 before historical ownership is introduced.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT / "main_menu/setup/start"
ROSTER = ROOT / "docs/world_1ad/polities.csv"
TAG_MAP = ROOT / "docs/world_1ad/tag_map.json"
OWNERSHIP = ROOT / "docs/world_1ad/ownership_resolved.csv"

STATIC_FILES = {
    "02_core.txt": """institution_manager = {\n}\n\nreligion_manager = {\n}\n""",
    "03_markets.txt": "market_manager = {\n}\n",
    "04_dynasties.txt": "dynasty_manager = {\n}\n",
    "05_characters.txt": "character_db = {\n}\n",
    "06_pops.txt": "locations = {\n}\n",
    "07_cities_and_buildings.txt": "locations = {\n}\n",
    "08_institutions.txt": "locations = {\n}\n",
    "09_roads.txt": "road_network = {\n}\n",
    "11_art.txt": "work_of_art_manager = {\n}\n",
    "12_diplomacy.txt": "diplomacy_manager = {\n}\n",
    "13_religion.txt": "building_manager = {\n}\n",
    "14_development.txt": "development = {\n}\n",
    "15_international_organizations.txt": "international_organization_manager = {\n}\n",
    "16_wars.txt": "war_manager = {\n}\n",
    "18_opinions.txt": "diplomacy_manager = {\n}\n",
    "19_diseases.txt": "disease_outbreak_manager = {\n}\n",
    "20_rivals.txt": "diplomacy_manager = {\n}\n",
    "21_locations.txt": "locations = {\n}\n",
    "22_situations.txt": "situation_manager = {\n}\n",
    "23_colonies.txt": "colony_manager = {\n}\n",
    "24_town_rights.txt": "townrights_manager = {\n}\n",
    "25_area_preferences.txt": "countries = {\n\tcountries = {\n\t}\n}\n",
    "26_ai_personalities.txt": "countries = {\n\tcountries = {\n\t}\n}\n",
    "27_armies.txt": "unit_manager = {\n}\n",
}


def country_manager() -> tuple[str, int, int]:
    """Render M3 countries from checked ownership plus verified capitals.

    The generic template and random rulers are explicit transitional scaffolding
    for the political-map milestone; M6 replaces them with sourced governments,
    characters, and dynasties.
    """
    with ROSTER.open(encoding="utf-8-sig", newline="") as handle:
        rows = list(csv.DictReader(handle))
    tag_map = {
        entry["design_tag"]: entry["engine_tag"]
        for entry in json.loads(TAG_MAP.read_text(encoding="utf-8"))["entries"]
    }
    ownership: dict[str, dict[str, list[str]]] = {}
    with OWNERSHIP.open(encoding="utf-8-sig", newline="") as handle:
        for entry in csv.DictReader(line for line in handle if not line.startswith("#")):
            ownership.setdefault(entry["tag"], {}).setdefault(entry["tenure"], []).append(
                entry["location"]
            )
    lines = [
        "# Generated by tools/generate_start_mirror.py --write.",
        "# M3 political-map slice; generated only from sourced ownership data.",
        "current_age = age_1_traditions",
        "",
        "countries = {",
        "\tcountries = {",
    ]
    count = 0
    controlled = 0
    for row in rows:
        capital = row["map_capital"]
        if capital == "TBD":
            continue
        template = "asia_advanced_tribe" if row["kind"] == "sop" else "east_asia_monarchy"
        lines.append(f'\t\t{tag_map[row["tag"]]} = {{ # {row["name"]}; {row["source"]}')
        groups = ownership.get(row["tag"], {"own_control_core": [capital]})
        for tenure in sorted(groups):
            locations = sorted(set(groups[tenure]))
            lines.append(f"\t\t\t{tenure} = {{")
            lines.extend(f"\t\t\t\t{location}" for location in locations)
            lines.extend(("\t\t\t}", ""))
            controlled += len(locations)
        lines.extend(
            (
                f'\t\t\tinclude = "{template}"',
                "\t\t\tgovernment = { ruler = random }",
                f"\t\t\tcapital = {capital}",
                "\t\t}",
                "",
            )
        )
        count += 1
    lines.extend(("\t}", "}"))
    return "\n".join(lines) + "\n", count, controlled


def generated_files() -> tuple[dict[str, str], int, int]:
    countries, count, controlled = country_manager()
    return {**STATIC_FILES, "10_countries.txt": countries}, count, controlled


def installed_start_filenames() -> set[str]:
    config = json.loads((ROOT / "config/local_paths.json").read_text(encoding="utf-8-sig"))
    source = Path(config["game_dir"]) / "game/main_menu/setup/start"
    return {path.name for path in source.glob("*.txt")}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write == args.check:
        parser.error("provide exactly one of --write or --check")
    failures: list[str] = []
    files, country_count, controlled = generated_files()
    if args.write:
        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        for name, content in files.items():
            path = OUTPUT_DIR / name
            path.write_text(content, encoding="utf-8", newline="\n")
            print(f"start_mirror: wrote {path.relative_to(ROOT)}")
        return 0
    actual = {path.name for path in OUTPUT_DIR.glob("*.txt")} if OUTPUT_DIR.is_dir() else set()
    expected = set(files)
    installed = installed_start_filenames()
    if installed != expected:
        failures.append(
            "installed start-manager inventory changed; refresh FILES before relying on the mirror"
        )
    for name in sorted(expected - actual):
        failures.append(f"missing M3 start mirror {name}")
    for name in sorted(actual - expected):
        failures.append(f"unexpected start file {name}; add it to generator inventory")
    for name, content in files.items():
        path = OUTPUT_DIR / name
        if path.is_file() and path.read_text(encoding="utf-8") != content:
            failures.append(f"stale generated start mirror {name}")
    if failures:
        print("start_mirror: FAIL")
        print("\n".join(f"  - {failure}" for failure in failures))
        return 1
    print(
        f"start_mirror: PASS ({len(files)} exact manager filenames; "
        f"{country_count} verified-capital countries; {controlled} controlled locations)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
