#!/usr/bin/env python3
"""Render checked antiquity-specific raw goods, localization, and icon contracts."""

from __future__ import annotations

import argparse
import csv
import json
import re
import subprocess
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "docs/m5/custom_goods.csv"
OUTPUT = ROOT / "in_game/common/goods/00_antiquitas_raw_goods.txt"
POP_DEMAND_SOURCE_RELATIVE = Path("game/in_game/common/goods_demand/pop_demands.txt")
POP_DEMAND_OUTPUT = ROOT / "in_game/common/goods_demand/pop_demands.txt"
ASSET_SOURCE = ROOT / "assets_queue/generated"
ICON_DIR = ROOT / "main_menu/gfx/interface/icons/trade_goods"
ILLUSTRATION_DIR = ICON_DIR / "illustrations"
MODIFIER_TYPES = ROOT / "main_menu/common/modifier_type_definitions/00_antiquitas_goods.txt"
MODIFIER_ICONS = ROOT / "main_menu/common/modifier_icons/00_antiquitas_goods.txt"
LOCALIZATION_DIR = ROOT / "main_menu/localization"
LANGUAGES = (
    "english",
    "french",
    "german",
    "spanish",
    "polish",
    "russian",
    "braz_por",
    "simp_chinese",
    "japanese",
    "korean",
    "turkish",
)
FIELDS = (
    "key",
    "name",
    "description",
    "method",
    "color_r",
    "color_g",
    "color_b",
    "price",
    "transport_cost",
    "nobles",
    "burghers",
    "clergy",
    "source",
    "confidence",
    "note",
)
KEY_RE = re.compile(r"^antq_[a-z0-9_]+$")
METHODS = {"farming", "gathering", "mining", "hunting", "forestry"}
POP_DEMAND_INSERTION = re.compile(r"^(?P<indent>[ \t]*)mercury\s*=\s*1(?P<ending>\r?\n)$", re.MULTILINE)


def rows() -> list[dict[str, str]]:
    with INPUT.open(encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        if tuple(reader.fieldnames or ()) != FIELDS:
            raise ValueError("custom_goods.csv header does not match required field order")
        return list(reader)


def number(value: str, field: str, key: str, minimum: float = 0.0) -> float:
    try:
        parsed = float(value)
    except ValueError as exc:
        raise ValueError(f"custom_goods.csv {key} has invalid {field} {value}") from exc
    if parsed < minimum:
        raise ValueError(f"custom_goods.csv {key} has {field} below {minimum}")
    return parsed


def render_goods(entries: list[dict[str, str]]) -> str:
    lines = [
        "# Generated by tools/generate_ancient_goods.py --write.",
        "# M5 antiquity-specific raw goods; sources and rationale: docs/m5/custom_goods.csv.",
    ]
    for row in sorted(entries, key=lambda item: item["key"]):
        lines.extend(
            (
                f"{row['key']} = {{",
                f"\tmethod = {row['method']}",
                "\tcategory = raw_material",
                f"\tcolor = rgb {{ {row['color_r']} {row['color_g']} {row['color_b']} }}",
                f"\tdefault_market_price = {row['price']}",
                f"\ttransport_cost = {row['transport_cost']}",
                "",
                "\tdemand_add = {",
                f"\t\tnobles = {row['nobles']}",
                f"\t\tburghers = {row['burghers']}",
                f"\t\tclergy = {row['clergy']}",
                "\t}",
                "",
                "\torigin_in_old_world = yes",
                "\tcustom_tags = { old_world_goods }",
                "\tno_demand_if_no_market_availability = yes",
                "}",
                "",
            )
        )
    return "\n".join(lines)


def pop_demand_source() -> Path:
    try:
        config = json.loads((ROOT / "config/local_paths.json").read_text(encoding="utf-8-sig"))
        source = Path(str(config["game_dir"])) / POP_DEMAND_SOURCE_RELATIVE
    except (OSError, KeyError, json.JSONDecodeError) as exc:
        raise ValueError(f"cannot resolve installed pop-demand registry: {exc}") from exc
    if not source.is_file():
        raise ValueError(f"installed pop-demand registry is missing: {source}")
    return source


def render_pop_demands(entries: list[dict[str, str]]) -> bytes:
    """Copy the engine's special demand registry and add every ANTIQVITAS good.

    ``pop_demand`` is not an additive generic script object: engine setup warns
    when a good's pop demand is absent from this one registry.  An exact-name
    source-pinned overlay keeps every installed demand key while extending the
    raw-material section with the generated custom-good inventory.
    """
    source = pop_demand_source()
    raw = source.read_bytes()
    has_bom = raw.startswith(b"\xef\xbb\xbf")
    content = raw.decode("utf-8-sig")
    matches = list(POP_DEMAND_INSERTION.finditer(content))
    if len(matches) != 1:
        raise ValueError(
            "installed pop-demand registry drift: expected exactly one mercury raw-material anchor, "
            f"found {len(matches)}"
        )
    match = matches[0]
    ending = match.group("ending")
    indent = match.group("indent")
    injected = [
        f"{indent}# ANTIQVITAS custom raw materials; generated from docs/m5/custom_goods.csv.{ending}",
    ]
    injected.extend(f"{indent}{row['key']} = 1{ending}" for row in sorted(entries, key=lambda item: item["key"]))
    rendered = content[: match.end()] + "".join(injected) + content[match.end() :]
    payload = rendered.encode("utf-8")
    return (b"\xef\xbb\xbf" if has_bom else b"") + payload


def modifier_names(row: dict[str, str]) -> tuple[tuple[str, str], ...]:
    key = row["key"]
    name = row["name"]
    return (
        (f"can_extract_{key}", f"Can Extract {name}"),
        (f"ban_exports_of_{key}", f"Ban Exports of {name}"),
        (f"ban_imports_of_{key}", f"Ban Imports of {name}"),
        (f"local_{key}_output_modifier", f"Local {name} Output"),
        (f"global_{key}_output_modifier", f"Global {name} Output"),
        (f"global_{key}_pop_demand", f"{name} Pop Demand"),
        (f"{key}_impacts_inflation", f"{name} Impacts Inflation"),
        (f"{key}_used_for_minting", f"{name} Used for Minting"),
    )


def render_localization(entries: list[dict[str, str]], language: str) -> str:
    lines = [f"l_{language}:"]
    for row in sorted(entries, key=lambda item: item["key"]):
        lines.append(f' {row["key"]}: "{row["name"]}"')
        lines.append(f' {row["key"]}_desc: "{row["description"]}"')
        for key, name in modifier_names(row):
            lines.append(f' MODIFIER_TYPE_NAME_{key}: "{name}"')
            lines.append(f' MODIFIER_TYPE_DESC_{key}: "{name}."')
    return "\n".join(lines) + "\n"


def render_modifier_types(entries: list[dict[str, str]]) -> str:
    contracts = (
        ("can_extract_{key}", "boolean", "country"),
        ("ban_exports_of_{key}", "boolean", "country"),
        ("ban_imports_of_{key}", "boolean", "country"),
        ("local_{key}_output_modifier", "percent", "location"),
        ("global_{key}_output_modifier", "percent", "country"),
        ("global_{key}_pop_demand", "percent", "country"),
        ("{key}_impacts_inflation", "percent", "country"),
        ("{key}_used_for_minting", "boolean", "country"),
    )
    lines = [
        "# Generated by tools/generate_ancient_goods.py --write.",
        "# Required modifier contracts synthesized by the EU5 goods parser.",
    ]
    for row in sorted(entries, key=lambda item: item["key"]):
        for template, value_type, scope in contracts:
            key = template.format(key=row["key"])
            lines.extend(
                (
                    f"{key}={{",
                    f"\t{value_type}=yes",
                    "\tgame_data={",
                    f"\t\tcategory={scope}",
                    "\t}",
                    "}",
                    "",
                )
            )
    return "\n".join(lines)


def render_modifier_icons(entries: list[dict[str, str]]) -> str:
    lines = [
        "# Generated by tools/generate_ancient_goods.py --write.",
        "# The vanilla default modifier texture is an intentional neutral fallback.",
    ]
    for row in sorted(entries, key=lambda item: item["key"]):
        for key, _name in modifier_names(row):
            lines.extend(
                (
                    f"{key} = {{",
                    '\tpositive = "gfx/interface/icons/modifier_types/_default.dds"',
                    "}",
                    "",
                )
            )
    return "\n".join(lines)


def dds_identify(path: Path) -> tuple[str, str, str, str]:
    magick = ROOT / ".tools/ImageMagick/magick.exe"
    executable = str(magick) if magick.is_file() else "magick"
    result = subprocess.run(
        [executable, "identify", "-format", "%m|%w|%h|%[channels]", str(path)],
        check=True,
        text=True,
        capture_output=True,
    )
    return tuple(result.stdout.split("|", 3))  # type: ignore[return-value]


def verify_dds(
    path: Path,
    expected_width: str,
    expected_height: str,
    minimum_size: int,
    failures: list[str],
) -> None:
    try:
        fmt, width, height, channels = dds_identify(path)
        if (fmt, width, height, channels) != ("DDS", expected_width, expected_height, "srgba 4.0"):
            failures.append(
                f"{path.relative_to(ROOT)} must be {expected_width}x{expected_height} DDS sRGBA, got "
                f"{fmt} {width}x{height} {channels}"
            )
        elif path.stat().st_size < minimum_size:
            failures.append(f"{path.relative_to(ROOT)} has no complete mip chain")
    except (OSError, subprocess.CalledProcessError) as exc:
        failures.append(f"{path.relative_to(ROOT)} cannot be identified: {exc}")


def validate(entries: list[dict[str, str]]) -> None:
    failures: list[str] = []
    seen: set[str] = set()
    colors: set[tuple[int, int, int]] = set()
    for row in entries:
        key = row.get("key", "").strip()
        if any(not row.get(field, "").strip() for field in FIELDS):
            failures.append("custom_goods.csv contains a blank required field")
            continue
        if key in seen:
            failures.append(f"custom_goods.csv repeats key {key}")
        if not KEY_RE.fullmatch(key):
            failures.append(f"custom_goods.csv key {key} must be namespaced antq_ ASCII")
        if row["method"] not in METHODS:
            failures.append(f"custom_goods.csv {key} has invalid method {row['method']}")
        try:
            color = tuple(int(row[field]) for field in ("color_r", "color_g", "color_b"))
            if any(value < 0 or value > 255 for value in color):
                raise ValueError
            if color in colors:
                failures.append(f"custom_goods.csv repeats RGB color {color}")
            colors.add(color)
        except ValueError:
            failures.append(f"custom_goods.csv {key} has an invalid RGB color")
        if row["confidence"] not in {"secure", "contested"}:
            failures.append(f"custom_goods.csv {key} has invalid confidence {row['confidence']}")
        for field in ("price", "transport_cost", "nobles", "burghers", "clergy"):
            try:
                number(row[field], field, key)
            except ValueError as exc:
                failures.append(str(exc))
        png = ASSET_SOURCE / f"{key}.png"
        icon = ICON_DIR / f"icon_goods_{key}.dds"
        illustration = ILLUSTRATION_DIR / f"icon_goods_{key}.dds"
        if not png.is_file():
            failures.append(f"custom_goods.csv {key} is missing source art {png.relative_to(ROOT)}")
        else:
            try:
                with Image.open(png) as image:
                    if image.mode != "RGBA":
                        failures.append(f"{png.relative_to(ROOT)} must have an alpha channel")
                    elif image.getpixel((0, 0))[3] != 0:
                        failures.append(f"{png.relative_to(ROOT)} must have a transparent corner")
            except OSError as exc:
                failures.append(f"{png.relative_to(ROOT)} is unreadable: {exc}")
        if not icon.is_file():
            failures.append(f"custom_goods.csv {key} is missing icon {icon.relative_to(ROOT)}")
        else:
            verify_dds(icon, "128", "128", 21900, failures)
        if not illustration.is_file():
            failures.append(f"custom_goods.csv {key} is missing illustration {illustration.relative_to(ROOT)}")
        else:
            verify_dds(illustration, "1080", "440", 630_000, failures)
        seen.add(key)
    if failures:
        raise ValueError("\n".join(sorted(set(failures))))


def expected_files(entries: list[dict[str, str]]) -> dict[Path, tuple[str, str]]:
    values: dict[Path, tuple[str, str]] = {
        OUTPUT: (render_goods(entries), "utf-8-sig"),
        MODIFIER_TYPES: (render_modifier_types(entries), "utf-8-sig"),
        MODIFIER_ICONS: (render_modifier_icons(entries), "utf-8-sig"),
    }
    for language in LANGUAGES:
        path = LOCALIZATION_DIR / language / f"antq_m5_goods_l_{language}.yml"
        values[path] = (render_localization(entries, language), "utf-8-sig")
    return values


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write == args.check:
        parser.error("provide exactly one of --write or --check")
    try:
        entries = rows()
        if not entries:
            raise ValueError("custom_goods.csv has no entries")
        validate(entries)
        outputs = expected_files(entries)
        pop_demands = render_pop_demands(entries)
    except (OSError, ValueError, csv.Error, subprocess.CalledProcessError) as exc:
        print(f"ancient_goods: FAIL\n  - {exc}")
        return 1
    if args.write:
        for path, (content, encoding) in outputs.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding=encoding, newline="\n")
            print(f"ancient_goods: wrote {path.relative_to(ROOT)}")
        POP_DEMAND_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        POP_DEMAND_OUTPUT.write_bytes(pop_demands)
        print(f"ancient_goods: wrote {POP_DEMAND_OUTPUT.relative_to(ROOT)}")
        return 0
    stale = [
        path.relative_to(ROOT).as_posix()
        for path, (content, encoding) in outputs.items()
        if not path.is_file() or path.read_text(encoding=encoding) != content
    ]
    if not POP_DEMAND_OUTPUT.is_file() or POP_DEMAND_OUTPUT.read_bytes() != pop_demands:
        stale.append(POP_DEMAND_OUTPUT.relative_to(ROOT).as_posix())
    if stale:
        print("ancient_goods: FAIL\n  - stale or missing " + "\n  - ".join(stale))
        return 1
    print(f"ancient_goods: PASS ({len(entries)} custom antiquity goods; {len(LANGUAGES)} language mirrors)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
