#!/usr/bin/env python3
"""Generate ANTIQVITAS's exact-filename M3 start-manager mirror.

Setup managers are additive in EU5.  Replacing every installed start filename
is therefore the only locally verified way to prevent the 1337 snapshot from
surviving beneath the AD 1 database.  Content generators extend these roots in
later M3 batches; this first batch proves the empty roots are valid on build
24187685 before historical ownership is introduced.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from collections import defaultdict
from dataclasses import dataclass
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

from extract_vanilla import tokenize
from generate_country_definitions import historical_profile_for

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT / "main_menu/setup/start"
ROSTER = ROOT / "docs/world_1ad/polities.csv"
TAG_MAP = ROOT / "docs/world_1ad/tag_map.json"
OWNERSHIP = ROOT / "docs/world_1ad/ownership_resolved.csv"
SUBJECTS = ROOT / "docs/world_1ad/subjects.csv"
SUBJECT_TYPES = ROOT / "docs/vanilla_symbols/subject_type.json"
POPULATION_TARGETS = ROOT / "docs/m4/population_targets.csv"
POPULATION_ALLOCATIONS = ROOT / "docs/m4/population_region_allocations.csv"
MARKETS = ROOT / "docs/m5/markets.csv"
SUBJECT_FIELDS = ("overlord", "subject", "relationship", "source", "confidence", "note")
THOUSANDTH = Decimal("0.001")

STATIC_FILES = {
    "02_core.txt": """institution_manager = {\n}\n\nreligion_manager = {\n}\n""",
    "04_dynasties.txt": "dynasty_manager = {\n}\n",
    "05_characters.txt": "character_db = {\n}\n",
    "07_cities_and_buildings.txt": "locations = {\n}\n",
    "08_institutions.txt": "locations = {\n}\n",
    "09_roads.txt": "road_network = {\n}\n",
    "11_art.txt": "work_of_art_manager = {\n}\n",
    "13_religion.txt": "building_manager = {\n}\n",
    "14_development.txt": "development = {\n}\n",
    "15_international_organizations.txt": "international_organization_manager = {\n}\n",
    "16_wars.txt": "war_manager = {\n}\n",
    "18_opinions.txt": "diplomacy_manager = {\n}\n",
    "19_diseases.txt": "disease_outbreak_manager = {\n}\n",
    "20_rivals.txt": "diplomacy_manager = {\n}\n",
    "21_locations.txt": "locations = {\n}\n",
    "22_situations.txt": "situation_manager = {\n}\n",
    "23_colonies.txt": "colony_manager = {\n}\n",
    "24_town_rights.txt": "townrights_manager = {\n}\n",
    "25_area_preferences.txt": "countries = {\n\tcountries = {\n\t}\n}\n",
    "26_ai_personalities.txt": "countries = {\n\tcountries = {\n\t}\n}\n",
    "27_armies.txt": "unit_manager = {\n}\n",
}


@dataclass(frozen=True)
class MacroTarget:
    target: Decimal
    minimum: Decimal | None
    maximum: Decimal | None
    source: str
    confidence: str
    note: str


@dataclass(frozen=True)
class RegionalAllocation:
    macro: str
    target: Decimal
    source: str
    confidence: str
    note: str


def csv_rows(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def market_manager() -> tuple[str, int]:
    """Render source-labelled AD 1 market hubs with installed location keys."""
    locations = set(json.loads((ROOT / "docs/vanilla_symbols/locations.json").read_text(encoding="utf-8-sig")))
    required = ("key", "name", "location", "source", "confidence", "note")
    entries = csv_rows(MARKETS)
    if not entries:
        raise ValueError("markets.csv has no market entries")
    seen_keys: set[str] = set()
    seen_locations: set[str] = set()
    failures: list[str] = []
    for row in entries:
        if any(not row.get(field, "").strip() for field in required):
            failures.append("markets.csv contains a blank required field")
            continue
        key = row["key"].strip()
        location = row["location"].strip()
        if key in seen_keys:
            failures.append(f"markets.csv repeats key {key}")
        if location in seen_locations:
            failures.append(f"markets.csv repeats location {location}")
        if location not in locations:
            failures.append(f"markets.csv {key} uses unknown installed location {location}")
        if row["confidence"].strip() not in {"secure", "contested"}:
            failures.append(f"markets.csv {key} has invalid confidence {row['confidence']}")
        seen_keys.add(key)
        seen_locations.add(location)
    if failures:
        raise ValueError("\n".join(sorted(set(failures))))
    lines = [
        "# Generated by tools/generate_start_mirror.py --write.",
        "# M5 AD 1 market hubs; source and proxy rationale: docs/m5/markets.csv.",
        "market_manager = {",
    ]
    for row in sorted(entries, key=lambda item: item["key"]):
        lines.append(f"\tadd_market = {row['location']} # {row['name']}; {row['source']}")
    lines.extend(("}", ""))
    return "\n".join(lines), len(entries)


def decimal_field(row: dict[str, str], field: str, path: Path) -> Decimal:
    value = row.get(field, "").strip()
    if not value:
        raise ValueError(f"{path.relative_to(ROOT)} has a blank {field}")
    try:
        parsed = Decimal(value)
    except Exception as exc:
        raise ValueError(f"{path.relative_to(ROOT)} has invalid {field}={value!r}") from exc
    if parsed <= 0:
        raise ValueError(f"{path.relative_to(ROOT)} has non-positive {field}={value!r}")
    return parsed


def load_population_plan() -> tuple[dict[str, MacroTarget], dict[str, RegionalAllocation]]:
    """Read the auditable M4 population targets and regional allocation plan."""
    macros: dict[str, MacroTarget] = {}
    for row in csv_rows(POPULATION_TARGETS):
        macro = row.get("macro", "").strip()
        if not macro or macro in macros:
            raise ValueError(f"{POPULATION_TARGETS.relative_to(ROOT)} has invalid or duplicate macro {macro!r}")
        minimum = row.get("min_thousands", "").strip()
        maximum = row.get("max_thousands", "").strip()
        if bool(minimum) != bool(maximum):
            raise ValueError(f"{POPULATION_TARGETS.relative_to(ROOT)} {macro}: min/max must both be set or blank")
        for field in ("source", "confidence", "note"):
            if not row.get(field, "").strip():
                raise ValueError(f"{POPULATION_TARGETS.relative_to(ROOT)} {macro}: blank {field}")
        macros[macro] = MacroTarget(
            decimal_field(row, "target_thousands", POPULATION_TARGETS),
            Decimal(minimum) if minimum else None,
            Decimal(maximum) if maximum else None,
            row["source"].strip(),
            row["confidence"].strip(),
            row["note"].strip(),
        )
    if "world" not in macros:
        raise ValueError(f"{POPULATION_TARGETS.relative_to(ROOT)} must define a world target")
    allocations: dict[str, RegionalAllocation] = {}
    for row in csv_rows(POPULATION_ALLOCATIONS):
        region = row.get("region", "").strip()
        macro = row.get("macro", "").strip()
        if not region or region in allocations:
            raise ValueError(f"{POPULATION_ALLOCATIONS.relative_to(ROOT)} has invalid or duplicate region {region!r}")
        if macro not in macros or macro == "world":
            raise ValueError(f"{POPULATION_ALLOCATIONS.relative_to(ROOT)} {region}: unknown macro {macro!r}")
        for field in ("source", "confidence", "note"):
            if not row.get(field, "").strip():
                raise ValueError(f"{POPULATION_ALLOCATIONS.relative_to(ROOT)} {region}: blank {field}")
        allocations[region] = RegionalAllocation(
            macro,
            decimal_field(row, "target_thousands", POPULATION_ALLOCATIONS),
            row["source"].strip(),
            row["confidence"].strip(),
            row["note"].strip(),
        )
    allocated = defaultdict(Decimal)
    for allocation in allocations.values():
        allocated[allocation.macro] += allocation.target
    for macro, target in macros.items():
        if macro == "world":
            continue
        if allocated[macro] != target.target:
            raise ValueError(
                f"{macro} allocations total {allocated[macro]} but target is {target.target} thousand"
            )
    if sum(allocated.values(), Decimal()) != macros["world"].target:
        raise ValueError(
            f"regional allocations total {sum(allocated.values(), Decimal())} but world target is "
            f"{macros['world'].target} thousand"
        )
    return macros, allocations


def vanilla_pop_weights() -> dict[str, Decimal]:
    """Read installed-pop density as a geographic weighting template only."""
    config = json.loads((ROOT / "config/local_paths.json").read_text(encoding="utf-8-sig"))
    source = Path(config["game_dir"]) / "game/main_menu/setup/start/06_pops.txt"
    if not source.is_file():
        raise ValueError(f"installed vanilla pop template is missing: {source}")
    tokens = list(tokenize(source.read_text(encoding="utf-8-sig", errors="replace")))
    stack: list[str] = []
    weights: defaultdict[str, Decimal] = defaultdict(Decimal)
    index = 0
    while index < len(tokens):
        value = tokens[index].value
        if (
            index + 2 < len(tokens)
            and tokens[index + 1].value == "="
            and tokens[index + 2].value == "{"
        ):
            stack.append(value)
            index += 3
            continue
        if value == "}":
            if stack:
                stack.pop()
            index += 1
            continue
        if (
            value == "size"
            and index + 2 < len(tokens)
            and tokens[index + 1].value == "="
            and len(stack) == 3
            and stack[0] == "locations"
            and stack[2] == "define_pop"
        ):
            try:
                weights[stack[1]] += Decimal(tokens[index + 2].value)
            except Exception as exc:
                raise ValueError(f"invalid vanilla pop size at {stack[1]}") from exc
            index += 3
            continue
        index += 1
    if not weights:
        raise ValueError("could not read any installed vanilla population weights")
    return dict(weights)


def population_manager() -> tuple[str, int, Decimal]:
    """Render all controlled AD 1 locations against section 12.4 target totals."""
    roster_rows = csv_rows(ROSTER)
    roster = {row["tag"]: row for row in roster_rows}
    macros, allocations = load_population_plan()
    roster_regions = {row["region"] for row in roster_rows}
    missing_regions = sorted(roster_regions - set(allocations))
    extra_regions = sorted(set(allocations) - roster_regions)
    if missing_regions or extra_regions:
        raise ValueError(f"population regional coverage mismatch; missing={missing_regions}, extra={extra_regions}")
    owners: dict[str, str] = {}
    with OWNERSHIP.open(encoding="utf-8-sig", newline="") as handle:
        for entry in csv.DictReader(line for line in handle if not line.startswith("#")):
            location = entry["location"]
            tag = entry["tag"]
            if tag not in roster:
                raise ValueError(f"population ownership references unknown tag {tag}")
            if location in owners:
                raise ValueError(f"population ownership assigns {location} more than once")
            owners[location] = tag
    weights = vanilla_pop_weights()
    by_region: defaultdict[str, list[str]] = defaultdict(list)
    for location, tag in owners.items():
        by_region[roster[tag]["region"]].append(location)
    floor = Decimal("0.050")
    sizes: dict[str, Decimal] = {}
    for region, locations in by_region.items():
        target = allocations[region].target
        ordered = sorted(locations)
        regional_weights = {location: max(weights.get(location, Decimal()), floor) for location in ordered}
        total_weight = sum(regional_weights.values(), Decimal())
        if not total_weight:
            raise ValueError(f"population region {region} has no usable geographic weight")
        scaled = {
            location: (regional_weights[location] * target / total_weight).quantize(
                THOUSANDTH, rounding=ROUND_HALF_UP
            )
            for location in ordered
        }
        correction = target - sum(scaled.values(), Decimal())
        largest = max(ordered, key=lambda location: (regional_weights[location], location))
        scaled[largest] += correction
        if scaled[largest] <= 0:
            raise ValueError(f"population rounding made {largest} non-positive")
        sizes.update(scaled)
    lines = [
        "# Generated by tools/generate_start_mirror.py --write.",
        "# M4 AD 1 population totals: plan section 12.4; regional allocation is source-labelled in docs/m4/.",
        "# Installed vanilla density is a geographic weighting template only, never a historical population source.",
        "locations = {",
    ]
    for location in sorted(owners):
        row = roster[owners[location]]
        profile = historical_profile_for(row)
        pop_type = "tribesmen" if row["kind"] == "sop" else "peasants"
        lines.extend(
            (
                f"\t{location} = {{",
                f"\t\tdefine_pop = {{ type = {pop_type} size = {sizes[location]:.3f} "
                f"culture = {profile.culture} religion = {profile.religion} }}",
                "\t}",
            )
        )
    lines.extend(("}", ""))
    return "\n".join(lines), len(owners), sum(sizes.values(), Decimal())


def country_manager() -> tuple[str, int, int]:
    """Render M3 countries from checked ownership plus verified capitals.

    The generic template and random rulers are explicit transitional scaffolding
    for the political-map milestone; M6 replaces them with sourced governments,
    characters, and dynasties.
    """
    with ROSTER.open(encoding="utf-8-sig", newline="") as handle:
        rows = list(csv.DictReader(handle))
    tag_map = {
        entry["design_tag"]: entry["engine_tag"]
        for entry in json.loads(TAG_MAP.read_text(encoding="utf-8"))["entries"]
    }
    ownership: dict[str, dict[str, list[str]]] = {}
    with OWNERSHIP.open(encoding="utf-8-sig", newline="") as handle:
        for entry in csv.DictReader(line for line in handle if not line.startswith("#")):
            ownership.setdefault(entry["tag"], {}).setdefault(entry["tenure"], []).append(
                entry["location"]
            )
    lines = [
        "# Generated by tools/generate_start_mirror.py --write.",
        "# M3 political-map slice; generated only from sourced ownership data.",
        "current_age = age_1_traditions",
        "",
        "countries = {",
        "\tcountries = {",
    ]
    count = 0
    controlled = 0
    for row in rows:
        capital = row["map_capital"]
        if capital == "TBD":
            continue
        template = "asia_advanced_tribe" if row["kind"] == "sop" else "east_asia_monarchy"
        lines.append(f'\t\t{tag_map[row["tag"]]} = {{ # {row["name"]}; {row["source"]}')
        groups = ownership.get(row["tag"], {"own_control_core": [capital]})
        for tenure in sorted(groups):
            locations = sorted(set(groups[tenure]))
            lines.append(f"\t\t\t{tenure} = {{")
            lines.extend(f"\t\t\t\t{location}" for location in locations)
            lines.extend(("\t\t\t}", ""))
            controlled += len(locations)
        lines.extend(
            (
                f'\t\t\tinclude = "{template}"',
                "\t\t\tgovernment = { ruler = random }",
                f"\t\t\tcapital = {capital}",
                "\t\t}",
                "",
            )
        )
        count += 1
    lines.extend(("\t}", "}"))
    return "\n".join(lines) + "\n", count, controlled


def diplomacy_manager() -> tuple[str, int]:
    """Render the current M3 subject graph with locally verified mechanics.

    M3 uses the engine's current vassal/tributary contracts only as a clean
    political-map adapter. M9 replaces those entries with the plan's bespoke
    client-kingdom, satrapy, tributary, and foederati subject mechanics.
    """
    with ROSTER.open(encoding="utf-8-sig", newline="") as handle:
        roster = {row["tag"]: row for row in csv.DictReader(handle)}
    tag_map = {
        entry["design_tag"]: entry["engine_tag"]
        for entry in json.loads(TAG_MAP.read_text(encoding="utf-8"))["entries"]
    }
    subject_types = set(json.loads(SUBJECT_TYPES.read_text(encoding="utf-8-sig")))
    failures: list[str] = []
    seen_subjects: set[str] = set()
    dependencies: list[dict[str, str]] = []
    with SUBJECTS.open(encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        if tuple(reader.fieldnames or ()) != SUBJECT_FIELDS:
            raise ValueError("subjects.csv header does not match required field order")
        for row in reader:
            if any(not row[field].strip() for field in SUBJECT_FIELDS):
                failures.append("subjects.csv contains a blank required field")
                continue
            for tag in (row["overlord"], row["subject"]):
                if tag not in roster:
                    failures.append(f"subjects.csv references unknown roster tag {tag}")
                elif roster[tag]["map_capital"] == "TBD":
                    failures.append(f"subjects.csv references {tag} before its capital is mapped")
            if row["relationship"] not in subject_types:
                failures.append(f"unknown installed subject type {row['relationship']}")
            if row["confidence"] not in {"secure", "contested"}:
                failures.append(f"invalid confidence {row['confidence']} for {row['subject']}")
            if row["subject"] in seen_subjects:
                failures.append(f"{row['subject']} has more than one M3 overlord")
            seen_subjects.add(row["subject"])
            dependencies.append(row)
    if failures:
        raise ValueError("\n".join(sorted(set(failures))))
    lines = [
        "# Generated by tools/generate_start_mirror.py --write.",
        "# M3 dependency graph; M9 replaces vanilla adapters with ancient contracts.",
        "diplomacy_manager = {",
    ]
    for row in sorted(dependencies, key=lambda item: (item["overlord"], item["subject"])):
        lines.append(
            "\tdependency = { "
            f"first = {tag_map[row['overlord']]} second = {tag_map[row['subject']]} "
            f"subject_type = {row['relationship']} }} "
            f"# {row['source']}: {row['note']}"
        )
    lines.append("}")
    return "\n".join(lines) + "\n", len(dependencies)


def generated_files() -> tuple[dict[str, str], int, int, int, int, Decimal, int]:
    markets, market_count = market_manager()
    pops, pop_locations, pop_total = population_manager()
    countries, count, controlled = country_manager()
    diplomacy, dependencies = diplomacy_manager()
    return (
        {**STATIC_FILES, "03_markets.txt": markets, "06_pops.txt": pops, "10_countries.txt": countries, "12_diplomacy.txt": diplomacy},
        count,
        controlled,
        dependencies,
        pop_locations,
        pop_total,
        market_count,
    )


def installed_start_filenames() -> set[str]:
    config = json.loads((ROOT / "config/local_paths.json").read_text(encoding="utf-8-sig"))
    source = Path(config["game_dir"]) / "game/main_menu/setup/start"
    return {path.name for path in source.glob("*.txt")}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write == args.check:
        parser.error("provide exactly one of --write or --check")
    failures: list[str] = []
    try:
        files, country_count, controlled, dependencies, pop_locations, pop_total, market_count = generated_files()
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"start_mirror: FAIL\n  - {exc}")
        return 1
    if args.write:
        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        for name, content in files.items():
            path = OUTPUT_DIR / name
            path.write_text(content, encoding="utf-8", newline="\n")
            print(f"start_mirror: wrote {path.relative_to(ROOT)}")
        return 0
    actual = {path.name for path in OUTPUT_DIR.glob("*.txt")} if OUTPUT_DIR.is_dir() else set()
    expected = set(files)
    installed = installed_start_filenames()
    if installed != expected:
        failures.append(
            "installed start-manager inventory changed; refresh FILES before relying on the mirror"
        )
    for name in sorted(expected - actual):
        failures.append(f"missing M3 start mirror {name}")
    for name in sorted(actual - expected):
        failures.append(f"unexpected start file {name}; add it to generator inventory")
    for name, content in files.items():
        path = OUTPUT_DIR / name
        if path.is_file() and path.read_text(encoding="utf-8") != content:
            failures.append(f"stale generated start mirror {name}")
    if failures:
        print("start_mirror: FAIL")
        print("\n".join(f"  - {failure}" for failure in failures))
        return 1
    print(
        f"start_mirror: PASS ({len(files)} exact manager filenames; "
        f"{country_count} verified-capital countries; {controlled} controlled locations; "
        f"{dependencies} dependencies; {pop_locations} populated locations; "
        f"{pop_total:,.3f} thousand people; {market_count} M5 markets)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
