#!/usr/bin/env python3
"""Generate ANTIQVITAS's exact-filename M3 start-manager mirror.

Setup managers are additive in EU5.  Replacing every installed start filename
is therefore the only locally verified way to prevent the 1337 snapshot from
surviving beneath the AD 1 database.  Content generators extend these roots in
later M3 batches; this first batch proves the empty roots are valid on build
24187685 before historical ownership is introduced.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from collections import defaultdict
from dataclasses import dataclass
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

from extract_vanilla import tokenize
from generate_country_definitions import historical_profile_for
from m6_power import character_manager, dynasty_manager, government_block, load_power_data
from m7_war import load_units, tag_map as m7_tag_map, validate_start_ledgers
from m8_knowledge import institution_manager as m8_institution_manager, technology_level as m8_technology_level
from m9_diplomacy import (
    START_ADAPTERS,
    discovery_regions as m9_discovery_regions,
    international_organization_manager as m9_international_organization_manager,
)

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT / "main_menu/setup/start"
ROSTER = ROOT / "docs/world_1ad/polities.csv"
TAG_MAP = ROOT / "docs/world_1ad/tag_map.json"
OWNERSHIP = ROOT / "docs/world_1ad/ownership_resolved.csv"
SUBJECTS = ROOT / "docs/world_1ad/subjects.csv"
SUBJECT_TYPES = ROOT / "docs/vanilla_symbols/subject_type.json"
POPULATION_TARGETS = ROOT / "docs/m4/population_targets.csv"
POPULATION_ALLOCATIONS = ROOT / "docs/m4/population_region_allocations.csv"
POPULATION_LOCATION_OVERRIDES = ROOT / "docs/m4/population_location_overrides.csv"
CULTURE_REMAP = ROOT / "docs/culture_remap.csv"
M4_SYMBOLS = ROOT / "docs/m4/definition_symbols.json"
GEOGRAPHY_HIERARCHY = ROOT / "docs/vanilla_symbols/geography_hierarchy.json"
VANILLA_AREAS = ROOT / "docs/vanilla_symbols/areas.json"
VANILLA_PROVINCES = ROOT / "docs/vanilla_symbols/provinces.json"
VANILLA_LOCATIONS = ROOT / "docs/vanilla_symbols/locations.json"
VANILLA_REGIONS = ROOT / "docs/vanilla_symbols/regions.json"
MARKETS = ROOT / "docs/m5/markets.csv"
URBAN_NODES = ROOT / "docs/m5/urban_nodes.csv"
ROAD_SEGMENTS = ROOT / "docs/m5/road_segments.csv"
DEVELOPMENT_PROFILE = ROOT / "docs/m5/development_profile.csv"
SPECIAL_BUILDINGS = ROOT / "docs/m5/special_buildings.csv"
HISTORIC_BUILDING_SITES = ROOT / "docs/m5/historic_building_sites.csv"
M7_FORTS = ROOT / "docs/m7/forts.csv"
M7_ARMIES = ROOT / "docs/m7/armies.csv"
URBAN_SETUP_OUTPUT = ROOT / "in_game/common/town_setups/00_antiquitas.txt"
SUBJECT_FIELDS = ("overlord", "subject", "relationship", "source", "confidence", "note")


def m9_subject_adapter(row: dict[str, str]) -> str:
    """Map the checked AD 1 relationships to M9's ancient mechanics."""
    return START_ADAPTERS.get(row["overlord"], row["relationship"])
THOUSANDTH = Decimal("0.001")

URBAN_TOWN_SETUPS = """# Generated by tools/generate_start_mirror.py --write.
# M5 engine-valid building proxies for AD 1 source-labelled market settlements.
antiqvitas_market_town = {
\ttemple = 1
\tmarketplace = 1
\tentrepot = 1
}

antiqvitas_market_city = {
\ttemple = 1
\tmarketplace = 2
\tentrepot = 1
\tgranary = 1
\tmason = 1
}
"""

STATIC_FILES = {
    "02_core.txt": """institution_manager = {\n}\n\nreligion_manager = {\n}\n""",
    "08_institutions.txt": "locations = {\n}\n",
    "11_art.txt": "work_of_art_manager = {\n}\n",
    "13_religion.txt": "building_manager = {\n}\n",
    "16_wars.txt": "war_manager = {\n}\n",
    "18_opinions.txt": "diplomacy_manager = {\n}\n",
    "19_diseases.txt": "disease_outbreak_manager = {\n}\n",
    "20_rivals.txt": "diplomacy_manager = {\n}\n",
    "21_locations.txt": "locations = {\n}\n",
    "22_situations.txt": "situation_manager = {\n}\n",
    "23_colonies.txt": "colony_manager = {\n}\n",
    "24_town_rights.txt": "townrights_manager = {\n}\n",
    "25_area_preferences.txt": "countries = {\n\tcountries = {\n\t}\n}\n",
    "26_ai_personalities.txt": "countries = {\n\tcountries = {\n\t}\n}\n",
}


@dataclass(frozen=True)
class MacroTarget:
    target: Decimal
    minimum: Decimal | None
    maximum: Decimal | None
    source: str
    confidence: str
    note: str


@dataclass(frozen=True)
class RegionalAllocation:
    macro: str
    target: Decimal
    source: str
    confidence: str
    note: str


def csv_rows(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def market_manager() -> tuple[str, int]:
    """Render source-labelled AD 1 market hubs with installed location keys."""
    locations = set(json.loads((ROOT / "docs/vanilla_symbols/locations.json").read_text(encoding="utf-8-sig")))
    required = ("key", "name", "location", "source", "confidence", "note")
    entries = csv_rows(MARKETS)
    if not entries:
        raise ValueError("markets.csv has no market entries")
    seen_keys: set[str] = set()
    seen_locations: set[str] = set()
    failures: list[str] = []
    for row in entries:
        if any(not row.get(field, "").strip() for field in required):
            failures.append("markets.csv contains a blank required field")
            continue
        key = row["key"].strip()
        location = row["location"].strip()
        if key in seen_keys:
            failures.append(f"markets.csv repeats key {key}")
        if location in seen_locations:
            failures.append(f"markets.csv repeats location {location}")
        if location not in locations:
            failures.append(f"markets.csv {key} uses unknown installed location {location}")
        if row["confidence"].strip() not in {"secure", "contested"}:
            failures.append(f"markets.csv {key} has invalid confidence {row['confidence']}")
        seen_keys.add(key)
        seen_locations.add(location)
    if failures:
        raise ValueError("\n".join(sorted(set(failures))))
    lines = [
        "# Generated by tools/generate_start_mirror.py --write.",
        "# M5 AD 1 market hubs; source and proxy rationale: docs/m5/markets.csv.",
        "market_manager = {",
    ]
    for row in sorted(entries, key=lambda item: item["key"]):
        lines.append(f"\tadd_market = {row['location']} # {row['name']}; {row['source']}")
    lines.extend(("}", ""))
    return "\n".join(lines), len(entries)


def urban_manager() -> tuple[str, int]:
    """Render town ranks and engine-valid market building profiles for M5 hubs."""
    required = ("key", "location", "profile", "source", "confidence", "note")
    market_rows = csv_rows(MARKETS)
    markets = {row["key"]: row for row in market_rows}
    if len(markets) != len(market_rows):
        raise ValueError("markets.csv has duplicate keys")
    entries = csv_rows(URBAN_NODES)
    locations = set(json.loads((ROOT / "docs/vanilla_symbols/locations.json").read_text(encoding="utf-8-sig")))
    valid_buildings = set(json.loads((ROOT / "docs/vanilla_symbols/building.json").read_text(encoding="utf-8-sig")))
    required_buildings = {"temple", "marketplace", "entrepot", "granary", "mason"}
    if required_buildings - valid_buildings:
        raise ValueError(f"installed building symbols missing {sorted(required_buildings - valid_buildings)}")
    owners: dict[str, str] = {}
    with OWNERSHIP.open(encoding="utf-8-sig", newline="") as handle:
        for row in csv.DictReader(line for line in handle if not line.startswith("#")):
            location = row["location"]
            if location in owners:
                raise ValueError(f"ownership has duplicate location {location}")
            owners[location] = row["engine_tag"]
    nodes: dict[str, dict[str, str]] = {}
    failures: list[str] = []
    for row in entries:
        if any(not row.get(field, "").strip() for field in required):
            failures.append("urban_nodes.csv contains a blank required field")
            continue
        key = row["key"].strip()
        location = row["location"].strip()
        if key in nodes:
            failures.append(f"urban_nodes.csv repeats key {key}")
        if key not in markets:
            failures.append(f"urban_nodes.csv has no matching market {key}")
        elif location != markets[key]["location"]:
            failures.append(f"urban_nodes.csv {key} location differs from markets.csv")
        if location not in locations:
            failures.append(f"urban_nodes.csv {key} uses unknown installed location {location}")
        if location not in owners:
            failures.append(f"urban_nodes.csv {key} has no controlled AD 1 location")
        if row["profile"].strip() not in {"town", "city"}:
            failures.append(f"urban_nodes.csv {key} has invalid profile {row['profile']}")
        if row["confidence"].strip() not in {"secure", "contested"}:
            failures.append(f"urban_nodes.csv {key} has invalid confidence {row['confidence']}")
        nodes[key] = row
    missing = sorted(set(markets) - set(nodes))
    if missing:
        failures.append(f"urban_nodes.csv is missing market nodes {missing}")
    if failures:
        raise ValueError("\n".join(sorted(set(failures))))
    lines = [
        "# Generated by tools/generate_start_mirror.py --write.",
        "# M5 AD 1 urban market tiers; sources and proxy rationale: docs/m5/urban_nodes.csv.",
        "locations = {",
    ]
    for key, row in sorted(nodes.items()):
        location = row["location"].strip()
        profile = row["profile"].strip()
        lines.append(
            f"\t{location} = {{ rank = {profile} town_setup = antiqvitas_market_{profile} }} "
            f"# {key}; {row['source']}"
        )
    lines.extend(("}", ""))
    return "\n".join(lines), len(nodes)


def special_building_manager() -> tuple[str, int, int]:
    """Render source-led M5 buildings and M7 fort proxies with verified owners."""
    required = ("key", "location", "building", "level", "source", "confidence", "note")
    entries = [(row, "M5") for row in csv_rows(SPECIAL_BUILDINGS)]
    entries.extend((row, "M7") for row in csv_rows(M7_FORTS))
    if not entries:
        raise ValueError("special_buildings.csv has no specialist-building entries")
    locations = set(json.loads((ROOT / "docs/vanilla_symbols/locations.json").read_text(encoding="utf-8-sig")))
    buildings = set(json.loads((ROOT / "docs/vanilla_symbols/building.json").read_text(encoding="utf-8-sig")))
    urban_locations = {row["location"].strip() for row in csv_rows(URBAN_NODES)}
    owners: dict[str, str] = {}
    with OWNERSHIP.open(encoding="utf-8-sig", newline="") as handle:
        for row in csv.DictReader(line for line in handle if not line.startswith("#")):
            location = row["location"]
            if location in owners:
                raise ValueError(f"ownership has duplicate location {location}")
            owners[location] = row["engine_tag"]
    historic_required = ("key", "location", "source", "confidence", "note")
    historic_sites: set[str] = set()
    historic_keys: set[str] = set()
    site_failures: list[str] = []
    for row in csv_rows(HISTORIC_BUILDING_SITES):
        if any(not row.get(field, "").strip() for field in historic_required):
            site_failures.append("historic_building_sites.csv contains a blank required field")
            continue
        key = row["key"].strip()
        location = row["location"].strip()
        if key in historic_keys:
            site_failures.append(f"historic_building_sites.csv repeats key {key}")
        if location in historic_sites:
            site_failures.append(f"historic_building_sites.csv repeats location {location}")
        if location not in locations:
            site_failures.append(f"historic_building_sites.csv {key} uses unknown installed location {location}")
        if location not in owners:
            site_failures.append(f"historic_building_sites.csv {key} has no controlled AD 1 location")
        if row["confidence"].strip() not in {"secure", "contested"}:
            site_failures.append(f"historic_building_sites.csv {key} has invalid confidence {row['confidence']}")
        historic_keys.add(key)
        historic_sites.add(location)
    if site_failures:
        raise ValueError("\n".join(sorted(set(site_failures))))
    failures: list[str] = []
    seen_keys: set[str] = set()
    seen_buildings: set[tuple[str, str]] = set()
    fort_count = 0
    for row, layer in entries:
        if any(not row.get(field, "").strip() for field in required):
            failures.append(f"{layer} building ledger contains a blank required field")
            continue
        key = row["key"].strip()
        location = row["location"].strip()
        building = row["building"].strip()
        try:
            level = int(row["level"])
        except ValueError:
            failures.append(f"{layer} building ledger {key} has non-integer level {row['level']}")
            continue
        if key in seen_keys:
            failures.append(f"building ledgers repeat key {key}")
        pair = (location, building)
        if pair in seen_buildings:
            failures.append(f"building ledgers repeat {building} at {location}")
        if location not in locations:
            failures.append(f"{layer} building ledger {key} uses unknown installed location {location}")
        if location not in owners:
            failures.append(f"{layer} building ledger {key} has no controlled AD 1 location")
        if layer == "M5" and location not in urban_locations | historic_sites:
            failures.append(f"special_buildings.csv {key} is not an AD 1 market node or historic site")
        if layer == "M7" and building != "stockade":
            failures.append(f"forts.csv {key} must use the verified stockade proxy")
        if building not in buildings:
            failures.append(f"{layer} building ledger {key} uses unknown installed building {building}")
        if not 1 <= level <= 10:
            failures.append(f"{layer} building ledger {key} level must be 1 through 10")
        if row["confidence"].strip() not in {"secure", "contested"}:
            failures.append(f"{layer} building ledger {key} has invalid confidence {row['confidence']}")
        seen_keys.add(key)
        seen_buildings.add(pair)
        fort_count += layer == "M7"
    if failures:
        raise ValueError("\n".join(sorted(set(failures))))
    lines = [
        "# M5 specialist buildings plus M7 castra/limes proxies; source rationale: docs/m5/ and docs/m7/.",
        "building_manager = {",
    ]
    for row, _layer in sorted(entries, key=lambda item: item[0]["key"]):
        location = row["location"].strip()
        lines.append(
            f"\t{row['building'].strip()} = {{ tag = {owners[location]} level = {row['level'].strip()} "
            f"location = {location} }} # {row['key'].strip()}; {row['source'].strip()}"
        )
    lines.extend(("}", ""))
    return "\n".join(lines), len(entries), fort_count


def m7_unit_manager() -> tuple[str, int]:
    """Render M7's source-labelled army and navy seeds into the exact start manager."""
    units = load_units()
    validate_start_ledgers(units)
    unit_keys = {unit.key for unit in units}
    tags = m7_tag_map()
    entries = csv_rows(M7_ARMIES)
    groups: dict[str, list[dict[str, str]]] = {}
    for row in entries:
        if row["unit_type"] not in unit_keys:
            raise ValueError(f"armies.csv references unknown M7 unit {row['unit_type']}")
        groups.setdefault(row["key"], []).append(row)
    lines = [
        "# Generated by tools/generate_start_mirror.py --write.",
        "# M7 technical force seeds; sources state broad force context, never a reconstructed order of battle.",
        "unit_manager = {",
    ]
    for key in sorted(groups):
        rows = groups[key]
        first = rows[0]
        lines.extend((
            f"\t{first['kind']} = {{",
            f"\t\tcountry = {tags[first['country']]}",
            f"\t\tlocation = {first['location']}",
            "\t\tsub_units = {",
        ))
        lines.extend(f"\t\t\t{row['unit_type']} = {{ strength = {row['strength']} }}" for row in rows)
        lines.extend(("\t\t}", "\t}", ""))
    lines.extend(("}", ""))
    return "\n".join(lines), len(groups)


def road_network() -> tuple[str, int]:
    """Render a small, source-labelled AD 1 road network using installed syntax."""
    required = ("origin", "destination", "corridor", "source", "confidence", "note")
    locations = set(json.loads((ROOT / "docs/vanilla_symbols/locations.json").read_text(encoding="utf-8-sig")))
    controlled: set[str] = set()
    with OWNERSHIP.open(encoding="utf-8-sig", newline="") as handle:
        for row in csv.DictReader(line for line in handle if not line.startswith("#")):
            controlled.add(row["location"])
    entries = csv_rows(ROAD_SEGMENTS)
    if not entries:
        raise ValueError("road_segments.csv has no segments")
    failures: list[str] = []
    seen: set[tuple[str, str]] = set()
    for row in entries:
        if any(not row.get(field, "").strip() for field in required):
            failures.append("road_segments.csv contains a blank required field")
            continue
        origin, destination = row["origin"].strip(), row["destination"].strip()
        if origin == destination:
            failures.append(f"road_segments.csv has a self-link at {origin}")
        pair = tuple(sorted((origin, destination)))
        if pair in seen:
            failures.append(f"road_segments.csv duplicates undirected segment {pair[0]}-{pair[1]}")
        if origin not in locations or destination not in locations:
            failures.append(f"road_segments.csv has unknown installed endpoint {origin}-{destination}")
        if origin not in controlled or destination not in controlled:
            failures.append(f"road_segments.csv has endpoint outside AD 1 control {origin}-{destination}")
        if row["confidence"].strip() not in {"secure", "contested"}:
            failures.append(f"road_segments.csv {origin}-{destination} has invalid confidence")
        seen.add(pair)
    if failures:
        raise ValueError("\n".join(sorted(set(failures))))
    lines = [
        "# Generated by tools/generate_start_mirror.py --write.",
        "# M5 AD 1 road corridors; source and route rationale: docs/m5/road_segments.csv.",
        "# Bare endpoint syntax matches the installed start manager's base-road contract.",
        "road_network = {",
    ]
    for row in sorted(entries, key=lambda item: (item["origin"], item["destination"])):
        lines.append(
            f"\t{row['origin']} = {row['destination']} # {row['corridor']}; {row['source']}"
        )
    lines.extend(("}", ""))
    return "\n".join(lines), len(entries)


def development_manager() -> tuple[str, int]:
    """Render the transparent M5 rank-and-road development foundation."""
    required = ("selector", "value", "source", "confidence", "note")
    allowed = {"base", "road", "town", "city"}
    locations = set(json.loads((ROOT / "docs/vanilla_symbols/locations.json").read_text(encoding="utf-8-sig")))
    controlled: set[str] = set()
    with OWNERSHIP.open(encoding="utf-8-sig", newline="") as handle:
        for row in csv.DictReader(line for line in handle if not line.startswith("#")):
            controlled.add(row["location"])
    entries = csv_rows(DEVELOPMENT_PROFILE)
    selectors: set[str] = set()
    failures: list[str] = []
    for row in entries:
        if any(not row.get(field, "").strip() for field in required):
            failures.append("development_profile.csv contains a blank required field")
            continue
        selector = row["selector"].strip()
        if selector in selectors:
            failures.append(f"development_profile.csv repeats selector {selector}")
        if selector not in allowed and selector not in locations:
            failures.append(f"development_profile.csv has unknown selector {selector}")
        if selector in locations and selector not in controlled:
            failures.append(f"development_profile.csv has uncontrolled location {selector}")
        try:
            value = Decimal(row["value"])
        except Exception:
            failures.append(f"development_profile.csv {selector} has invalid value {row['value']!r}")
        else:
            if value < -10 or value > 30:
                failures.append(f"development_profile.csv {selector} value is outside -10..30")
        if row["confidence"].strip() not in {"secure", "contested"}:
            failures.append(f"development_profile.csv {selector} has invalid confidence")
        selectors.add(selector)
    required_selectors = {"base", "road", "town", "city"}
    if selectors != required_selectors:
        failures.append(
            f"development_profile.csv selectors must be exactly {sorted(required_selectors)} for this foundation"
        )
    if failures:
        raise ValueError("\n".join(sorted(set(failures))))
    values = {row["selector"].strip(): row["value"].strip() for row in entries}
    lines = [
        "# Generated by tools/generate_start_mirror.py --write.",
        "# M5 technical development scaling; historical evidence remains in M4 population and M5 urban ledgers.",
        "development = {",
    ]
    for selector in ("base", "road", "town", "city"):
        lines.append(f"\t{selector} = {values[selector]}")
    lines.extend(("}", ""))
    return "\n".join(lines), len(entries)


def decimal_field(row: dict[str, str], field: str, path: Path) -> Decimal:
    value = row.get(field, "").strip()
    if not value:
        raise ValueError(f"{path.relative_to(ROOT)} has a blank {field}")
    try:
        parsed = Decimal(value)
    except Exception as exc:
        raise ValueError(f"{path.relative_to(ROOT)} has invalid {field}={value!r}") from exc
    if parsed <= 0:
        raise ValueError(f"{path.relative_to(ROOT)} has non-positive {field}={value!r}")
    return parsed


def load_population_plan() -> tuple[dict[str, MacroTarget], dict[str, RegionalAllocation]]:
    """Read the auditable M4 population targets and regional allocation plan."""
    macros: dict[str, MacroTarget] = {}
    for row in csv_rows(POPULATION_TARGETS):
        macro = row.get("macro", "").strip()
        if not macro or macro in macros:
            raise ValueError(f"{POPULATION_TARGETS.relative_to(ROOT)} has invalid or duplicate macro {macro!r}")
        minimum = row.get("min_thousands", "").strip()
        maximum = row.get("max_thousands", "").strip()
        if bool(minimum) != bool(maximum):
            raise ValueError(f"{POPULATION_TARGETS.relative_to(ROOT)} {macro}: min/max must both be set or blank")
        for field in ("source", "confidence", "note"):
            if not row.get(field, "").strip():
                raise ValueError(f"{POPULATION_TARGETS.relative_to(ROOT)} {macro}: blank {field}")
        macros[macro] = MacroTarget(
            decimal_field(row, "target_thousands", POPULATION_TARGETS),
            Decimal(minimum) if minimum else None,
            Decimal(maximum) if maximum else None,
            row["source"].strip(),
            row["confidence"].strip(),
            row["note"].strip(),
        )
    if "world" not in macros:
        raise ValueError(f"{POPULATION_TARGETS.relative_to(ROOT)} must define a world target")
    allocations: dict[str, RegionalAllocation] = {}
    for row in csv_rows(POPULATION_ALLOCATIONS):
        region = row.get("region", "").strip()
        macro = row.get("macro", "").strip()
        if not region or region in allocations:
            raise ValueError(f"{POPULATION_ALLOCATIONS.relative_to(ROOT)} has invalid or duplicate region {region!r}")
        if macro not in macros or macro == "world":
            raise ValueError(f"{POPULATION_ALLOCATIONS.relative_to(ROOT)} {region}: unknown macro {macro!r}")
        for field in ("source", "confidence", "note"):
            if not row.get(field, "").strip():
                raise ValueError(f"{POPULATION_ALLOCATIONS.relative_to(ROOT)} {region}: blank {field}")
        allocations[region] = RegionalAllocation(
            macro,
            decimal_field(row, "target_thousands", POPULATION_ALLOCATIONS),
            row["source"].strip(),
            row["confidence"].strip(),
            row["note"].strip(),
        )
    allocated = defaultdict(Decimal)
    for allocation in allocations.values():
        allocated[allocation.macro] += allocation.target
    for macro, target in macros.items():
        if macro == "world":
            continue
        if allocated[macro] != target.target:
            raise ValueError(
                f"{macro} allocations total {allocated[macro]} but target is {target.target} thousand"
            )
    if sum(allocated.values(), Decimal()) != macros["world"].target:
        raise ValueError(
            f"regional allocations total {sum(allocated.values(), Decimal())} but world target is "
            f"{macros['world'].target} thousand"
        )
    return macros, allocations


def population_location_overrides(
    owners: dict[str, str],
    allocations: dict[str, RegionalAllocation],
) -> dict[str, dict[str, str]]:
    """Load exceptional source-led populations without treating political
    ownership as proof of a uniform local culture or religion.
    """
    required = ("location", "culture", "religion", "pop_type", "region", "source", "confidence", "note")
    rows = csv_rows(POPULATION_LOCATION_OVERRIDES)
    overrides: dict[str, dict[str, str]] = {}
    failures: list[str] = []
    for row in rows:
        location = row.get("location", "").strip()
        if any(not row.get(field, "").strip() for field in required):
            failures.append(f"{POPULATION_LOCATION_OVERRIDES.relative_to(ROOT)} has a blank required field")
            continue
        if location in overrides:
            failures.append(f"{POPULATION_LOCATION_OVERRIDES.relative_to(ROOT)} repeats {location}")
        elif location not in owners:
            failures.append(f"{POPULATION_LOCATION_OVERRIDES.relative_to(ROOT)} {location} is not controlled")
        elif row["region"].strip() not in allocations:
            failures.append(f"{POPULATION_LOCATION_OVERRIDES.relative_to(ROOT)} {location} has an unknown region")
        elif row["confidence"].strip() not in {"secure", "contested"}:
            failures.append(f"{POPULATION_LOCATION_OVERRIDES.relative_to(ROOT)} {location} has invalid confidence")
        elif row["pop_type"].strip() not in {"peasants", "tribesmen"}:
            failures.append(f"{POPULATION_LOCATION_OVERRIDES.relative_to(ROOT)} {location} has invalid pop_type")
        else:
            overrides[location] = {key: value.strip() for key, value in row.items()}
    if failures:
        raise ValueError("\n".join(sorted(set(failures))))
    return overrides


def population_culture_remaps(owners: dict[str, str]) -> dict[str, dict[str, str]]:
    """Resolve the source-labelled M4 culture atlas to exact owned locations.

    The source ledger deliberately accepts installed geographic selectors, not
    vanilla culture keys.  Thus an area can be assigned only after a historical
    judgment is recorded with its source, and a selector's concrete location
    expansion stays auditable after a map patch.  A narrower, independently
    sourced selector may refine a broader regional frame: precedence is
    location > province > area > region.  Equally specific overlap remains an
    error, so the ledger cannot silently choose between competing historical
    claims.  Location overrides remain the final, higher-precedence exception
    for places such as the Rinan/Linyi frontier.
    """
    required = ("selector_type", "selector", "culture", "source", "confidence", "note")
    with CULTURE_REMAP.open(encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        if tuple(reader.fieldnames or ()) != required:
            raise ValueError(
                f"{CULTURE_REMAP.relative_to(ROOT)} must use header {','.join(required)}"
            )
        rows = list(reader)
    if not rows:
        raise ValueError(f"{CULTURE_REMAP.relative_to(ROOT)} has no remap rows")

    m4_symbols = json.loads(M4_SYMBOLS.read_text(encoding="utf-8"))
    cultures = set(m4_symbols["cultures"])
    hierarchy = json.loads(GEOGRAPHY_HIERARCHY.read_text(encoding="utf-8-sig"))
    valid = {
        "area": set(json.loads(VANILLA_AREAS.read_text(encoding="utf-8-sig"))),
        "province": set(json.loads(VANILLA_PROVINCES.read_text(encoding="utf-8-sig"))),
        "location": set(json.loads(VANILLA_LOCATIONS.read_text(encoding="utf-8-sig"))),
        "region": set(json.loads(VANILLA_REGIONS.read_text(encoding="utf-8-sig"))),
    }

    def leaves(selector: str, trail: tuple[str, ...] = ()) -> set[str]:
        if selector in trail:
            raise ValueError(
                f"{CULTURE_REMAP.relative_to(ROOT)} has cyclic geography selector "
                f"{' -> '.join((*trail, selector))}"
            )
        children = hierarchy.get(selector)
        # The harvested hierarchy can list a location alongside its subordinate
        # locations (for example ``kilkenny`` -> ``cullahill``, ``kilkenny``).
        # Treat that direct self member as a leaf while retaining strict cycle
        # detection for every indirect loop.
        if not children:
            return {selector}
        resolved: set[str] = set()
        for child in children:
            if child == selector:
                resolved.add(child)
            else:
                resolved.update(leaves(child, (*trail, selector)))
        return resolved

    remaps: dict[str, dict[str, str]] = {}
    specificity = {"region": 0, "area": 1, "province": 2, "location": 3}
    selectors: set[tuple[str, str]] = set()
    failures: list[str] = []
    for number, row in enumerate(rows, start=2):
        values = {key: row.get(key, "").strip() for key in required}
        if any(not values[key] for key in required):
            failures.append(f"{CULTURE_REMAP.relative_to(ROOT)}:{number}: blank required field")
            continue
        selector_type = values["selector_type"]
        selector = values["selector"]
        selector_key = (selector_type, selector)
        if selector_type not in valid:
            failures.append(
                f"{CULTURE_REMAP.relative_to(ROOT)}:{number}: invalid selector type {selector_type}"
            )
            continue
        if selector not in valid[selector_type]:
            failures.append(
                f"{CULTURE_REMAP.relative_to(ROOT)}:{number}: unknown {selector_type} {selector}"
            )
            continue
        if selector_key in selectors:
            failures.append(
                f"{CULTURE_REMAP.relative_to(ROOT)}:{number}: duplicate selector {selector_type} {selector}"
            )
            continue
        selectors.add(selector_key)
        if values["culture"] not in cultures:
            failures.append(
                f"{CULTURE_REMAP.relative_to(ROOT)}:{number}: unknown M4 culture {values['culture']}"
            )
            continue
        if values["confidence"] not in {"secure", "contested"}:
            failures.append(
                f"{CULTURE_REMAP.relative_to(ROOT)}:{number}: invalid confidence {values['confidence']}"
            )
            continue
        selected = leaves(selector) & set(owners)
        if not selected:
            failures.append(
                f"{CULTURE_REMAP.relative_to(ROOT)}:{number}: {selector_type} {selector} has no controlled locations"
            )
            continue
        for location in selected:
            existing = remaps.get(location)
            if existing:
                current_rank = specificity[selector_type]
                existing_rank = specificity[existing["selector_type"]]
                if current_rank == existing_rank:
                    failures.append(
                        f"{CULTURE_REMAP.relative_to(ROOT)}:{number}: equally-specific overlap at {location} from "
                        f"{existing['selector_type']} {existing['selector']}"
                    )
                    continue
                if current_rank < existing_rank:
                    continue
            remaps[location] = values
    if failures:
        raise ValueError("\n".join(sorted(set(failures))))
    return remaps


def vanilla_pop_weights() -> dict[str, Decimal]:
    """Read installed-pop density as a geographic weighting template only."""
    config = json.loads((ROOT / "config/local_paths.json").read_text(encoding="utf-8-sig"))
    source = Path(config["game_dir"]) / "game/main_menu/setup/start/06_pops.txt"
    if not source.is_file():
        raise ValueError(f"installed vanilla pop template is missing: {source}")
    tokens = list(tokenize(source.read_text(encoding="utf-8-sig", errors="replace")))
    stack: list[str] = []
    weights: defaultdict[str, Decimal] = defaultdict(Decimal)
    index = 0
    while index < len(tokens):
        value = tokens[index].value
        if (
            index + 2 < len(tokens)
            and tokens[index + 1].value == "="
            and tokens[index + 2].value == "{"
        ):
            stack.append(value)
            index += 3
            continue
        if value == "}":
            if stack:
                stack.pop()
            index += 1
            continue
        if (
            value == "size"
            and index + 2 < len(tokens)
            and tokens[index + 1].value == "="
            and len(stack) == 3
            and stack[0] == "locations"
            and stack[2] == "define_pop"
        ):
            try:
                weights[stack[1]] += Decimal(tokens[index + 2].value)
            except Exception as exc:
                raise ValueError(f"invalid vanilla pop size at {stack[1]}") from exc
            index += 3
            continue
        index += 1
    if not weights:
        raise ValueError("could not read any installed vanilla population weights")
    return dict(weights)


def population_manager() -> tuple[str, int, Decimal]:
    """Render all controlled AD 1 locations against section 12.4 target totals."""
    roster_rows = csv_rows(ROSTER)
    roster = {row["tag"]: row for row in roster_rows}
    macros, allocations = load_population_plan()
    roster_regions = {row["region"] for row in roster_rows}
    missing_regions = sorted(roster_regions - set(allocations))
    extra_regions = sorted(set(allocations) - roster_regions)
    if missing_regions or extra_regions:
        raise ValueError(f"population regional coverage mismatch; missing={missing_regions}, extra={extra_regions}")
    owners: dict[str, str] = {}
    with OWNERSHIP.open(encoding="utf-8-sig", newline="") as handle:
        for entry in csv.DictReader(line for line in handle if not line.startswith("#")):
            location = entry["location"]
            tag = entry["tag"]
            if tag not in roster:
                raise ValueError(f"population ownership references unknown tag {tag}")
            if location in owners:
                raise ValueError(f"population ownership assigns {location} more than once")
            owners[location] = tag
    overrides = population_location_overrides(owners, allocations)
    culture_remaps = population_culture_remaps(owners)
    weights = vanilla_pop_weights()
    by_region: defaultdict[str, list[str]] = defaultdict(list)
    for location, tag in owners.items():
        by_region[overrides.get(location, {}).get("region", roster[tag]["region"])].append(location)
    floor = Decimal("0.050")
    sizes: dict[str, Decimal] = {}
    for region, locations in by_region.items():
        target = allocations[region].target
        ordered = sorted(locations)
        regional_weights = {location: max(weights.get(location, Decimal()), floor) for location in ordered}
        total_weight = sum(regional_weights.values(), Decimal())
        if not total_weight:
            raise ValueError(f"population region {region} has no usable geographic weight")
        scaled = {
            location: (regional_weights[location] * target / total_weight).quantize(
                THOUSANDTH, rounding=ROUND_HALF_UP
            )
            for location in ordered
        }
        correction = target - sum(scaled.values(), Decimal())
        largest = max(ordered, key=lambda location: (regional_weights[location], location))
        scaled[largest] += correction
        if scaled[largest] <= 0:
            raise ValueError(f"population rounding made {largest} non-positive")
        sizes.update(scaled)
    lines = [
        "# Generated by tools/generate_start_mirror.py --write.",
        "# M4 AD 1 population totals: plan section 12.4; regional allocation is source-labelled in docs/m4/.",
        "# Installed vanilla density is a geographic weighting template only, never a historical population source.",
        "locations = {",
    ]
    for location in sorted(owners):
        row = roster[owners[location]]
        profile = historical_profile_for(row)
        override = overrides.get(location, {})
        pop_type = override.get("pop_type", "tribesmen" if row["kind"] == "sop" else "peasants")
        culture = override.get("culture", culture_remaps.get(location, {}).get("culture", profile.culture))
        religion = override.get("religion", profile.religion)
        lines.extend(
            (
                f"\t{location} = {{",
                f"\t\tdefine_pop = {{ type = {pop_type} size = {sizes[location]:.3f} "
                f"culture = {culture} religion = {religion} }}",
                "\t}",
            )
        )
    lines.extend(("}", ""))
    return "\n".join(lines), len(owners), sum(sizes.values(), Decimal())


def country_manager() -> tuple[str, int, int]:
    """Render M3 countries from checked ownership plus verified capitals.

    Generic random-ruler scaffolding remains only for countries outside the
    source-labelled M6 foundation. M6 country profiles are generated from the
    checked `docs/m6/governments.csv` ledger.
    """
    with ROSTER.open(encoding="utf-8-sig", newline="") as handle:
        rows = list(csv.DictReader(handle))
    tag_map = {
        entry["design_tag"]: entry["engine_tag"]
        for entry in json.loads(TAG_MAP.read_text(encoding="utf-8"))["entries"]
    }
    power = load_power_data()
    ownership: dict[str, dict[str, list[str]]] = {}
    with OWNERSHIP.open(encoding="utf-8-sig", newline="") as handle:
        for entry in csv.DictReader(line for line in handle if not line.startswith("#")):
            ownership.setdefault(entry["tag"], {}).setdefault(entry["tenure"], []).append(
                entry["location"]
            )
    lines = [
        "# Generated by tools/generate_start_mirror.py --write.",
        "# M3 political-map slice; generated only from sourced ownership data.",
        "current_age = age_1_traditions",
        "",
        "countries = {",
        "\tcountries = {",
    ]
    count = 0
    controlled = 0
    for row in rows:
        capital = row["map_capital"]
        if capital == "TBD":
            continue
        template = "asia_advanced_tribe" if row["kind"] == "sop" else "east_asia_monarchy"
        lines.append(f'\t\t{tag_map[row["tag"]]} = {{ # {row["name"]}; {row["source"]}')
        groups = ownership.get(row["tag"], {"own_control_core": [capital]})
        for tenure in sorted(groups):
            locations = sorted(set(groups[tenure]))
            lines.append(f"\t\t\t{tenure} = {{")
            lines.extend(f"\t\t\t\t{location}" for location in locations)
            lines.extend(("\t\t\t}", ""))
            controlled += len(locations)
        lines.append(f'\t\t\tinclude = "{template}"')
        lines.append(f'\t\t\tstarting_technology_level = {m8_technology_level(row)}')
        lines.append("\t\t\tdiscovered_regions = {")
        lines.extend(f"\t\t\t\t{region}" for region in m9_discovery_regions(row))
        lines.append("\t\t\t}")
        if row["tag"] in power.governments:
            lines.extend(government_block(power.governments[row["tag"]]))
        else:
            lines.append("\t\t\tgovernment = { ruler = random }")
        lines.extend((f"\t\t\tcapital = {capital}", "\t\t}", ""))
        count += 1
    lines.extend(("\t}", "}"))
    return "\n".join(lines) + "\n", count, controlled


def diplomacy_manager() -> tuple[str, int]:
    """Render the current M3 subject graph with locally verified mechanics.

    M3 uses the engine's current vassal/tributary contracts only as a clean
    political-map adapter. M9 replaces those entries with the plan's bespoke
    client-kingdom, satrapy, tributary, and foederati subject mechanics.
    """
    with ROSTER.open(encoding="utf-8-sig", newline="") as handle:
        roster = {row["tag"]: row for row in csv.DictReader(handle)}
    tag_map = {
        entry["design_tag"]: entry["engine_tag"]
        for entry in json.loads(TAG_MAP.read_text(encoding="utf-8"))["entries"]
    }
    subject_types = set(json.loads(SUBJECT_TYPES.read_text(encoding="utf-8-sig")))
    failures: list[str] = []
    seen_subjects: set[str] = set()
    dependencies: list[dict[str, str]] = []
    with SUBJECTS.open(encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        if tuple(reader.fieldnames or ()) != SUBJECT_FIELDS:
            raise ValueError("subjects.csv header does not match required field order")
        for row in reader:
            if any(not row[field].strip() for field in SUBJECT_FIELDS):
                failures.append("subjects.csv contains a blank required field")
                continue
            for tag in (row["overlord"], row["subject"]):
                if tag not in roster:
                    failures.append(f"subjects.csv references unknown roster tag {tag}")
                elif roster[tag]["map_capital"] == "TBD":
                    failures.append(f"subjects.csv references {tag} before its capital is mapped")
            adapter = m9_subject_adapter(row)
            if adapter not in subject_types and adapter not in set(START_ADAPTERS.values()):
                failures.append(f"unknown installed subject type {adapter}")
            if row["confidence"] not in {"secure", "contested"}:
                failures.append(f"invalid confidence {row['confidence']} for {row['subject']}")
            if row["subject"] in seen_subjects:
                failures.append(f"{row['subject']} has more than one M3 overlord")
            seen_subjects.add(row["subject"])
            dependencies.append(row)
    if failures:
        raise ValueError("\n".join(sorted(set(failures))))
    lines = [
        "# Generated by tools/generate_start_mirror.py --write.",
        "# M3 dependency graph; M9 replaces vanilla adapters with ancient contracts.",
        "diplomacy_manager = {",
    ]
    for row in sorted(dependencies, key=lambda item: (item["overlord"], item["subject"])):
        lines.append(
            "\tdependency = { "
            f"first = {tag_map[row['overlord']]} second = {tag_map[row['subject']]} "
                f"subject_type = {m9_subject_adapter(row)} }} "
            f"# {row['source']}: {row['note']}"
        )
    lines.append("}")
    return "\n".join(lines) + "\n", len(dependencies)


def generated_files() -> tuple[dict[str, str], int, int, int, int, Decimal, int, int, int, int, int, int, int]:
    markets, market_count = market_manager()
    urban, urban_count = urban_manager()
    special_buildings, special_building_count, fort_count = special_building_manager()
    units, unit_manager_count = m7_unit_manager()
    roads, road_count = road_network()
    development, development_count = development_manager()
    pops, pop_locations, pop_total = population_manager()
    power = load_power_data()
    countries, count, controlled = country_manager()
    diplomacy, dependencies = diplomacy_manager()
    return (
        {
            **STATIC_FILES,
            "02_core.txt": m8_institution_manager() + "religion_manager = {\n}\n",
            "03_markets.txt": markets,
            "04_dynasties.txt": dynasty_manager(power),
            "05_characters.txt": character_manager(power),
            "06_pops.txt": pops,
            "07_cities_and_buildings.txt": urban + "\n" + special_buildings,
            "09_roads.txt": roads,
            "10_countries.txt": countries,
            "12_diplomacy.txt": diplomacy,
            "14_development.txt": development,
            "15_international_organizations.txt": m9_international_organization_manager(),
            "27_armies.txt": units,
        },
        count,
        controlled,
        dependencies,
        pop_locations,
        pop_total,
        market_count,
        urban_count,
        special_building_count,
        fort_count,
        unit_manager_count,
        road_count,
        development_count,
    )


def installed_start_filenames() -> set[str]:
    config = json.loads((ROOT / "config/local_paths.json").read_text(encoding="utf-8-sig"))
    source = Path(config["game_dir"]) / "game/main_menu/setup/start"
    return {path.name for path in source.glob("*.txt")}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write == args.check:
        parser.error("provide exactly one of --write or --check")
    failures: list[str] = []
    try:
        (
            files,
            country_count,
            controlled,
            dependencies,
            pop_locations,
            pop_total,
            market_count,
            urban_count,
            special_building_count,
            fort_count,
            unit_manager_count,
            road_count,
            development_count,
        ) = generated_files()
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"start_mirror: FAIL\n  - {exc}")
        return 1
    if args.write:
        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        for name, content in files.items():
            path = OUTPUT_DIR / name
            path.write_text(content, encoding="utf-8", newline="\n")
            print(f"start_mirror: wrote {path.relative_to(ROOT)}")
        URBAN_SETUP_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        URBAN_SETUP_OUTPUT.write_text(URBAN_TOWN_SETUPS, encoding="utf-8-sig", newline="\n")
        print(f"start_mirror: wrote {URBAN_SETUP_OUTPUT.relative_to(ROOT)}")
        return 0
    actual = {path.name for path in OUTPUT_DIR.glob("*.txt")} if OUTPUT_DIR.is_dir() else set()
    expected = set(files)
    installed = installed_start_filenames()
    if installed != expected:
        failures.append(
            "installed start-manager inventory changed; refresh FILES before relying on the mirror"
        )
    for name in sorted(expected - actual):
        failures.append(f"missing M3 start mirror {name}")
    for name in sorted(actual - expected):
        failures.append(f"unexpected start file {name}; add it to generator inventory")
    for name, content in files.items():
        path = OUTPUT_DIR / name
        if path.is_file() and path.read_text(encoding="utf-8") != content:
            failures.append(f"stale generated start mirror {name}")
    if not URBAN_SETUP_OUTPUT.is_file() or URBAN_SETUP_OUTPUT.read_text(encoding="utf-8-sig") != URBAN_TOWN_SETUPS:
        failures.append(f"stale or missing M5 town setup {URBAN_SETUP_OUTPUT.relative_to(ROOT)}")
    if failures:
        print("start_mirror: FAIL")
        print("\n".join(f"  - {failure}" for failure in failures))
        return 1
    print(
        f"start_mirror: PASS ({len(files)} exact manager filenames; "
        f"{country_count} verified-capital countries; {controlled} controlled locations; "
        f"{dependencies} dependencies; {pop_locations} populated locations; "
        f"{pop_total:,.3f} thousand people; {market_count} M5 markets; {urban_count} M5 urban nodes; "
        f"{special_building_count} M5/M7 buildings including {fort_count} M7 forts; "
        f"{unit_manager_count} M7 force seeds; {road_count} M5 road segments; "
        f"{development_count} M5 development selectors)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
