#!/usr/bin/env python3
"""Generate the shared readable panel layout for every ANTIQVITAS situation."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SITUATION_DIR = ROOT / "in_game/common/situations"
PANEL_DIR = ROOT / "in_game/gui/panels/situation"
EVENT_ART_DIR = ROOT / "main_menu/gfx/interface/illustrations/event"
FALLBACK_ART = "gfx/interface/illustrations/situation/antq_m10_immensum_bellum.dds"
CONFIG = ROOT / "config/local_paths.json"
COMMON_RELATIVE = Path("game/in_game/gui/panels/situation/common.gui")
COMMON_OUTPUT = PANEL_DIR / "common.gui"
COMMON_SHA256 = "8b5b0ed89f86a0890a5aba512934205e093360d40a4a5a11f52b3dd2e353a35c"


def common_panel_script() -> str:
    game_dir = Path(json.loads(CONFIG.read_text(encoding="utf-8"))["game_dir"])
    source = (game_dir / COMMON_RELATIVE).read_text(encoding="utf-8-sig")
    digest = hashlib.sha256(source.encode("utf-8")).hexdigest()
    if digest != COMMON_SHA256:
        raise ValueError(f"installed common situation panel changed: {digest}")
    marker = '\t\t\t\t\t\t\t\t\tblock "situation_panel_main_content" {}'
    generic_content = '''\t\t\t\t\t\t\t\t\tblock "situation_panel_main_content" {
\t\t\t\t\t\t\t\t\t\tvbox = {
\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = expanding
\t\t\t\t\t\t\t\t\t\t\tmargin = { 10 10 }
\t\t\t\t\t\t\t\t\t\t\tspacing = 6
\t\t\t\t\t\t\t\t\t\t\ttext_single = {
\t\t\t\t\t\t\t\t\t\t\t\tlayoutpolicy_horizontal = expanding
\t\t\t\t\t\t\t\t\t\t\t\talign = center
\t\t\t\t\t\t\t\t\t\t\t\ttext = "[SituationView.GetActiveSituation.GetName]"
\t\t\t\t\t\t\t\t\t\t\t\tdefault_format = "#header_titles"
\t\t\t\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t\t\t\t\tsituation_card_expandable = {
\t\t\t\t\t\t\t\t\t\t\t\tblockoverride "header_button_onclick" {
\t\t\t\t\t\t\t\t\t\t\t\t\tonclick = "[LateralView.Vars.Toggle( 'requirements_toggled' )]"
\t\t\t\t\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t\t\t\t\t\tblockoverride "header_text" { text = "END_REQUIREMENTS" }
\t\t\t\t\t\t\t\t\t\t\t\tblockoverride "header_icon" { texture = "gfx/interface/icons/disasters/end_requirements_green.dds" }
\t\t\t\t\t\t\t\t\t\t\t\tblockoverride "bottom_content" {
\t\t\t\t\t\t\t\t\t\t\t\t\tTooltipRequirementsList = {
\t\t\t\t\t\t\t\t\t\t\t\t\t\ttextcontext = "[SituationView.GetActiveSituation.GetSituation.GetEndConditions]"
\t\t\t\t\t\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t\t\t}'''
    if source.count(marker) != 1:
        raise ValueError("installed common situation panel has no unique main-content marker")
    rendered = source.replace(marker, generic_content)
    # Canonicalize whitespace in the generated overlay so the file participates
    # cleanly in repository diff checks without changing its GUI semantics.
    return "\n".join(line.rstrip() for line in rendered.splitlines()) + "\n"


def situation_keys() -> tuple[str, ...]:
    keys: list[str] = []
    for path in sorted(SITUATION_DIR.glob("antq_*.txt")):
        keys.extend(re.findall(r"(?m)^(antq_[a-z0-9_]+)\s*=\s*\{", path.read_text(encoding="utf-8-sig")))
    if len(keys) != len(set(keys)):
        raise ValueError("ancient situation keys are not unique")
    if len(keys) != 43:
        raise ValueError(f"expected 43 ancient situations, found {len(keys)}")
    return tuple(keys)


def illustration(key: str) -> str:
    event_name = key.removeprefix("antq_m10_")
    candidate = EVENT_ART_DIR / f"antq_{event_name}.dds"
    if candidate.is_file():
        return f"gfx/interface/illustrations/event/{candidate.name}"
    return FALLBACK_ART


def panel_script(key: str) -> str:
    progress = f"{key}_resolution_progress"
    return f'''# Generated by tools/m10_situation_panels.py --write; do not edit directly.
# Uses the installed common situation-panel contract with ANTIQVITAS content.
situation_panel = {{
	blockoverride "situation_panel_image" {{
		background = {{
			texture = "{illustration(key)}"
		}}
		using = scene_fade_vertical_up
	}}

	blockoverride "situation_panel_main_content" {{
		vbox = {{
			layoutpolicy_horizontal = expanding
			margin = {{ 10 10 }}
			spacing = 6
			text_single = {{
				layoutpolicy_horizontal = expanding
				align = center
				text = "[SituationView.GetActiveSituation.GetName]"
				default_format = "#header_titles"
			}}
			text_multi = {{
				layoutpolicy_horizontal = expanding
				max_width = 420
				autoresize = yes
				text = "{key}_tooltip"
			}}
		}}

		situation_card_expandable = {{
			blockoverride "header_button_onclick" {{
				onclick = "[LateralView.Vars.Toggle( 'requirements_toggled' )]"
			}}
			blockoverride "header_text" {{ text = "END_REQUIREMENTS" }}
			blockoverride "header_icon" {{ texture = "gfx/interface/icons/disasters/end_requirements_green.dds" }}
			blockoverride "bottom_content" {{
				TooltipRequirementsList = {{
					textcontext = "[SituationView.GetActiveSituation.GetSituation.GetEndConditions]"
				}}
			}}
			blockoverride "bottom_content_onclick" {{
				visible = "[LateralView.Vars.Exists( 'requirements_toggled' )]"
			}}
			blockoverride "icon_replace_visible_yes" {{
				visible = "[LateralView.Vars.Exists( 'requirements_toggled' )]"
			}}
			blockoverride "icon_replace_visible_not" {{
				visible = "[Not(LateralView.Vars.Exists( 'requirements_toggled' ))]"
			}}
		}}

		situation_card_expandable = {{
			blockoverride "header_text" {{ text = "{key}_tooltip" }}
			blockoverride "header_icon" {{ texture = "[SituationView.GetActiveSituation.GetIcon]" }}
			blockoverride "bottom_content" {{
				text_multi = {{
					margin = {{ 15 0 }}
					layoutpolicy_horizontal = expanding
					max_width = 420
					autoresize = yes
					text = "{key}_tooltip"
				}}
			}}
		}}

		situation_card_expandable = {{
			blockoverride "header_text" {{ text = "{key}_progress" }}
			blockoverride "header_icon" {{ texture = "gfx/interface/icons/situations/tension.dds" }}
			blockoverride "bottom_content" {{
				text_single = {{
					layoutpolicy_horizontal = expanding
					align = center
					raw_text = "[FixedPointToInt(SituationView.GetActiveSituation.GetSituation.MakeScope.GetVariable('{progress}').GetValue)] / 100"
				}}
			}}
		}}
	}}

	blockoverride "situation_variable_progress_bar_visible" {{ visible = yes }}
	blockoverride "disaster_progressbar" {{
		hbox = {{
			using = situation_disaster_progressbar_with_thresholds
			blockoverride "progressbar_with_thresholds_size" {{ size = {{ 340 10 }} }}
			blockoverride "progress_bar_value_low" {{
				value = "[Min_float(FixedPointToFloat(SituationView.GetActiveSituation.GetSituation.MakeScope.GetVariable('{progress}').GetValue), '(float)100')]"
			}}
			blockoverride "progress_bar_value_mid" {{
				value = "[Max_float(Subtract_float(Min_float(FixedPointToFloat(SituationView.GetActiveSituation.GetSituation.MakeScope.GetVariable('{progress}').GetValue), '(float)66'), '(float)33'), '(float)0')]"
			}}
			blockoverride "progress_bar_value_high" {{
				value = "[Max_float(Subtract_float(FixedPointToFloat(SituationView.GetActiveSituation.GetSituation.MakeScope.GetVariable('{progress}').GetValue), '(float)66'), '(float)0')]"
			}}
		}}
	}}
}}
'''


def outputs() -> dict[Path, str]:
    result = {PANEL_DIR / f"{key}.gui": panel_script(key) for key in situation_keys()}
    result[COMMON_OUTPUT] = common_panel_script()
    return result


def write() -> None:
    for path, content in outputs().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def check() -> None:
    expected = outputs()
    missing = [str(path.relative_to(ROOT)) for path, content in expected.items() if not path.is_file() or path.read_text(encoding="utf-8-sig") != content]
    unexpected = sorted(path.name for path in PANEL_DIR.glob("antq_*.gui") if path not in expected)
    if missing or unexpected:
        raise ValueError(f"situation panel drift: missing_or_changed={missing}, unexpected={unexpected}")
    for path, content in expected.items():
        if path == COMMON_OUTPUT:
            for token in ("SituationView.GetActiveSituation.GetName]", "TooltipRequirementsList"):
                if token not in content:
                    raise ValueError(f"{path.name} lacks generic situation-panel token {token}")
            continue
        for token in ("situation_panel_main_content", "TooltipRequirementsList", "situation_disaster_progressbar_with_thresholds"):
            if token not in content:
                raise ValueError(f"{path.name} lacks standard panel token {token}")
    print(f"m10_situation_panels: PASS ({len(expected)} readable situation panels)")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        write()
        print(f"m10_situation_panels: wrote {len(outputs())} panels")
    if args.check or not args.write:
        check()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
