#!/usr/bin/env python3
"""Give every ancient situation a usable, AI-visible response surface.

EU5 situation panels populate their action area from generic actions with a
``looking_for_a = situation`` selector.  The M10 lifecycle generators created
the currents but had no such actions, leaving a valid yet empty panel.  This
renderer derives the exact live situation inventory rather than duplicating it
in another historical ledger.
"""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path

from dates import M2_MIRROR_LANGUAGES


ROOT = Path(__file__).resolve().parents[1]
SITUATION_FILES = tuple(sorted((ROOT / "in_game/common/situations").glob("antq_m10_*.txt"))) + (
    ROOT / "in_game/common/situations/antq_s2_germania_dynamics.txt",
)
ACTION_OUTPUT = ROOT / "in_game/common/generic_actions/antq_m10_situation_actions.txt"
AI_LIST_OUTPUT = ROOT / "in_game/common/generic_action_ai_lists/antq_m10_situation_actions_list.txt"
LOC_ROOT = ROOT / "main_menu/localization"
LANGUAGES = ("english", *M2_MIRROR_LANGUAGES)
EXPECTED_SITUATIONS = 43


@dataclass(frozen=True)
class Situation:
    key: str
    anchor: str

    @property
    def progress(self) -> str:
        return f"{self.key}_resolution_progress"


def block_at(text: str, open_brace: int) -> str:
    depth = 0
    for index, char in enumerate(text[open_brace:], open_brace):
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[open_brace:index + 1]
    raise ValueError("unterminated Paradox block")


def load_situations() -> tuple[Situation, ...]:
    records: list[Situation] = []
    for path in SITUATION_FILES:
        if not path.is_file():
            raise ValueError(f"missing situation source: {path.relative_to(ROOT)}")
        text = path.read_text(encoding="utf-8-sig")
        for match in re.finditer(r"(?m)^(antq_(?:m10|s2)_[a-z0-9_]+)\s*=\s*\{", text):
            block = block_at(text, match.end() - 1)
            content = re.search(r"\bcontent_trigger\s*=\s*\{(.*?)\}", block, re.S)
            if content is None:
                raise ValueError(f"{match.group(1)} has no content trigger")
            anchor = re.search(r"\btag\s*=\s*([A-Z0-9]{3})\b", content.group(1))
            if anchor is None:
                raise ValueError(f"{match.group(1)} has no exact anchor tag")
            records.append(Situation(match.group(1), anchor.group(1)))
    records.sort(key=lambda item: item.key)
    if len(records) != EXPECTED_SITUATIONS:
        raise ValueError(f"ancient situation inventory is {len(records)}, expected {EXPECTED_SITUATIONS}")
    if len({record.key for record in records}) != len(records):
        raise ValueError("ancient situation inventory has duplicate keys")
    return tuple(records)


def action_key(record: Situation, response: str) -> str:
    return f"{record.key}_{response}"


def action_block(record: Situation, response: str) -> str:
    key = action_key(record, response)
    cost, progress, stability = (18, 18, "stability_weak_bonus") if response == "relief" else (28, 28, "stability_weak_penalty")
    title = "Fund Relief and Negotiation" if response == "relief" else "Mobilize a Coordinated Response"
    return f'''# Generated ancient-current response. The selector keeps this action inside its own situation panel.
{key} = {{
\ttype = situation
\tshow_message = no
\tai_tick = monthly
\tai_tick_frequency = 6
\tautomation_tick = monthly
\tautomation_tick_frequency = 3
\tpotential = {{
\t\tscope:actor = {{ tag = {record.anchor} }}
\t}}
\tallow = {{
\t\tscope:actor = {{ gold >= {cost} }}
\t\tscope:recipient = {{ situation_is_active = yes }}
\t}}
\tcooldown = {{ type = {key} years = 2 }}
\tselect_trigger = {{
\t\tlooking_for_a = situation
\t\tinteraction_source_list = {{
\t\t\tsituation:{record.key} = {{ add_to_list = source }}
\t\t}}
\t\ttarget_flag = recipient
\t\tname = "choose_situation"
\t\tcolumn = {{ data = name }}
\t\tvisible = {{
\t\t\tsituation:{record.key} = this
\t\t\tsituation_is_active = yes
\t\t\tscope:actor = {{ tag = {record.anchor} }}
\t\t}}
\t}}
\teffect = {{
\t\tscope:actor = {{
\t\t\tadd_gold = -{cost}
\t\t\tadd_stability = {stability}
\t\t}}
\t\tscope:recipient = {{ change_variable = {{ name = {record.progress} add = {progress} }} }}
\t}}
\tai_will_do = {{
\t\tadd = 10
\t\tif = {{ limit = {{ scope:actor = {{ gold < {cost * 2} }} }} add = -18 }}
\t\tif = {{ limit = {{ scope:actor = {{ stability < 0 }} }} add = 10 }}
\t}}
}}'''


def action_script(records: tuple[Situation, ...]) -> str:
    chunks = ["# Generated by tools/m10_situation_actions.py --write.", "# Two material, AI-usable responses for each active ancient situation.", ""]
    for record in records:
        chunks.extend((action_block(record, "relief"), "", action_block(record, "mobilize"), ""))
    return "\n".join(chunks)


def ai_list_script(records: tuple[Situation, ...]) -> str:
    actions = "\n".join(f"\t\t{action_key(record, response)}" for record in records for response in ("relief", "mobilize"))
    return (
        "# Generated by tools/m10_situation_actions.py --write.\n"
        "antq_m10_situation_actions_list = {\n"
        "\tpotential = { always = yes }\n"
        "\tactions = {\n"
        f"{actions}\n"
        "\t}\n"
        "}\n"
    )


def localization(records: tuple[Situation, ...], language: str) -> str:
    lines = [f"l_{language}:"]
    for record in records:
        # r5_visible_unions owns the shared situation title/progress/legend/
        # faction/tooltip localization.  This file deliberately owns only the
        # newly introduced generic-action surfaces.
        lines.extend((
            f' {action_key(record, "relief")}: "Fund Relief and Negotiation"',
            f' {action_key(record, "relief")}_desc: "Spend 18 [gold|e] on relief, envoys, and local accommodation to add #G 18#! resolution progress and restore modest stability."',
            f' {action_key(record, "relief")}_tt: "Spend 18 [gold|e] to add #G 18#! resolution progress."',
            f' {action_key(record, "mobilize")}: "Mobilize a Coordinated Response"',
            f' {action_key(record, "mobilize")}_desc: "Spend 28 [gold|e] to concentrate logistics and authority, adding #G 28#! resolution progress at a small stability cost."',
            f' {action_key(record, "mobilize")}_tt: "Spend 28 [gold|e] to add #G 28#! resolution progress and lose a little stability."',
        ))
    return "\n".join(lines) + "\n"


def outputs(records: tuple[Situation, ...]) -> dict[Path, str]:
    rendered = {ACTION_OUTPUT: action_script(records), AI_LIST_OUTPUT: ai_list_script(records)}
    for language in LANGUAGES:
        rendered[LOC_ROOT / language / f"antq_m10_situation_actions_l_{language}.yml"] = localization(records, language)
    return rendered


def validate(records: tuple[Situation, ...]) -> list[str]:
    failures: list[str] = []
    rendered = outputs(records)
    for path, expected in rendered.items():
        if not path.is_file():
            failures.append(f"missing generated output: {path.relative_to(ROOT)}")
        elif path.read_text(encoding="utf-8-sig") != expected:
            failures.append(f"stale generated output: {path.relative_to(ROOT)}")
    action_text = rendered[ACTION_OUTPUT]
    if "stability_tiny_penalty" in action_text or "stability_weak_penalty" not in action_text:
        failures.append("situation mobilization must use the installed stability_weak_penalty value")
    for record in records:
        for response in ("relief", "mobilize"):
            key = action_key(record, response)
            for token in (f"{key} = {{", f"situation:{record.key} = this", f"name = {record.progress}", "type = situation", "ai_will_do = {"):
                if token not in action_text:
                    failures.append(f"{key} lacks panel/action contract: {token}")
    return failures


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write == args.check:
        parser.error("provide exactly one of --write or --check")
    try:
        records = load_situations()
        if args.write:
            for path, content in outputs(records).items():
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8-sig", newline="\n")
        failures = validate(records)
    except (OSError, ValueError) as exc:
        failures = [str(exc)]
    if failures:
        print("m10_situation_actions: FAIL")
        print("\n".join(f"  - {failure}" for failure in failures))
        return 1
    print(f"m10_situation_actions: PASS ({len(records)} situations; {len(records) * 2} response actions)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
