#!/usr/bin/env python3
"""Generate and check the complete direct ANTIQVITAS UI-asset ledger.

Specialist validators own the format and resolver contracts.  This compact
cross-surface ledger makes their player-facing inventory reviewable in one
place: every listed item has a unique local source, reviewed PNG master, and
game-facing DDS texture.
"""

from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from pathlib import Path

from PIL import Image

import m11_advance_icons
import m11_common_icons
import m11_privilege_icons
import m5_regional_buildings
import m5_roman_buildings


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs/m11/UI_ASSET_LEDGER.md"
GOODS = ROOT / "docs/m5/custom_goods.csv"
BUILDING_MASTERS = ROOT / "assets_queue/generated"


@dataclass(frozen=True)
class Asset:
    surface: str
    key: str
    source: Path | None
    master: Path | None
    texture: Path


def local(path: str | Path) -> Path:
    value = Path(path)
    return value if value.is_absolute() else ROOT / value


def building_master(key: str) -> Path:
    """Return the retained reviewed master for one direct building icon.

    Earlier M5 batches retained their finished 128px master with the explicit
    ``_128`` suffix; the later Roman civic and regional batches use the key
    itself.  Both are source masters, never a shared fallback texture.
    """
    for suffix in ("_128.png", ".png"):
        candidate = BUILDING_MASTERS / f"{key}{suffix}"
        if candidate.is_file():
            return candidate
    raise ValueError(f"missing retained 128px building master for {key}")


def assets() -> list[Asset]:
    result: list[Asset] = []
    for item in m11_advance_icons.direct_assets():
        result.append(Asset("Advance", item.icon, local(item.source), local(item.master), local(item.texture)))
    for item in m11_privilege_icons.direct_icons():
        result.append(Asset("Privilege", item.key, item.source, item.master,
                            m11_privilege_icons.ICON_DIR / f"{item.key}.dds"))
    for item in m11_common_icons.direct_religion_icons():
        result.append(Asset("Religion", item.key, local(item.source), local(item.master),
                            m11_common_icons.RELIGION_TEXTURES / f"{item.key}.dds"))
    for item in m11_common_icons.INSTITUTION_ICONS:
        result.append(Asset("Institution", item.key, local(item.source), local(item.master),
                            m11_common_icons.INSTITUTION_TEXTURES / f"{item.key}.dds"))
    for item in m5_roman_buildings.load():
        key = item["key"]
        result.append(Asset("Named Roman building", key, None, building_master(key),
                            m5_roman_buildings.ICON_DIR / f"{key}.dds"))
    families, _seeds = m5_regional_buildings.load()
    for item in families:
        key = item["key"]
        result.append(Asset("Regional building family", key, None, building_master(key),
                            m5_regional_buildings.ICON_DIR / f"{key}.dds"))
    with GOODS.open(encoding="utf-8-sig", newline="") as handle:
        for row in csv.DictReader(handle):
            key = (row.get("key") or "").strip()
            if not key:
                raise ValueError("custom goods ledger contains a blank key")
            result.append(Asset("Custom trade good", key, None,
                                ROOT / "assets_queue/generated" / f"{key}.png",
                                ROOT / "main_menu/gfx/interface/icons/trade_goods" / f"icon_goods_{key}.dds"))
    return result


def relative(path: Path | None) -> str:
    if path is None:
        return "—"
    return path.relative_to(ROOT).as_posix()


def render(items: list[Asset]) -> str:
    groups = sorted({item.surface for item in items})
    lines = [
        "# Direct ANTIQVITAS UI asset ledger",
        "",
        "Generated by `tools/m11_ui_asset_ledger.py --write`. This is the cross-surface inventory of player-facing direct art. The specialist validators in `make validate` own exact dimensions, DDS format, key resolver, and source-chain checks; this ledger makes the complete inventory reviewable as one set. A dash records an older direct-texture contract whose source master predates per-item master retention; it is still checked by its specialist texture validator.",
        "",
        f"**Total direct asset chains: {len(items)}.**",
        "",
        "| Surface | Direct chains |",
        "|---|---:|",
    ]
    lines.extend(f"| {group} | {sum(item.surface == group for item in items)} |" for group in groups)
    for group in groups:
        lines.extend(("", f"## {group}", "", "| Key | Source | Reviewed master | Game texture |", "|---|---|---|---|"))
        for item in sorted((entry for entry in items if entry.surface == group), key=lambda entry: entry.key):
            lines.append(
                f"| `{item.key}` | `{relative(item.source)}` | `{relative(item.master)}` | `{relative(item.texture)}` |"
            )
    return "\n".join(lines) + "\n"


def validate(items: list[Asset]) -> None:
    seen: set[tuple[str, str]] = set()
    failures: list[str] = []
    for item in items:
        identity = (item.surface, item.key)
        if identity in seen:
            failures.append(f"duplicate ledger item {item.surface}: {item.key}")
        seen.add(identity)
        for path, label in ((item.source, "source"), (item.master, "master"), (item.texture, "texture")):
            if path is None:
                continue
            if not path.is_file():
                failures.append(f"missing {label} for {item.surface} {item.key}: {relative(path)}")
        if item.surface in {"Named Roman building", "Regional building family"} and item.master:
            try:
                with Image.open(item.master) as image:
                    if image.size != (128, 128):
                        failures.append(
                            f"building master for {item.key} must be 128x128: "
                            f"{relative(item.master)} is {image.size[0]}x{image.size[1]}"
                        )
            except OSError as exc:
                failures.append(f"unreadable building master for {item.key}: {relative(item.master)} ({exc})")
    if failures:
        raise ValueError("\n".join(failures))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write == args.check:
        parser.error("provide exactly one of --write or --check")
    try:
        items = assets()
        validate(items)
        content = render(items)
        if args.write:
            OUTPUT.parent.mkdir(parents=True, exist_ok=True)
            OUTPUT.write_text(content, encoding="utf-8", newline="\n")
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != content:
            raise ValueError(f"stale or missing generated ledger: {OUTPUT.relative_to(ROOT)}")
    except (OSError, ValueError, csv.Error) as exc:
        print(f"m11_ui_asset_ledger: FAIL\n  - {exc}")
        return 1
    print(f"m11_ui_asset_ledger: PASS ({len(items)} direct UI asset chains)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
