#!/usr/bin/env python3
"""Generate and audit the sourced ANTIQVITAS religious-doctrine surface."""

from __future__ import annotations

import argparse
import csv
import hashlib
import io
import json
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

from PIL import Image, ImageDraw


ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "config/local_paths.json"
LEDGER = ROOT / "docs/m12/religious_doctrines.csv"
SCRIPT = ROOT / "in_game/common/religious_aspects/00_antiquitas_m12_roman.txt"
RELIGIONS = ROOT / "in_game/common/religions/antq_m4_religions.txt"
MASTER_DIR = ROOT / "assets_queue/religious_doctrines/masters"
ICON_DIR = ROOT / "main_menu/gfx/interface/icons/religious_aspects"
CONTACT_SHEET = ROOT / "docs/m12/religious_doctrines_contact_sheet.png"
DDS = ROOT / "tools/dds.py"
LANGUAGES = (
    "english",
    "french",
    "german",
    "spanish",
    "polish",
    "russian",
    "braz_por",
    "simp_chinese",
    "japanese",
    "korean",
    "turkish",
)
FIELDS = (
    "key",
    "name",
    "religion",
    "modifier_1",
    "value_1",
    "modifier_2",
    "value_2",
    "source",
    "note",
    "art_mode",
    "art_source",
    "art_sha256",
)


@dataclass(frozen=True)
class Doctrine:
    key: str
    name: str
    religion: str
    modifiers: tuple[tuple[str, str], ...]
    source: str
    note: str
    art_mode: str
    art_source: str
    art_sha256: str

    @property
    def master(self) -> Path:
        return MASTER_DIR / f"{self.key}_128.png"

    @property
    def texture(self) -> Path:
        return ICON_DIR / f"{self.key}.dds"


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def game_root() -> Path:
    data = json.loads(CONFIG.read_text(encoding="utf-8-sig"))
    return Path(str(data["game_dir"])) / "game"


def rows() -> tuple[Doctrine, ...]:
    with LEDGER.open(encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        if tuple(reader.fieldnames or ()) != FIELDS:
            raise ValueError(
                f"{LEDGER.relative_to(ROOT)} must use header {','.join(FIELDS)}"
            )
        raw = list(reader)
    doctrines: list[Doctrine] = []
    seen: set[str] = set()
    for number, row in enumerate(raw, start=2):
        key = (row["key"] or "").strip()
        modifiers = tuple(
            (
                (row[f"modifier_{index}"] or "").strip(),
                (row[f"value_{index}"] or "").strip(),
            )
            for index in (1, 2)
        )
        if (
            not key.startswith("antq_roman_")
            or key in seen
            or (row["religion"] or "").strip() != "antq_religio_romana"
            or any(not field or not value for field, value in modifiers)
            or (row["art_mode"] or "").strip() not in {"installed", "generated"}
            or len((row["art_sha256"] or "").strip()) != 64
        ):
            raise ValueError(f"{LEDGER.relative_to(ROOT)}:{number}: invalid doctrine row")
        doctrines.append(
            Doctrine(
                key=key,
                name=(row["name"] or "").strip(),
                religion=(row["religion"] or "").strip(),
                modifiers=modifiers,
                source=(row["source"] or "").strip(),
                note=(row["note"] or "").strip(),
                art_mode=(row["art_mode"] or "").strip(),
                art_source=(row["art_source"] or "").strip(),
                art_sha256=(row["art_sha256"] or "").strip(),
            )
        )
        seen.add(key)
    if len(doctrines) != 8:
        raise ValueError("the first Roman doctrine tranche must contain exactly eight choices")
    if any(not row.name or not row.source or not row.note for row in doctrines):
        raise ValueError("every doctrine needs a name, source, and historical note")
    return tuple(doctrines)


def source_path(row: Doctrine) -> Path:
    if row.art_mode == "installed":
        return (
            game_root()
            / "main_menu/gfx/interface/icons/religious_aspects"
            / row.art_source
        )
    return ROOT / row.art_source


def verify_source(row: Doctrine) -> Path:
    source = source_path(row)
    if not source.is_file():
        raise ValueError(f"missing doctrine art source: {source}")
    actual = sha256(source.read_bytes())
    if actual != row.art_sha256:
        raise ValueError(
            f"doctrine art source drift for {row.key}: "
            f"expected {row.art_sha256}, found {actual}"
        )
    return source


def render_script(doctrines: tuple[Doctrine, ...]) -> bytes:
    lines = [
        "# Generated by tools/m12_religious_doctrines.py --write.",
        "# Sourced AD 1 Roman public and household religious practices.",
    ]
    for row in doctrines:
        lines.extend(
            (
                "",
                f"{row.key} = {{ # {row.source}; {row.note}",
                f"\ticon = {row.key}",
                f"\treligion = {row.religion}",
                "",
                "\tmodifier = {",
                *(f"\t\t{field} = {value}" for field, value in row.modifiers),
                "\t}",
                "",
                "\topinions = {",
                f"\t\t{row.key} = 10",
                "\t}",
                "}",
            )
        )
    return ("\ufeff" + "\n".join(lines) + "\n").encode("utf-8")


def render_localization(doctrines: tuple[Doctrine, ...], language: str) -> bytes:
    lines = [f"l_{language}:"]
    for row in doctrines:
        name = row.name.replace('"', '\\"')
        note = row.note.replace('"', '\\"')
        lines.append(f' {row.key}: "{name}"')
        lines.append(f' {row.key}_desc: "{note}"')
    return ("\ufeff" + "\n".join(lines) + "\n").encode("utf-8")


def localization_path(language: str) -> Path:
    return (
        ROOT
        / "main_menu/localization"
        / language
        / f"antq_m12_religious_doctrines_l_{language}.yml"
    )


def render_master(source: Path) -> Image.Image:
    with Image.open(source) as image:
        rgba = image.convert("RGBA")
    rgba.thumbnail((124, 124), Image.Resampling.LANCZOS)
    master = Image.new("RGBA", (128, 128), (0, 0, 0, 0))
    master.alpha_composite(
        rgba,
        ((128 - rgba.width) // 2, (128 - rgba.height) // 2),
    )
    return master


def render_contact_sheet(doctrines: tuple[Doctrine, ...]) -> Image.Image:
    sheet = Image.new("RGB", (720, 400), (13, 24, 42))
    draw = ImageDraw.Draw(sheet)
    for index, row in enumerate(doctrines):
        x = 20 + (index % 4) * 175
        y = 20 + (index // 4) * 190
        with Image.open(row.master) as image:
            icon = image.convert("RGBA")
        sheet.paste(icon, (x + 23, y), icon)
        label = row.name
        if len(label) > 23:
            label = label[:22] + "…"
        draw.text((x, y + 138), label, fill=(235, 226, 197))
        draw.text((x, y + 156), row.key.removeprefix("antq_roman_"), fill=(145, 166, 194))
    return sheet


def image_bytes(image: Image.Image, mode: str = "RGBA") -> bytes:
    output = io.BytesIO()
    image.convert(mode).save(output, format="PNG", optimize=False)
    return output.getvalue()


def write() -> None:
    doctrines = rows()
    SCRIPT.parent.mkdir(parents=True, exist_ok=True)
    SCRIPT.write_bytes(render_script(doctrines))
    for language in LANGUAGES:
        target = localization_path(language)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(render_localization(doctrines, language))

    MASTER_DIR.mkdir(parents=True, exist_ok=True)
    ICON_DIR.mkdir(parents=True, exist_ok=True)
    for row in doctrines:
        source = verify_source(row)
        row.master.write_bytes(image_bytes(render_master(source)))
        if row.art_mode == "installed":
            shutil.copyfile(source, row.texture)
        else:
            subprocess.run(
                [
                    sys.executable,
                    str(DDS),
                    "convert",
                    str(row.master),
                    str(row.texture),
                    "--compression",
                    "dxt5",
                ],
                check=True,
            )
    CONTACT_SHEET.write_bytes(image_bytes(render_contact_sheet(doctrines), "RGB"))
    print(
        "m12_religious_doctrines: wrote 8 Roman choices, "
        "11 localization mirrors, and 8 direct icons"
    )


def dds_details(path: Path) -> dict[str, str]:
    result = subprocess.run(
        [sys.executable, str(DDS), "identify", str(path)],
        check=True,
        capture_output=True,
        text=True,
    )
    return json.loads(result.stdout)


def check() -> bool:
    try:
        doctrines = rows()
        errors: list[str] = []
        if not SCRIPT.is_file() or SCRIPT.read_bytes() != render_script(doctrines):
            errors.append(f"stale or missing {SCRIPT.relative_to(ROOT)}")
        for language in LANGUAGES:
            target = localization_path(language)
            expected = render_localization(doctrines, language)
            if not target.is_file() or target.read_bytes() != expected:
                errors.append(f"stale or missing {target.relative_to(ROOT)}")
        religion_text = RELIGIONS.read_text(encoding="utf-8-sig")
        roman_start = religion_text.index("antq_religio_romana = {")
        roman_end = religion_text.index("\n}", roman_start)
        roman_block = religion_text[roman_start:roman_end]
        if "religious_aspects = 2" not in roman_block:
            errors.append("Religio Romana does not expose two doctrine slots")

        hashes: set[str] = set()
        for row in doctrines:
            verify_source(row)
            if not row.master.is_file() or not row.texture.is_file():
                errors.append(f"missing direct art for {row.key}")
                continue
            with Image.open(row.master) as master:
                rgba = master.convert("RGBA")
                if rgba.size != (128, 128):
                    errors.append(f"{row.key} master is not 128x128")
                if any(rgba.getpixel(point)[3] != 0 for point in ((0, 0), (127, 0), (0, 127), (127, 127))):
                    errors.append(f"{row.key} master lacks transparent corners")
            details = dds_details(row.texture)
            if (
                details.get("format") != "DDS"
                or details.get("width") != "128"
                or details.get("height") != "128"
                or details.get("channels") != "srgba 4.0"
            ):
                errors.append(f"{row.key} DDS contract is invalid: {details}")
            texture_hash = sha256(row.texture.read_bytes())
            if texture_hash in hashes:
                errors.append(f"{row.key} duplicates another doctrine texture")
            hashes.add(texture_hash)
        if not CONTACT_SHEET.is_file():
            errors.append(f"missing {CONTACT_SHEET.relative_to(ROOT)}")
        else:
            with Image.open(CONTACT_SHEET) as sheet:
                if sheet.size != (720, 400):
                    errors.append("religious doctrine contact sheet has wrong dimensions")
        if errors:
            print("m12_religious_doctrines: FAIL")
            for error in errors:
                print(f"  - {error}")
            return False
    except (
        OSError,
        ValueError,
        csv.Error,
        json.JSONDecodeError,
        subprocess.CalledProcessError,
    ) as exc:
        print(f"m12_religious_doctrines: FAIL\n  - {exc}")
        return False
    print(
        "m12_religious_doctrines: PASS "
        "(8 Roman choices; 2 slots; 8 direct distinct icons; 11 clients)"
    )
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        try:
            write()
        except (
            OSError,
            ValueError,
            csv.Error,
            json.JSONDecodeError,
            subprocess.CalledProcessError,
        ) as exc:
            print(f"m12_religious_doctrines: FAIL\n  - {exc}")
            return 1
        return 0 if check() else 1
    return 0 if check() else 1


if __name__ == "__main__":
    raise SystemExit(main())
