#!/usr/bin/env python3
"""Maintain the M12 engine-required culture-presence compatibility ledger."""

from __future__ import annotations

import argparse
import csv
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs/m12/culture_presence.csv"
M4_SYMBOLS = ROOT / "docs/m4/definition_symbols.json"
VANILLA_CULTURES = ROOT / "docs/vanilla_symbols/culture.json"
START_POPS = ROOT / "main_menu/setup/start/06_pops.txt"
WARNING = re.compile(r"Culture has no pops in the setup:\s*([A-Za-z0-9_]+)")
CULTURE_TOKEN = re.compile(r"\bculture\s*=\s*([A-Za-z0-9_]+)")


def m4_cultures() -> set[str]:
    return set(json.loads(M4_SYMBOLS.read_text(encoding="utf-8"))["cultures"])


def known_cultures() -> set[str]:
    vanilla = set(json.loads(VANILLA_CULTURES.read_text(encoding="utf-8-sig")))
    return vanilla | m4_cultures()


def required_custom_presences() -> set[str]:
    """Return M4 symbols with no historical AD 1 population record.

    The compatibility manager owns these sub-thousand engine presences. Derive
    them from the canonical definition index and historical pop mirror so a new
    definition cannot silently reintroduce the initializer warning.
    """
    historical = set(CULTURE_TOKEN.findall(START_POPS.read_text(encoding="utf-8")))
    return m4_cultures() - historical


def existing_rows() -> list[str]:
    """Read the ledger without requiring its derived custom slice to be current."""
    with OUTPUT.open(encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(line for line in handle if not line.startswith("#"))
        if tuple(reader.fieldnames or ()) != ("culture",):
            raise ValueError(f"{OUTPUT.relative_to(ROOT)} must contain only a culture column")
        rows = [row["culture"].strip() for row in reader]
    if not rows or any(not row for row in rows) or rows != sorted(set(rows)):
        raise ValueError(f"{OUTPUT.relative_to(ROOT)} must be non-empty, sorted, and unique")
    unknown = sorted(set(rows) - known_cultures())
    if unknown:
        raise ValueError(f"{OUTPUT.relative_to(ROOT)} has unknown culture(s): {unknown[:8]}")
    return rows


def read() -> list[str]:
    rows = existing_rows()
    custom = set(rows) & m4_cultures()
    required = required_custom_presences()
    if custom != required:
        missing = sorted(required - custom)
        stale = sorted(custom - required)
        raise ValueError(
            f"{OUTPUT.relative_to(ROOT)} custom-presence drift; "
            f"missing={missing[:8]}, stale={stale[:8]}"
        )
    return rows


def write() -> int:
    config = json.loads((ROOT / "config/local_paths.json").read_text(encoding="utf-8-sig"))
    log = Path(str(config["user_dir"])) / "logs/error.log"
    existing = set(existing_rows()) if OUTPUT.is_file() else set()
    live = (
        set(WARNING.findall(log.read_text(encoding="utf-8-sig", errors="replace")))
        if log.is_file()
        else set()
    )
    custom = m4_cultures()
    cultures = (
        (existing - custom)
        | live
        | required_custom_presences()
    )
    unknown = sorted(cultures - known_cultures())
    if unknown:
        raise ValueError(f"live initializer reported unknown culture(s): {unknown[:8]}")
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(
        "# Generated by tools/m12_culture_presence.py --write from live diagnostics and canonical M4/start ledgers.\n"
        "# EU5 1.3.11 AD 1 initializer compatibility presences, refreshed 2026-07-24.\n"
        "culture\n" + "".join(f"{culture}\n" for culture in sorted(cultures)),
        encoding="utf-8-sig",
        newline="\n",
    )
    print(f"m12_culture_presence: wrote {len(cultures)} cultures")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        if args.write:
            return write()
        print(f"m12_culture_presence: PASS ({len(read())} initializer-required cultures)")
        return 0
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"m12_culture_presence: FAIL\n  - {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
