#!/usr/bin/env python3
"""Render the narrowly patched vanilla marriage-law compatibility overlay.

EU5 gives a number of low-technology country templates the ``polygyny``
policy before bookmark initialization.  The native rule makes it available to
pagan, Hindu, and Indian-group countries.  ANTIQVITAS uses sourced ancient
faiths in native Buddhist, Dharmic, Iranian, and Manichaean mechanics groups,
so the engine otherwise removes the policy even where the template selected
it.  This overlay only extends *availability*; it never assigns a policy.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "config/local_paths.json"
OUTPUT = ROOT / "in_game/common/laws/01_common.txt"
PATCH_FROM = """\t\t\t\tis_country_religion_pagan = yes
\t\t\t\treligion = religion:hindu
\t\t\t\tculture = { has_culture_group = culture_group:indian_group }
"""
PATCH_TO = """\t\t\t\tis_country_religion_pagan = yes
\t\t\t\treligion = religion:hindu
\t\t\t\tculture = { has_culture_group = culture_group:indian_group }
\t\t\t\treligion.group = religion_group:buddhist
\t\t\t\treligion.group = religion_group:dharmic
\t\t\t\treligion.group = religion_group:zoroastrian_group
\t\t\t\treligion.group = religion_group:manichaean_group
"""


def source_path() -> Path:
    config = json.loads(CONFIG.read_text(encoding="utf-8-sig"))
    return Path(config["game_dir"]) / "game/in_game/common/laws/01_common.txt"


def render() -> bytes:
    source = source_path().read_bytes()
    text = source.decode("utf-8-sig")
    if text.count(PATCH_FROM) != 1:
        raise ValueError("installed 01_common.txt no longer has the expected polygyny availability block")
    patched = text.replace(PATCH_FROM, PATCH_TO)
    # The installed script has a handful of trailing tabs/spaces.  They are
    # semantically inert, but normalized output keeps the generated overlay
    # clean under the repository's whitespace gate.
    patched = "\n".join(line.rstrip() for line in patched.splitlines()) + "\n"
    digest = hashlib.sha256(source).hexdigest()
    header = (
        "# Generated by tools/m12_marriage_policy_guard.py --write.\n"
        f"# Installed 01_common.txt SHA256: {digest}\n"
        "# Extends availability only for native AD 1 Buddhist/Dharmic/Iranian mechanics groups.\n"
    )
    return (header + patched).encode("utf-8-sig")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write == args.check:
        parser.error("provide exactly one of --write or --check")
    try:
        expected = render()
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"m12_marriage_policy_guard: FAIL\n  - {exc}")
        return 1
    if args.write:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_bytes(expected)
        print(f"m12_marriage_policy_guard: wrote {OUTPUT.relative_to(ROOT)}")
        return 0
    if not OUTPUT.is_file() or OUTPUT.read_bytes() != expected:
        print(f"m12_marriage_policy_guard: FAIL\n  - stale generated output {OUTPUT.relative_to(ROOT)}")
        return 1
    print("m12_marriage_policy_guard: PASS (four native AD 1 compatibility groups)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
