#!/usr/bin/env python3
"""Quarantine inherited country definitions while retaining engine sentinels."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "config/local_paths.json"
RELATIVE_ROOT = Path("in_game/setup/countries")
ACTIVE = ROOT / RELATIVE_ROOT / "antq_00_world.txt"
MANIFEST = ROOT / "docs/m12/country_registry_manifest.json"
RESERVED = frozenset({"DUMMY", "PIR", "MER"})
HEADER = re.compile(r"(?m)^(?P<key>[A-Z0-9]{3,5})\s*=\s*\{\s*(?:#.*)?$")


def game_root() -> Path:
    data = json.loads(CONFIG.read_text(encoding="utf-8-sig"))
    root = Path(data["game_dir"]) / "game"
    if not root.is_dir():
        raise ValueError(f"installed game root is missing: {root}")
    return root


def source_files() -> list[Path]:
    root = game_root() / RELATIVE_ROOT
    files = sorted(root.glob("*.txt"), key=lambda path: path.name.lower())
    if len(files) != 45:
        raise ValueError(f"installed country file inventory drift: {len(files)}")
    return files


def brace_delta(text: str) -> int:
    quoted = False
    escaped = False
    delta = 0
    for char in text:
        if escaped:
            escaped = False
        elif quoted and char == "\\":
            escaped = True
        elif char == '"':
            quoted = not quoted
        elif not quoted and char == "#":
            break
        elif not quoted and char == "{":
            delta += 1
        elif not quoted and char == "}":
            delta -= 1
    return delta


def blocks(text: str) -> dict[str, str]:
    lines = text.splitlines(keepends=True)
    result: dict[str, str] = {}
    index = 0
    while index < len(lines):
        match = HEADER.match(lines[index])
        if match is None:
            index += 1
            continue
        start = index
        depth = 0
        while index < len(lines):
            depth += brace_delta(lines[index])
            index += 1
            if depth == 0:
                break
        if depth != 0:
            raise ValueError(f"country definition {match.group('key')} is unbalanced")
        key = match.group("key")
        if key in result:
            raise ValueError(f"duplicate country definition {key}")
        result[key] = "".join(lines[start:index]).rstrip() + "\n"
    return result


def render(path: Path) -> bytes:
    raw = path.read_bytes()
    source = blocks(raw.decode("utf-8-sig"))
    retained = [source[key] for key in sorted(RESERVED & source.keys())]
    text = (
        "# Generated by tools/m12_country_registry.py --write.\n"
        "# Inherited 1337 country registry quarantined; engine sentinels retained.\n\n"
        + "\n".join(retained)
    )
    return (b"\xef\xbb\xbf" if raw.startswith(b"\xef\xbb\xbf") else b"") + text.encode("utf-8")


def expected_manifest() -> dict[str, object]:
    records = []
    total = 0
    retained: set[str] = set()
    for path in source_files():
        raw = path.read_bytes()
        definitions = blocks(raw.decode("utf-8-sig"))
        kept = sorted(RESERVED & definitions.keys())
        retained.update(kept)
        total += len(definitions)
        records.append({
            "file": path.name,
            "source_sha256": hashlib.sha256(raw).hexdigest(),
            "definitions": len(definitions),
            "retained": kept,
        })
    active = blocks(ACTIVE.read_text(encoding="utf-8-sig"))
    if len(active) != 463:
        raise ValueError(f"active ANTIQVITAS registry drift: {len(active)}")
    if retained != RESERVED:
        raise ValueError(f"reserved country sentinel drift: {sorted(retained)}")
    if set(active) & RESERVED:
        raise ValueError("active roster collides with reserved country sentinels")
    return {
        "schema": 1,
        "installed_definitions": total,
        "active_definitions": len(active),
        "retained_engine_sentinels": sorted(retained),
        "files": records,
    }


def write() -> None:
    for source in source_files():
        destination = ROOT / RELATIVE_ROOT / source.name
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(render(source))
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(
        json.dumps(expected_manifest(), indent=2) + "\n", encoding="utf-8", newline="\n"
    )
    print("m12_country_registry: wrote 45 exact mirrors and audited 463 active definitions")


def check() -> bool:
    try:
        stale = [
            source.name for source in source_files()
            if not (ROOT / RELATIVE_ROOT / source.name).is_file()
            or (ROOT / RELATIVE_ROOT / source.name).read_bytes() != render(source)
        ]
        manifest = json.dumps(expected_manifest(), indent=2) + "\n"
        if not MANIFEST.is_file() or MANIFEST.read_text(encoding="utf-8") != manifest:
            stale.append(MANIFEST.as_posix())
    except (OSError, ValueError, KeyError, json.JSONDecodeError) as exc:
        print(f"m12_country_registry: FAIL\n  - {exc}")
        return False
    if stale:
        print("m12_country_registry: FAIL\n  - stale or missing " + ", ".join(stale[:8]))
        return False
    print("m12_country_registry: PASS (2,337 inherited definitions removed; 3 engine sentinels + 463 active retained)")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        try:
            write()
        except (OSError, ValueError, KeyError, json.JSONDecodeError) as exc:
            print(f"m12_country_registry: FAIL\n  - {exc}")
            return 1
        return 0
    return 0 if check() else 1


if __name__ == "__main__":
    raise SystemExit(main())
