#!/usr/bin/env python3
"""Generate namespaced ancient replacements for the last installed buildings."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LEDGER = ROOT / "docs/m5/ancient_building_replacements.csv"
OUTPUT = ROOT / "in_game/common/building_types/00_antiquitas_adapter_replacements.txt"
ICON_DIR = ROOT / "main_menu/gfx/interface/icons/buildings"
LOC_ROOT = ROOT / "main_menu/localization"
GOODS = ROOT / "docs/vanilla_symbols/good.json"
SPECIALS = ROOT / "docs/m5/special_buildings.csv"
FORTS = ROOT / "docs/m7/forts.csv"
DDS = ROOT / "tools/dds.py"
LANGUAGES = (
    "english", "french", "german", "spanish", "polish", "russian", "braz_por",
    "simp_chinese", "japanese", "korean", "turkish",
)
FIELDS = (
    "key", "name", "description", "is_special", "max_levels", "category",
    "pop_type", "employment_size", "build_time", "modifier", "maintenance",
    "goods", "potential", "construction", "source", "confidence", "note",
    "icon_subject",
)
POTENTIALS = {"none", "waterways", "port", "buddhist", "disabled"}
MODIFIERS = {
    "local_clergy_max_literacy", "local_cultural_tradition",
    "local_garrison_size", "local_max_literacy", "local_merchant_capacity",
    "local_merchant_power", "local_monthly_food_modifier",
    "local_population_capacity", "local_repair_speed", "local_sailors",
    "local_unrest",
}


def pairs(value: str, label: str) -> list[tuple[str, str]]:
    result: list[tuple[str, str]] = []
    for item in value.split(";"):
        key, separator, amount = item.partition("=")
        if not separator or not key.strip() or not amount.strip():
            raise ValueError(f"invalid {label} pair {item!r}")
        float(amount)
        result.append((key.strip(), amount.strip()))
    return result


def load() -> list[dict[str, str]]:
    with LEDGER.open(encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        if tuple(reader.fieldnames or ()) != FIELDS:
            raise ValueError(f"{LEDGER.relative_to(ROOT)} header mismatch")
        rows = [
            {field: (row.get(field) or "").strip() for field in FIELDS}
            for row in reader
        ]
    goods = set(json.loads(GOODS.read_text(encoding="utf-8-sig")))
    seen: set[str] = set()
    failures: list[str] = []
    for number, row in enumerate(rows, start=2):
        prefix = f"{LEDGER.relative_to(ROOT)}:{number}"
        if any(not row[field] for field in FIELDS):
            failures.append(f"{prefix}: blank required field")
        if not re.fullmatch(r"antq_[a-z0-9_]+", row["key"]):
            failures.append(f"{prefix}: invalid namespaced key")
        if row["key"] in seen:
            failures.append(f"{prefix}: duplicate key {row['key']}")
        if row["is_special"] not in {"yes", "no"}:
            failures.append(f"{prefix}: is_special must be yes or no")
        if row["potential"] not in POTENTIALS:
            failures.append(f"{prefix}: invalid potential {row['potential']}")
        if row["confidence"] not in {"secure", "contested"}:
            failures.append(f"{prefix}: invalid confidence")
        try:
            modifiers = pairs(row["modifier"], "modifier")
            maintenance = pairs(row["maintenance"], "maintenance")
            unknown_modifiers = {key for key, _ in modifiers} - MODIFIERS
            if unknown_modifiers:
                failures.append(f"{prefix}: unverified modifiers {sorted(unknown_modifiers)}")
            listed = {item for item in row["goods"].split(";") if item}
            used = {key for key, _ in maintenance}
            if listed != used:
                failures.append(f"{prefix}: goods differ from maintenance inputs")
            if used - goods:
                failures.append(f"{prefix}: unknown goods {sorted(used - goods)}")
        except ValueError as exc:
            failures.append(f"{prefix}: {exc}")
        seen.add(row["key"])
    if len(rows) != 8:
        failures.append(f"expected eight active replacements, found {len(rows)}")
    placed = set()
    for path, field in ((SPECIALS, "building"), (FORTS, "building")):
        with path.open(encoding="utf-8-sig", newline="") as handle:
            placed.update((row.get(field) or "").strip() for row in csv.DictReader(handle))
    required = {row["key"] for row in rows}
    if required - placed:
        failures.append(f"replacement buildings lack AD 1 seeds: {sorted(required - placed)}")
    if failures:
        raise ValueError("\n".join(failures))
    return rows


def definition(rows: list[dict[str, str]]) -> str:
    lines = [
        "# Generated by tools/m5_ancient_building_replacements.py --write.",
        "# Namespaced AD 1 replacements for the final installed building adapters.",
        "",
    ]
    rural = {"antq_irrigation_network", "antq_earthwork_stockade"}
    for row in rows:
        lines.extend((
            f"{row['key']} = {{",
            "\taudio_tier = 2",
            f"\tis_special = {row['is_special']}",
            "\tis_foreign = no",
            f"\tpop_type = {row['pop_type']}",
            f"\tmax_levels = {row['max_levels']}",
            f"\tcategory = {row['category']}",
            f"\temployment_size = {row['employment_size']}",
        ))
        if row["key"] in rural:
            lines.append("\trural_settlement = yes")
        lines.extend((
            "\ttown = yes", "\tcity = yes", "\tmegalopolis = yes",
            f"\tbuild_time = {row['build_time']}",
        ))
        potential = row["potential"]
        if potential == "waterways":
            lines.extend((
                "\tlocation_potential = {", "\t\tOR = {",
                "\t\t\thas_river = yes", "\t\t\tis_adjacent_to_lake = yes",
                "\t\t}", "\t}",
            ))
        elif potential == "port":
            lines.extend(("\tlocation_potential = {", "\t\tis_port = yes", "\t}"))
        elif potential == "buddhist":
            lines.extend((
                "\tcountry_potential = {",
                "\t\treligion ?= { group = religion_group:antq_buddhist_group }",
                "\t}",
            ))
        elif potential == "disabled":
            lines.extend((
                "\tcountry_potential = { always = no }",
                "\tallow = { always = no }",
            ))
        lines.append("\tmodifier = {")
        lines.extend(f"\t\t{key} = {amount}" for key, amount in pairs(row["modifier"], "modifier"))
        lines.extend((
            "\t}", "\tunique_production_methods = {",
            f"\t\t{row['key']}_maintenance = {{",
        ))
        lines.extend(
            f"\t\t\t{key} = {amount}"
            for key, amount in pairs(row["maintenance"], "maintenance")
        )
        lines.extend((
            "\t\t\tcategory = building_maintenance", "\t\t}", "\t}",
            f"\tconstruction_demand = {row['construction']}",
        ))
        if row["key"] == "antq_earthwork_stockade":
            lines.extend((
                "\traw_modifier = {", "\t\tfort_level = 1",
                "\t\tpure_tooltip_entry = pte_no_propagating_zone_of_control", "\t}",
            ))
        lines.extend(("}", ""))
    return "\n".join(lines)


def localization(rows: list[dict[str, str]], language: str) -> str:
    lines = [
        f"l_{language}:",
        " # Generated ancient building replacements; English mirrored by design.",
    ]
    for row in rows:
        name = row["name"].replace('"', "'")
        description = row["description"].replace('"', "'")
        lines.extend((
            f' {row["key"]}: "{name}"',
            f' {row["key"]}_desc: "{description}"',
            f' {row["key"]}_maintenance: "{name} Upkeep"',
        ))
    return "\n".join(lines) + "\n"


def expected(rows: list[dict[str, str]]) -> dict[Path, tuple[str, str]]:
    result = {OUTPUT: (definition(rows), "utf-8-sig")}
    for language in LANGUAGES:
        result[
            LOC_ROOT / language / f"antq_m5_ancient_building_replacements_l_{language}.yml"
        ] = (localization(rows, language), "utf-8-sig")
    return result


def dds_ok(path: Path) -> bool:
    result = subprocess.run(
        [sys.executable, str(DDS), "identify", str(path)],
        text=True, capture_output=True,
    )
    if result.returncode:
        return False
    return json.loads(result.stdout) == {
        "format": "DDS", "width": "128", "height": "128",
        "depth": "8", "channels": "srgba 4.0",
    }


def validate_art(rows: list[dict[str, str]]) -> None:
    hashes: dict[str, str] = {}
    failures: list[str] = []
    for row in rows:
        icon = ICON_DIR / f"{row['key']}.dds"
        if not icon.is_file() or not dds_ok(icon):
            failures.append(f"missing or invalid direct icon {icon.relative_to(ROOT)}")
            continue
        digest = hashlib.sha256(icon.read_bytes()).hexdigest()
        if digest in hashes:
            failures.append(f"duplicate icons {hashes[digest]} and {row['key']}")
        hashes[digest] = row["key"]
    if failures:
        raise ValueError("\n".join(failures))


def main() -> int:
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true")
    group.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        rows = load()
        outputs = expected(rows)
        if args.write:
            for path, (content, encoding) in outputs.items():
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding=encoding, newline="\n")
        stale = [
            path.relative_to(ROOT)
            for path, (content, encoding) in outputs.items()
            if not path.is_file() or path.read_text(encoding=encoding) != content
        ]
        if stale:
            raise ValueError(f"stale generated outputs: {stale}")
        validate_art(rows)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"m5_ancient_building_replacements: FAIL\n  - {exc}")
        return 1
    print(f"m5_ancient_building_replacements: PASS ({len(rows)} direct ancient replacements)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
