#!/usr/bin/env python3
"""Generate the exclusive AD 1 holy-site union and future-faith lifecycle text."""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from pathlib import Path

from m12_system_quarantine import render_quarantine


ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "config/local_paths.json"
LEDGER = ROOT / "docs/r5/holy_sites.csv"
SITE_DIR = ROOT / "in_game/common/holy_sites"
SITE_FILE = SITE_DIR / "antq_r5_holy_sites.txt"
TYPE_FILE = ROOT / "in_game/common/holy_site_types/00_holy_site_types.txt"
ACTION_FILE = ROOT / "in_game/common/generic_actions/autocephalous_patriarchates.txt"
LOC_ROOT = ROOT / "main_menu/localization"
CLIENTS = (
    "english", "french", "german", "spanish", "polish", "russian",
    "turkish", "braz_por", "simp_chinese", "japanese", "korean",
)
FIELDS = (
    "site_key", "location", "type", "importance", "religions", "name",
    "description", "source", "date_note",
)
TYPES = (
    "sanctuary", "temple_complex", "sacred_grove", "sacred_mountain",
    "pilgrimage_city", "ancestral_precinct", "oracle",
)
SHARED_BUILDING_LOC = {
    "antq_second_temple_jerusalem",
    "antq_second_temple_jerusalem_desc",
}
FUTURE_SITES = {
    "antq_christian_jerusalem_memory": (
        "Jerusalem Christian Memory", "The earliest Jerusalem community preserves the memory of Jesus and the first assemblies.",
    ),
    "antq_christian_antioch_community": (
        "Antiochene Christian Community", "Antioch becomes a major meeting place for the early movement along Syrian and Mediterranean roads.",
    ),
    "antq_christian_ephesos_community": (
        "Ephesian Christian Community", "The Christian assembly at Ephesos links Anatolian cities with Aegean travel and correspondence.",
    ),
    "antq_christian_roman_memory": (
        "Roman Christian Memory", "Rome's early community gathers around apostolic memory, household assemblies, and the first martyr traditions.",
    ),
    "antq_daoist_chengdu_community": (
        "Chengdu Celestial Masters", "Organized communities in the Chengdu basin join household registers, ritual leadership, and the Way of the Celestial Masters.",
    ),
    "antq_daoist_hanzhong_community": (
        "Hanzhong Celestial Masters", "The Hanzhong community anchors the later Han movement's northern basin and mountain routes.",
    ),
    "antq_manichaean_babylonia_mission": (
        "Babylonian Manichaean Mission", "Mani's first communities spread through Babylonia and the Arsacid-Sasanian road world.",
    ),
}
TOP_LEVEL = re.compile(r"(?m)^([a-z][a-z0-9_]*)\s*=\s*\{")
LOC_LINE = re.compile(r'^\s*([^#\s][^:]*):(?:\d+)?\s+"(.*)"\s*$')


def game_root() -> Path:
    return Path(json.loads(CONFIG.read_text(encoding="utf-8-sig"))["game_dir"]) / "game"


def rows() -> list[dict[str, str]]:
    with LEDGER.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        if tuple(reader.fieldnames or ()) != FIELDS:
            raise ValueError(f"holy-site schema {reader.fieldnames} != {FIELDS}")
        return [{key: (value or "").strip() for key, value in row.items()} for row in reader]


def religion_keys() -> set[str]:
    text = (ROOT / "in_game/common/religions/antq_m4_religions.txt").read_text(encoding="utf-8-sig")
    return set(TOP_LEVEL.findall(text))


def installed_site_files() -> set[str]:
    return {
        path.name for path in (game_root() / "in_game/common/holy_sites").glob("*.txt")
        if path.name != "readme.txt"
    }


def action_bytes() -> bytes:
    source = game_root() / "in_game/common/generic_actions/autocephalous_patriarchates.txt"
    rendered, definitions = render_quarantine(
        source,
        "generic_actions",
        "potential",
        preserve_generic_registry=True,
    )
    if definitions != 5:
        raise ValueError(f"expected five patriarchate action adapters, found {definitions}")
    return rendered


def site_bytes(values: list[dict[str, str]]) -> bytes:
    lines = ["# Generated by tools/r5_holy_sites.py --write.", ""]
    for row in values:
        religions = " ".join(row["religions"].split("|"))
        lines.extend((
            f"{row['site_key']} = {{",
            f"\tlocation = {row['location']}",
            f"\ttype = {row['type']}",
            f"\timportance = {row['importance']}",
            f"\treligions = {{ {religions} }}",
            "}", "",
        ))
    return ("\n".join(lines) + "\n").encode("utf-8-sig")


def type_bytes() -> bytes:
    bodies = {
        "sanctuary": "local_clergy_desired_pop = 0.02\n\t\tlocal_unrest = -0.03",
        "temple_complex": "local_clergy_desired_pop = 0.05\n\t\tlocal_monthly_prosperity = 0.001\n\t\tlocal_max_control = 0.01",
        "sacred_grove": "local_clergy_desired_pop = 0.02\n\t\tlocal_monthly_food_modifier = 0.02",
        "sacred_mountain": "local_clergy_desired_pop = 0.04\n\t\tlocal_max_literacy = 1",
        "pilgrimage_city": "local_population_capacity_modifier = 0.10\n\t\tlocal_clergy_desired_pop = 0.04\n\t\tlocal_institution_growth_modifier = 0.01",
        "ancestral_precinct": "local_clergy_desired_pop = 0.025\n\t\tlocal_monthly_control = 0.001",
        "oracle": "local_clergy_desired_pop = 0.03\n\t\tlocal_monthly_prosperity = 0.001",
    }
    installed = (
        game_root() / "in_game/common/holy_site_types/00_holy_site_types.txt"
    ).read_text(encoding="utf-8-sig").rstrip()
    lines = [
        "# Generated by tools/r5_holy_sites.py --write.",
        "# Installed type keys remain resolvable; mounted holy-site instances are quarantined.",
        "",
        installed,
        "",
    ]
    for key in TYPES:
        lines.extend((f"{key} = {{", "\tlocation_modifier = {", f"\t\t{bodies[key]}", "\t}", "}", ""))
    return ("\n".join(lines) + "\n").encode("utf-8-sig")


def loc_values(values: list[dict[str, str]]) -> dict[str, str]:
    result = {
        key: value
        for site_key, pair in FUTURE_SITES.items()
        for key, value in ((site_key, pair[0]), (f"{site_key}_desc", pair[1]))
    }
    for row in values:
        result[row["site_key"]] = row["name"]
        result[f"{row['site_key']}_desc"] = row["description"]
    for key in TYPES:
        result[key] = key.replace("_", " ").title()
    # The Second Temple is both a physical opening building and a holy site.
    # Keep one authoritative localization in the building replacement file.
    for key in SHARED_BUILDING_LOC:
        result.pop(key, None)
    return result


def loc_bytes(client: str, values: list[dict[str, str]]) -> bytes:
    lines = [f"l_{client}:"]
    for key, value in sorted(loc_values(values).items()):
        lines.append(f' {key}: "{value.replace(chr(34), chr(92) + chr(34))}"')
    return ("\n".join(lines) + "\n").encode("utf-8-sig")


def write() -> None:
    values = rows()
    SITE_DIR.mkdir(parents=True, exist_ok=True)
    for filename in installed_site_files():
        (SITE_DIR / filename).write_bytes(
            b"\xef\xbb\xbf# Exact-path ANTIQVITAS quarantine: inherited holy site unavailable.\n"
        )
    SITE_FILE.write_bytes(site_bytes(values))
    TYPE_FILE.parent.mkdir(parents=True, exist_ok=True)
    TYPE_FILE.write_bytes(type_bytes())
    ACTION_FILE.parent.mkdir(parents=True, exist_ok=True)
    ACTION_FILE.write_bytes(action_bytes())
    for client in CLIENTS:
        path = LOC_ROOT / client / f"antq_r5_holy_sites_l_{client}.yml"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(loc_bytes(client, values))
    print(f"r5_holy_sites: wrote {len(values)} AD 1 sites and 11 localization mirrors")


def effective_loc(client: str) -> dict[str, str]:
    result: dict[str, str] = {}
    for path in sorted((LOC_ROOT / client).glob("*.yml")):
        for line in path.read_text(encoding="utf-8-sig").splitlines():
            match = LOC_LINE.match(line)
            if match:
                result[match.group(1)] = match.group(2)
    return result


def validate() -> None:
    values = rows()
    failures: list[str] = []
    locations = set(json.loads((ROOT / "docs/vanilla_symbols/locations.json").read_text(encoding="utf-8-sig")))
    religions = religion_keys()
    active = set(
        re.findall(
            r"\breligion\s*=\s*(antq_[a-z0-9_]+)",
            (ROOT / "main_menu/setup/start/06_pops.txt").read_text(encoding="utf-8-sig"),
        )
    )
    keys: set[str] = set()
    used_locations: set[str] = set()
    covered: set[str] = set()
    for row in values:
        key = row["site_key"]
        if not key.startswith("antq_") or key in keys:
            failures.append(f"invalid or duplicate holy-site key: {key}")
        keys.add(key)
        if row["location"] not in locations or row["location"] in used_locations:
            failures.append(f"invalid or duplicate holy-site location: {row['location']}")
        used_locations.add(row["location"])
        if row["type"] not in TYPES or not row["importance"].isdigit() or not 1 <= int(row["importance"]) <= 5:
            failures.append(f"invalid type/importance at {key}")
        site_religions = set(row["religions"].split("|"))
        if not site_religions or not site_religions <= religions:
            failures.append(f"invalid religions at {key}: {sorted(site_religions - religions)}")
        if site_religions & {"antq_early_christianity", "antq_daoism", "antq_manichaeism"}:
            failures.append(f"future religion statically owns {key}")
        covered.update(site_religions)
        if not row["source"] or not row["date_note"]:
            failures.append(f"missing source/date note at {key}")
    if covered != active:
        failures.append(f"active-faith site coverage differs: missing={sorted(active-covered)} extra={sorted(covered-active)}")
    if set(TOP_LEVEL.findall(SITE_FILE.read_text(encoding="utf-8-sig"))) != keys:
        failures.append("mounted holy-site catalogue differs from ledger")
    if SITE_FILE.read_bytes() != site_bytes(values) or TYPE_FILE.read_bytes() != type_bytes():
        failures.append("holy-site or type output is stale")
    for filename in installed_site_files():
        path = SITE_DIR / filename
        if not path.is_file() or TOP_LEVEL.search(path.read_text(encoding="utf-8-sig")):
            failures.append(f"inherited holy-site file not quarantined: {filename}")
    if not ACTION_FILE.is_file() or ACTION_FILE.read_bytes() != action_bytes():
        failures.append("autocephalous patriarchate action adapters are stale")
    allowed_calls = {
        # Preserved inside a permanently hidden installed action adapter so
        # the engine can validate the action body and its hardcoded callers.
        "in_game/common/generic_actions/autocephalous_patriarchates.txt": 1,
        "in_game/events/antq_m10_first_century.txt": 4,
        "in_game/events/antq_m10_second_century.txt": 2,
        "in_game/events/antq_m10_third_century.txt": 1,
    }
    found_calls: dict[str, int] = {}
    for path in (ROOT / "in_game").rglob("*.txt"):
        count = path.read_text(encoding="utf-8-sig").count("create_holy_site")
        if count:
            found_calls[path.relative_to(ROOT).as_posix()] = count
    if found_calls != allowed_calls:
        failures.append(f"holy-site lifecycle calls differ: {found_calls}")
    for client in CLIENTS:
        path = LOC_ROOT / client / f"antq_r5_holy_sites_l_{client}.yml"
        if not path.is_file() or path.read_bytes() != loc_bytes(client, values):
            failures.append(f"stale holy-site localization: {client}")
        loc = effective_loc(client)
        for key in (*keys, *FUTURE_SITES, *TYPES):
            if key not in loc:
                failures.append(f"{client}: missing holy-site localization {key}")
    if failures:
        raise ValueError("\n  - ".join(["holy-site validation failed", *failures]))
    print(f"r5_holy_sites: PASS ({len(keys)} AD 1 sites; {len(active)} active faiths; 7 future lifecycle sites; 11 clients)")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        write()
    if args.check or not args.write:
        validate()
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, UnicodeError, ValueError, json.JSONDecodeError) as exc:
        print(f"r5_holy_sites: FAIL\n  - {exc}", file=sys.stderr)
        raise SystemExit(1)
