#!/usr/bin/env python3
"""Own Round 5 disease, situation, and universal-currency unions."""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

from dates import AntqDate, END
from m12_system_quarantine import render_quarantine


ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "config/local_paths.json"
DISEASE_DIR = ROOT / "in_game/common/diseases"
SITUATION_DIR = ROOT / "in_game/common/situations"
LOC_ROOT = ROOT / "main_menu/localization"
CLIENTS = (
    "english", "french", "german", "spanish", "polish", "russian",
    "turkish", "braz_por", "simp_chinese", "japanese", "korean",
)
FORBIDDEN_DISEASE = re.compile(
    r"black_death|columbian|stock_exchange|situation:|current_age|1[0-9]{3}\.|"
    r"vaccin|quinine|jesuit|new_world|colon",
    re.IGNORECASE,
)
FORBIDDEN_CURRENCY_CONTEXT = re.compile(
    r"\b(?:Ottoman|Napoleonic|medieval|modern(?:ized)?|feudal|Western-style|"
    r"Voivode|Renaissance|colonial|industrial|parliamentary|gunpowder|"
    r"centur(?:y|ies)|1[0-9]{3})\b",
    re.IGNORECASE,
)
LOC_LINE = re.compile(r'^\s*([^#\s][^:]*):(?:\d+)?\s+"(.*)"\s*$')
TOP_LEVEL = re.compile(r"(?m)^([a-z][a-z0-9_]*)\s*=\s*\{")


@dataclass(frozen=True)
class Disease:
    key: str
    name: str
    description: str
    spawn: float
    r0: tuple[float, float]
    mortality: tuple[float, float]
    interval: tuple[int, int]
    fate: float
    stagnation: float
    growth: float
    attrition: float
    color: tuple[int, int, int]


DISEASES = (
    Disease("bubonic_plague", "Pestilence of Swellings", "A violent pestilence marked by fever, weakness, and painful swellings. Crowded ports, camps, and caravan roads can carry it onward before households know the danger.", 0.002, (1.4, 2.8), (0.20, 0.45), (7, 15), 0.30, 0.24, -0.06, 4, (86, 32, 38)),
    Disease("great_pestilence", "Great Camp Pestilence", "A compound mortality of flux, fever, hunger, and exhaustion spreading through displaced hosts and overburdened towns. Its name records the flux, fever, hunger, and exhaustion that sufferers can observe.", 0.003, (1.2, 2.4), (0.12, 0.32), (8, 18), 0.28, 0.26, -0.05, 3, (104, 70, 42)),
    Disease("influenza", "Winter Catarrh", "A fast-moving cough and fever that returns with the cold season. Most recover, but infants, elders, and people already weakened by hunger or wounds may die.", 0.025, (2.0, 4.0), (0.005, 0.025), (4, 9), 0.45, 0.18, -0.01, 1, (92, 142, 172)),
    Disease("measles", "Speckled Fever", "An intensely contagious fever with cough and a spreading red eruption. Dense settlements sustain it, while communities without prior exposure suffer the heaviest childhood losses.", 0.012, (3.0, 6.0), (0.02, 0.08), (5, 11), 0.35, 0.16, -0.025, 1, (178, 88, 62)),
    Disease("smallpox", "Pustular Fever", "Fever and vomiting are followed by deep pustules across the body. Survivors often bear scars or damaged sight, while connected cities and armies allow new outbreaks to travel far.", 0.010, (2.5, 5.0), (0.08, 0.28), (5, 12), 0.30, 0.20, -0.04, 2, (92, 142, 82)),
    Disease("typhus", "Camp Fever", "Lice-borne fever, rash, and delirium flourish where armies, prisoners, refugees, or the hungry crowd together without clean clothing and shelter.", 0.008, (1.5, 3.5), (0.04, 0.18), (5, 12), 0.34, 0.22, -0.035, 3, (126, 82, 116)),
)

MALARIA = Disease(
    "malaria", "Marsh Fever",
    "Recurring chills and burning fever burden warm wetlands and irrigated lowlands. The sickness follows local waters and seasons rather than passing directly from one sufferer to another.",
    0.0, (0.0, 0.0), (0.01, 0.06), (10, 18), 1.0, 0.0, -0.02, 1,
    (44, 76, 126),
)

COMPATIBILITY_EVENTS = {
    "bubonic_plague": "black_death.2",
    "great_pestilence": "great_pestilence.1",
    "influenza": "diseases.1",
    "measles": "diseases.1",
    "smallpox": "diseases.1",
    "typhus": "diseases.1",
}


def game_root() -> Path:
    return Path(json.loads(CONFIG.read_text(encoding="utf-8-sig"))["game_dir"]) / "game"


def installed_files(relative: str) -> tuple[str, ...]:
    directory = game_root() / relative
    return tuple(sorted(path.name for path in directory.glob("*.txt") if path.name != "readme.txt"))


def render_epidemic(disease: Disease) -> str:
    key = disease.key
    event = COMPATIBILITY_EVENTS[key]
    return f"""# Generated by tools/r5_visible_unions.py --write.\n{key} = {{
\tmonthly_spawn_chance = {{ value = {disease.spawn:.3f} }}
\tspawn = {{
\t\trandom_ownable_location = {{
\t\t\tlimit = {{ is_land = yes population > 1 }}
\t\t\tspawn_disease = {{ disease = scope:disease value = 0.35 save_scope_as = outbreak }}
\t\t}}
\t}}
\tr0 = {{ value = {{ {disease.r0[0]:g} {disease.r0[1]:g} }} }}
\tcalc_interval_days = {{ {disease.interval[0]} {disease.interval[1]} }}
\tlocation_stagnation_chance = {{ value = {disease.stagnation:g} }}
\tpercentage_to_meet_their_fate_on_calc = {{ value = {disease.fate:g} }}
\tlocation_spread_threshold = {{ value = 0.12 }}
\tmonthly_resistance_reduction = 0.001
\tmortality_rate = {{ value = {{ {disease.mortality[0]:g} {disease.mortality[1]:g} }} }}
\tcharacter_mortality_chance = {{ value = {disease.mortality[0]:g} multiply = \"disease_presence(scope:disease)\" }}
\tlocation_modifier = {{
\t\tlocal_population_growth = {disease.growth:g}
\t\tlocal_forced_attrition = {disease.attrition:g}
\t\tlocal_pop_promotion_speed_modifier = -0.2
\t\tlocal_prosperity_decay = 0.01
\t\tlocal_migration_attraction = -0.5
\t}}
\ton_spread_to_country = {{
\t\tif = {{ limit = {{ always = no }} trigger_event_non_silently = {event} }}
\t}}
\tmap_color = {{ lerp = {{ min_color = rgb {{ 170 160 140 }} max_color = rgb {{ {disease.color[0]} {disease.color[1]} {disease.color[2]} }} factor = \"disease_presence(scope:disease)\" }} }}
\tsecondary_map_color = {{ if = {{ limit = {{ disease_affects_pops_here = scope:disease }} value = rgb {{ {disease.color[0]} {disease.color[1]} {disease.color[2]} }} }} }}
}}\n"""


def render_malaria() -> str:
    disease = MALARIA
    return f"""# Generated by tools/r5_visible_unions.py --write.\nmalaria = {{
\tmonthly_spawn_chance = {{ value = 0 }}
\tspawn = {{}}
\tmonthly_resistance_reduction = 0
\tr0 = {{ value = 0 }}
\tenvironmental_infection = {{
\t\tvalue = 0.025
\t\tif = {{ limit = {{ climate = subtropical }} multiply = 1.75 }}
\t\telse_if = {{ limit = {{ climate = tropical }} multiply = 2 }}
\t\telse_if = {{ limit = {{ climate = mediterranean }} multiply = 0.35 }}
\t\telse_if = {{ limit = {{ climate = oceanic }} multiply = 0.15 }}
\t\telse_if = {{ limit = {{ OR = {{ climate = arctic climate = continental climate = cold_arid }} }} multiply = 0 }}
\t\tif = {{ limit = {{ topography = wetlands }} multiply = 3 }}
\t\telse_if = {{ limit = {{ topography = mountains }} multiply = 0 }}
\t\tif = {{ limit = {{ vegetation = desert }} multiply = 0 }}
\t\telse_if = {{ limit = {{ vegetation = jungle }} multiply = 1.25 }}
\t}}
\tcalc_interval_days = {{ {disease.interval[0]} {disease.interval[1]} }}
\tlocation_stagnation_chance = {{ value = 0 }}
\tpercentage_to_meet_their_fate_on_calc = {{ value = 1 }}
\tlocation_modifier = {{ local_population_growth = -0.02 local_prosperity_decay = 0.003 }}
\tmortality_rate = {{ value = {{ {disease.mortality[0]:g} {disease.mortality[1]:g} }} }}
\tcharacter_mortality_chance = {{ value = 0.01 multiply = \"disease_presence(scope:disease)\" }}
\ton_spread_to_country = {{}}
\tmap_color = {{ lerp = {{ min_color = rgb {{ 100 120 188 }} max_color = rgb {{ 44 76 126 }} factor = \"disease_presence(scope:disease)\" }} }}
\tsecondary_map_color = {{ if = {{ limit = {{ disease_has_outbreak_here = scope:disease }} value = rgb {{ 44 76 126 }} }} }}
}}\n"""


def situation_bytes(filename: str) -> bytes:
    source = game_root() / "in_game/common/situations" / filename
    rendered, definitions = render_quarantine(
        source, "situations", ("can_start", "visible")
    )
    if definitions != 1:
        raise ValueError(f"{filename}: expected one installed situation, found {definitions}")
    had_bom = rendered.startswith(b"\xef\xbb\xbf")
    text = rendered.decode("utf-8-sig")
    inert_date = AntqDate(*END).engine()

    def clamp(match: re.Match[str]) -> str:
        return inert_date if int(match.group(1)) > END[0] else match.group(0)

    text = re.sub(r"\b(\d{3,4})\.\d{1,2}\.\d{1,2}\b", clamp, text)
    if filename in {"black_death.txt", "great_pestilence.txt"}:
        marker = "\ton_start = {"
        if marker not in text:
            raise ValueError(f"{filename}: installed situation lacks on_start")
        # The installed adapters dereference this engine compatibility variable.
        # Their start and visibility gates are permanently false, so a neutral
        # initializer satisfies the reference graph without activating them.
        text = text.replace(
            marker,
            marker + "\n\t\tset_variable = { name = original_outbreak value = no }",
            1,
        )
    return text.encode("utf-8-sig" if had_bom else "utf-8")


def installed_ducat_entries() -> dict[str, str]:
    entries: dict[str, str] = {}
    for path in sorted((game_root() / "main_menu/localization/english").rglob("*.yml")):
        for line in path.read_text(encoding="utf-8-sig").splitlines():
            match = LOC_LINE.match(line)
            if match and re.search(r"\bducats?\b", match.group(2), re.IGNORECASE):
                entries[match.group(1)] = match.group(2)
    return entries


def currency_entries() -> dict[str, str]:
    entries = installed_ducat_entries()
    rewritten: dict[str, str] = {}
    for key, value in entries.items():
        value = re.sub(r"\bducats?\b", "wealth", value, flags=re.IGNORECASE)
        if FORBIDDEN_CURRENCY_CONTEXT.search(value):
            if key.endswith("historical_info"):
                value = "This agreement records a transfer of wealth between the participating states."
            elif key.endswith("_desc"):
                value = "Accounts, appointed scribes, and audited stores improve the state's control of wealth."
            else:
                value = "Wealth"
        rewritten[key] = value
    rewritten["gold"] = "Wealth"
    rewritten["game_concept_gold"] = "Wealth"
    rewritten["game_concept_gold_desc"] = (
        "A universal measure of liquid wealth: coin, weighed metal, valuables, "
        "and trusted accounting claims. A country's current reserve is its "
        "[treasury|e].\\n\\nWealth comes from [taxes|e], [estates|e], [subjects|e], "
        "and exchange, and pays for [buildings|e], [armies|e], food, goods, "
        "diplomacy, and the [court|e]."
    )
    return rewritten


def disease_loc() -> dict[str, str]:
    values: dict[str, str] = {}
    for disease in (*DISEASES, MALARIA):
        values[disease.key] = disease.name
        values[f"{disease.key}_desc"] = disease.description
        values[f"{disease.key}_location_modifier"] = f"{disease.name} burden"
        values[f"local_{disease.key}_impact_modifier"] = f"{disease.name} impact"
    return values


def loc_bytes(client: str) -> bytes:
    lines = [f"l_{client}:"]
    for key, value in sorted({**currency_entries(), **disease_loc()}.items()):
        escaped = value.replace('"', '\\"')
        lines.append(f' {key}: "{escaped}"')
    return ("\n".join(lines) + "\n").encode("utf-8-sig")


def write() -> None:
    DISEASE_DIR.mkdir(parents=True, exist_ok=True)
    expected_diseases = set(installed_files("in_game/common/diseases"))
    rendered = {disease.key + ".txt": render_epidemic(disease) for disease in DISEASES}
    rendered["malaria.txt"] = render_malaria()
    if set(rendered) != expected_diseases:
        raise ValueError(f"disease file union changed: {sorted(expected_diseases ^ set(rendered))}")
    for filename, text in rendered.items():
        (DISEASE_DIR / filename).write_bytes(text.encode("utf-8-sig"))

    SITUATION_DIR.mkdir(parents=True, exist_ok=True)
    for filename in installed_files("in_game/common/situations"):
        (SITUATION_DIR / filename).write_bytes(situation_bytes(filename))

    for client in CLIENTS:
        path = LOC_ROOT / client / f"antq_r5_visible_unions_l_{client}.yml"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(loc_bytes(client))
    print("r5_visible_unions: wrote 7 diseases, 22 inert situation adapters, and 11 localization mirrors")


def effective_mod_loc(client: str) -> dict[str, str]:
    values: dict[str, str] = {}
    for path in sorted((LOC_ROOT / client).rglob("*.yml")):
        for line in path.read_text(encoding="utf-8-sig").splitlines():
            match = LOC_LINE.match(line)
            if match:
                values[match.group(1)] = match.group(2)
    return values


def validate() -> None:
    failures: list[str] = []
    expected_diseases = set(installed_files("in_game/common/diseases"))
    actual_diseases = {path.name for path in DISEASE_DIR.glob("*.txt")}
    if actual_diseases != expected_diseases:
        failures.append(f"disease files differ from installed union: {sorted(actual_diseases ^ expected_diseases)}")
    for path in sorted(DISEASE_DIR.glob("*.txt")):
        if not path.read_bytes().startswith(b"\xef\xbb\xbf"):
            failures.append(f"{path}: disease script is not UTF-8 BOM")
        text = path.read_text(encoding="utf-8-sig")
        definitions = TOP_LEVEL.findall(text)
        if definitions != [path.stem]:
            failures.append(f"{path}: definitions {definitions} != [{path.stem}]")
        scan_text = text
        compatibility_event = COMPATIBILITY_EVENTS.get(path.stem)
        if compatibility_event:
            inert_reference = (
                "\t\tif = { limit = { always = no } "
                f"trigger_event_non_silently = {compatibility_event} }}"
            )
            if text.count(inert_reference) != 1:
                failures.append(f"{path}: missing exact inert compatibility-event reference")
            scan_text = scan_text.replace(inert_reference, "", 1)
        forbidden = FORBIDDEN_DISEASE.search(scan_text)
        if forbidden:
            failures.append(f"{path}: forbidden inherited disease token {forbidden.group(0)!r}")
        for required in ("mortality_rate", "location_modifier", "map_color", "calc_interval_days"):
            if required not in text:
                failures.append(f"{path}: missing {required}")

    installed_situations = set(installed_files("in_game/common/situations"))
    for filename in sorted(installed_situations):
        path = SITUATION_DIR / filename
        expected = situation_bytes(filename)
        if not path.is_file() or path.read_bytes() != expected:
            failures.append(f"inherited situation adapter is stale: {filename}")
        elif TOP_LEVEL.findall(path.read_text(encoding="utf-8-sig")) != [Path(filename).stem]:
            failures.append(f"inherited situation adapter lost its registry key: {filename}")
    custom_ids: set[str] = set()
    for path in SITUATION_DIR.glob("antq*.txt"):
        custom_ids.update(TOP_LEVEL.findall(path.read_text(encoding="utf-8-sig")))
    if len(custom_ids) != 43:
        failures.append(f"expected 43 ancient situations, found {len(custom_ids)}")

    ducat_keys = set(installed_ducat_entries())
    expected_currency = currency_entries()
    reference: bytes | None = None
    for client in CLIENTS:
        path = LOC_ROOT / client / f"antq_r5_visible_unions_l_{client}.yml"
        expected = loc_bytes(client)
        if not path.is_file() or path.read_bytes() != expected:
            failures.append(f"stale Round 5 localization mirror: {path}")
        normalized = expected.replace(f"l_{client}:".encode(), b"l_CLIENT:")
        if reference is None:
            reference = normalized
        elif normalized != reference:
            failures.append(f"client localization diverges: {client}")
        loc = effective_mod_loc(client)
        missing_currency = sorted((ducat_keys | {"gold", "game_concept_gold", "game_concept_gold_desc"}) - set(loc))
        if missing_currency:
            failures.append(f"{client}: missing Wealth overrides {missing_currency}")
        if any(re.search(r"\bducats?\b", loc[key], re.IGNORECASE) for key in expected_currency):
            failures.append(f"{client}: Ducats survives a Wealth override")
        for situation in custom_ids:
            if situation not in loc or f"{situation}_desc" not in loc:
                failures.append(f"{client}: missing situation title/description for {situation}")
        for disease in (*DISEASES, MALARIA):
            if loc.get(disease.key) != disease.name or loc.get(f"{disease.key}_desc") != disease.description:
                failures.append(f"{client}: stale disease localization for {disease.key}")
    if failures:
        raise ValueError("\n  - ".join(["Round 5 visible-union validation failed", *failures]))
    print(f"r5_visible_unions: PASS (7 diseases; 22 inert adapters; 43 ancient situations; {len(ducat_keys)} Wealth overrides; 11 clients)")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.write:
        write()
    if args.check or not args.write:
        validate()
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, UnicodeError, ValueError) as exc:
        print(f"r5_visible_unions: FAIL\n  - {exc}", file=sys.stderr)
        raise SystemExit(1)
