#!/usr/bin/env python3
"""Generate and validate complete producer-to-consumer ancient economy chains."""

from __future__ import annotations

import argparse
import csv
import re
from collections import Counter, defaultdict
from io import StringIO
from pathlib import Path

from economy_chains import (
    PACKAGE_GOODS,
    PACKAGE_NAMES,
    construction_package,
    institutional_upkeep,
)
from goods_integration import bindings
from m5_regional_buildings import FAMILY_MACRO_RESTRICTIONS, PRODUCTION_RECIPES
from s2_global_settlements import REGION_MACRO


ROOT = Path(__file__).resolve().parents[1]
ACTIVE = ROOT / "docs/m5/active_goods_audit.csv"
CUSTOM = ROOT / "docs/m5/custom_goods.csv"
RGO_AUDIT = ROOT / "docs/m5/global_rgo_audit.csv"
ADVANCES = ROOT / "docs/m8/advances.csv"
MARKETS = ROOT / "docs/m5/markets.csv"
POP_DEMAND = ROOT / "in_game/common/goods_demand/pop_demands.txt"
DEMAND_OUTPUT = ROOT / "in_game/common/goods_demand/01_antiquitas_s2_construction_demands.txt"
LEDGER_OUTPUT = ROOT / "docs/s2/economy_chain_bindings.csv"
REPORT_OUTPUT = ROOT / "docs/s2/ECONOMY_CHAINS.md"
LOC_ROOT = ROOT / "main_menu/localization"
LANGUAGES = (
    "english", "french", "german", "spanish", "polish", "russian",
    "braz_por", "simp_chinese", "japanese", "korean", "turkish",
)
BUILDING_INPUTS = (
    (
        ROOT / "docs/m5/regional_building_families.csv",
        ROOT / "in_game/common/building_types/00_antiquitas_regional_buildings.txt",
    ),
    (
        ROOT / "docs/m5/roman_buildings.csv",
        ROOT / "in_game/common/building_types/00_antiquitas_roman_buildings.txt",
    ),
    (
        ROOT / "docs/m5/ancient_building_replacements.csv",
        ROOT / "in_game/common/building_types/00_antiquitas_adapter_replacements.txt",
    ),
)
SEED_INPUTS = (
    (ROOT / "docs/m5/regional_building_seeds.csv", "family"),
    (ROOT / "docs/m5/food_building_seeds.csv", "family"),
    (ROOT / "docs/m5/s2_britain_ireland_building_seeds.csv", "families"),
)
LEDGER_FIELDS = (
    "building", "category", "package", "productive", "produced",
    "upkeep_additions", "source", "confidence",
)


def rows(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        return [
            {key: str(value or "").strip() for key, value in row.items() if key}
            for row in csv.DictReader(handle)
            if row
        ]


def goods_field(value: str) -> set[str]:
    return {
        item.partition("=")[0].strip()
        for item in value.split(";")
        if item.strip()
    }


def top_level_blocks(text: str) -> dict[str, str]:
    result: dict[str, str] = {}
    key = ""
    depth = 0
    collected: list[str] = []
    for line in text.splitlines():
        if depth == 0:
            match = re.fullmatch(r"([a-zA-Z0-9_]+)\s*=\s*\{", line.strip())
            if not match:
                continue
            key = match.group(1)
            collected = [line]
            depth = line.count("{") - line.count("}")
            continue
        collected.append(line)
        depth += line.count("{") - line.count("}")
        if depth == 0:
            result[key] = "\n".join(collected)
            key = ""
            collected = []
    return result


def render_demands() -> str:
    lines = [
        "# Generated by tools/s2_economy_chains.py --write.",
        "# Bounded ancient construction packages derived from installed demand syntax.",
        "",
    ]
    for package, package_goods in PACKAGE_GOODS.items():
        lines.append(f"{package} = {{")
        lines.extend(f"\t{good} = {amount}" for good, amount in package_goods)
        lines.extend(("\tcategory = building_construction", "}", ""))
    return "\n".join(lines)


def render_localization(language: str) -> str:
    lines = [
        f"l_{language}:",
        " # Generated S2 ancient construction-demand localization; English mirrored by design.",
    ]
    lines.extend(f' {key}: "{name}"' for key, name in PACKAGE_NAMES.items())
    return "\n".join(lines) + "\n"


def building_rows() -> tuple[list[dict[str, str]], dict[str, Path]]:
    combined: list[dict[str, str]] = []
    output_by_key: dict[str, Path] = {}
    for ledger, output in BUILDING_INPUTS:
        for row in rows(ledger):
            row["_ledger"] = str(ledger.relative_to(ROOT))
            combined.append(row)
            output_by_key[row["key"]] = output
    return combined, output_by_key


def render_ledger(items: list[dict[str, str]]) -> str:
    stream = StringIO(newline="")
    writer = csv.DictWriter(stream, fieldnames=LEDGER_FIELDS, lineterminator="\n")
    writer.writeheader()
    for row in sorted(items, key=lambda item: item["key"]):
        recipe = PRODUCTION_RECIPES.get(row["key"])
        package = construction_package(row["key"], row["category"])
        additions = institutional_upkeep(
            row["key"], row["category"], productive=bool(recipe),
        )
        writer.writerow(
            {
                "building": row["key"],
                "category": row["category"],
                "package": package,
                "productive": "yes" if recipe else "no",
                "produced": recipe[0] if recipe else "",
                "upkeep_additions": ";".join(
                    f"{good}={amount}" for good, amount in additions
                ),
                "source": row["source"],
                "confidence": row["confidence"],
            }
        )
    return stream.getvalue()


def population_goods() -> set[str]:
    blocks = top_level_blocks(POP_DEMAND.read_text(encoding="utf-8-sig"))
    block = blocks.get("pop_demand", "")
    return {
        match.group(1)
        for line in block.splitlines()
        if (match := re.fullmatch(r"\s*([a-zA-Z0-9_]+)\s*=\s*[-0-9.]+\s*", line))
    } - {"category"}


def macro_portfolios() -> dict[str, set[str]]:
    portfolios: dict[str, set[str]] = defaultdict(set)
    for row in rows(RGO_AUDIT):
        macro = REGION_MACRO.get(row["region"])
        if macro and row["ad1_good"]:
            portfolios[macro].add(row["ad1_good"])
    for path, family_field in SEED_INPUTS:
        for row in rows(path):
            macro = row["macro"]
            for family in row[family_field].split(";"):
                recipe = PRODUCTION_RECIPES.get(family.strip())
                if recipe:
                    portfolios[macro].add(recipe[0])
    return dict(portfolios)


def validate_and_report(
    items: list[dict[str, str]],
    output_by_key: dict[str, Path],
) -> tuple[str, dict[str, int]]:
    failures: list[str] = []
    if set(PACKAGE_NAMES) != set(PACKAGE_GOODS):
        failures.append(
            "construction package/localization registry drift: "
            f"missing_names={sorted(set(PACKAGE_GOODS) - set(PACKAGE_NAMES))} "
            f"orphan_names={sorted(set(PACKAGE_NAMES) - set(PACKAGE_GOODS))}"
        )
    active_rows = rows(ACTIVE)
    active = {row["good"] for row in active_rows}
    producers = {
        row["good"]
        for row in active_rows
        if int(row["rgo_locations"]) or int(row["productive_outputs"])
    }
    pop_goods = population_goods()
    if len(items) != 292 or len({row["key"] for row in items}) != 292:
        failures.append("economy-chain ledger must own 292 unique buildings")
    if len(PRODUCTION_RECIPES) != 155:
        failures.append(
            f"productive recipe contract changed from 155 to {len(PRODUCTION_RECIPES)}"
        )
    if active - producers:
        failures.append(f"active goods lack producers: {sorted(active - producers)}")

    package_goods = {
        good for package in PACKAGE_GOODS.values() for good, _amount in package
    }
    upkeep_goods: set[str] = set()
    package_counts: Counter[str] = Counter()
    service_count = 0
    output_blocks: dict[Path, dict[str, str]] = {}
    for _ledger, output in BUILDING_INPUTS:
        output_blocks[output] = top_level_blocks(output.read_text(encoding="utf-8-sig"))
    for row in items:
        key = row["key"]
        package = construction_package(key, row["category"])
        package_counts[package] += 1
        recipe = PRODUCTION_RECIPES.get(key)
        additions = institutional_upkeep(
            key, row["category"], productive=bool(recipe),
        )
        upkeep_goods.update(good for good, _amount in additions)
        service_count += not bool(recipe)
        block = output_blocks[output_by_key[key]].get(key, "")
        if f"\tconstruction_demand = {package}" not in block:
            failures.append(f"{key}: rendered construction package drift")
        for good, _amount in additions:
            if not re.search(rf"^\s+{re.escape(good)}\s*=", block, re.MULTILINE):
                failures.append(f"{key}: missing institutional upkeep good {good}")
    if service_count != 137:
        failures.append(f"institutional service contract changed from 137 to {service_count}")
    unknown_chain_goods = (package_goods | upkeep_goods) - active
    if unknown_chain_goods:
        failures.append(f"construction/upkeep uses inactive goods {sorted(unknown_chain_goods)}")

    consumers: dict[str, set[str]] = defaultdict(set)
    for good in pop_goods:
        consumers[good].add("population")
    for package in PACKAGE_GOODS.values():
        for good, _amount in package:
            consumers[good].add("construction")
    for good in upkeep_goods:
        consumers[good].add("institutional_upkeep")
    for _family, (_output, _amount, inputs) in PRODUCTION_RECIPES.items():
        for good, _input_amount in inputs:
            consumers[good].add("production_input")
    for row in items:
        for good in goods_field(row.get("maintenance", "")):
            consumers[good].add("building_maintenance")
    for binding in bindings():
        consumers[binding.good].add(binding.surface)
    integration_surfaces = {binding.surface for binding in bindings()}
    required_surfaces = {
        "law_modifier", "privilege_modifier", "decision_market",
        "event_market", "event_rgo", "unit_demand",
    }
    if required_surfaces - integration_surfaces:
        failures.append(
            f"economy graph lacks integration surfaces "
            f"{sorted(required_surfaces - integration_surfaces)}"
        )
    dead_consumers = active - consumers.keys()
    if dead_consumers:
        failures.append(f"active goods lack consumers: {sorted(dead_consumers)}")
    for _family, (output, _amount, inputs) in PRODUCTION_RECIPES.items():
        if output not in consumers:
            failures.append(f"recipe output {output} has no consumer")
        for good, _input_amount in inputs:
            if good not in producers:
                failures.append(f"recipe input {good} has no producer")

    portfolios = macro_portfolios()
    expected_macros = set(REGION_MACRO.values())
    if set(portfolios) != expected_macros:
        failures.append(
            f"regional portfolio coverage mismatch: "
            f"missing={sorted(expected_macros - portfolios.keys())}"
        )
    fingerprints: dict[frozenset[str], str] = {}
    for macro, goods in sorted(portfolios.items()):
        signature = frozenset(goods)
        if signature in fingerprints:
            failures.append(
                f"interchangeable regional portfolios: {fingerprints[signature]} and {macro}"
            )
        fingerprints[signature] = macro
        minimum_goods = 6 if macro == "Oceania" else 12
        if len(goods) < minimum_goods:
            failures.append(
                f"{macro}: only {len(goods)} opening economy goods; "
                f"minimum is {minimum_goods}"
            )

    regional_keys = {row["key"] for row in rows(BUILDING_INPUTS[0][0])}
    advance_unlocks = {
        token.partition("=")[2]
        for advance in rows(ADVANCES)
        for token in advance["unlocks"].split(";")
        if token.startswith("unlock_building=")
    }
    if regional_keys - advance_unlocks:
        failures.append(
            f"regional buildings lack advance gates: "
            f"{sorted(regional_keys - advance_unlocks)}"
        )
    market_rows = rows(MARKETS)
    if len(market_rows) < 40 or len({row["location"] for row in market_rows}) != len(market_rows):
        failures.append("market network must contain at least 40 unique locations")

    if failures:
        raise ValueError("\n".join(sorted(set(failures))))

    custom = {row["key"] for row in rows(CUSTOM)}
    cross_system = {
        good
        for good, surfaces in consumers.items()
        if surfaces - {"population", "building_maintenance", "production_input"}
    }
    report = [
        "# Economy Chains",
        "",
        "Generated by `tools/s2_economy_chains.py`.",
        "",
        f"- {len(active)} active goods have a producer and live consumer.",
        f"- {len(PRODUCTION_RECIPES)} calibrated recipes have live inputs and outputs.",
        f"- {len(items)} ancient buildings use {len(PACKAGE_GOODS)} construction packages.",
        f"- {service_count} non-production institutions receive bounded upkeep; "
        f"all production recipes remain unchanged.",
        f"- {len(cross_system & active)} goods also feed construction, upkeep, "
        "military, law, privilege, decision, or event surfaces.",
        f"- {len(regional_keys)} regional families are advance-gated; "
        f"{len(market_rows)} market nodes carry emergent trade.",
        f"- {len(FAMILY_MACRO_RESTRICTIONS)} specialty families have explicit "
        "production-geography bounds.",
        f"- {len(portfolios)} macro-economies have distinct opening portfolios.",
        "",
        "Construction assignments:",
        "",
    ]
    report.extend(
        f"- {PACKAGE_NAMES[package]}: {package_counts[package]} buildings."
        for package in PACKAGE_GOODS
    )
    report.extend(("", "Regional portfolios:", ""))
    report.extend(
        f"- {macro}: {len(goods)} goods."
        for macro, goods in sorted(portfolios.items())
    )
    report.extend(
        (
            "",
            "These are bounded market-scale product classes and demand links, not",
            "reconstructed quantities, issued rations, or uniform workshop bills.",
            "",
        )
    )
    metrics = {
        "active": len(active),
        "custom": len(custom),
        "buildings": len(items),
        "recipes": len(PRODUCTION_RECIPES),
        "services": service_count,
        "packages": len(PACKAGE_GOODS),
        "macros": len(portfolios),
        "cross_system": len(cross_system & active),
        "advance_gated": len(regional_keys),
        "markets": len(market_rows),
    }
    return "\n".join(report), metrics


def expected_outputs(
    items: list[dict[str, str]],
    report: str,
) -> dict[Path, tuple[str, str]]:
    outputs: dict[Path, tuple[str, str]] = {
        DEMAND_OUTPUT: (render_demands(), "utf-8-sig"),
        LEDGER_OUTPUT: (render_ledger(items), "utf-8-sig"),
        REPORT_OUTPUT: (report, "utf-8"),
    }
    for language in LANGUAGES:
        outputs[
            LOC_ROOT / language / f"antq_s2_economy_chains_l_{language}.yml"
        ] = (render_localization(language), "utf-8-sig")
    return outputs


def write_outputs(outputs: dict[Path, tuple[str, str]]) -> None:
    for path, (content, encoding) in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding=encoding, newline="\n")


def stale_outputs(outputs: dict[Path, tuple[str, str]]) -> list[Path]:
    stale: list[Path] = []
    for path, (content, encoding) in outputs.items():
        if not path.is_file() or path.read_text(encoding=encoding) != content:
            stale.append(path.relative_to(ROOT))
    return stale


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        items, output_by_key = building_rows()
        # Building generators must run before this tool so rendered bindings can
        # be checked against the shared package mapping.
        report, metrics = validate_and_report(items, output_by_key)
        outputs = expected_outputs(items, report)
        if args.write:
            write_outputs(outputs)
        stale = stale_outputs(outputs)
        if stale:
            raise ValueError(f"stale or missing outputs: {stale}")
    except (OSError, ValueError, csv.Error) as exc:
        print(f"s2_economy_chains: FAIL\n  - {exc}")
        return 1
    print(
        "s2_economy_chains: PASS "
        f"({metrics['active']} goods; {metrics['recipes']} recipes; "
        f"{metrics['buildings']} buildings; {metrics['services']} service-upkeep; "
        f"{metrics['packages']} construction packages; {metrics['macros']} macro portfolios)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
