#!/usr/bin/env python3
"""Validate and render cross-system ancient-goods bindings."""

from __future__ import annotations

import argparse
import csv
import json
import re
from collections import Counter, defaultdict
from pathlib import Path

from goods_integration import ROOT, bindings, modifier_name


OUTPUT = ROOT / "in_game/common/goods_demand/00_antiquitas_s2_goods_demands.txt"
REPORT = ROOT / "docs/s2/GOODS_INTEGRATION.md"
LOC_ROOT = ROOT / "main_menu/localization"
ACTIVE_GOODS = ROOT / "docs/m5/active_goods_audit.csv"
VANILLA_GOODS = ROOT / "docs/vanilla_symbols/good.json"
LAW_OPTIONS = ROOT / "docs/m6/ancient_law_options.csv"
PRIVILEGES = (
    ROOT / "docs/m6/privileges.csv",
    ROOT / "docs/m6/estate_order_privileges.csv",
)
DECISIONS = ROOT / "docs/m11/decisions.csv"
TIMELINE = ROOT / "docs/timeline.csv"
UNIT_LEDGER = ROOT / "docs/m7/units.csv"
NUMBER = re.compile(r"^(?:\d+(?:\.\d+)?|\.\d+)$")
TOKEN = re.compile(r"^[a-z][a-z0-9_]*$")
SURFACES = {
    "law_modifier", "privilege_modifier", "decision_market",
    "event_market", "event_rgo", "unit_demand",
}
MARKET_VALUES = {
    "market_goods_weak_gain", "market_goods_mild_gain",
    "market_goods_severe_gain",
    "market_goods_weak_loss", "market_goods_mild_loss",
    "market_goods_severe_loss",
}
LANGUAGES = (
    "english", "french", "german", "spanish", "polish", "russian",
    "braz_por", "simp_chinese", "japanese", "korean", "turkish",
)
PACKAGE_NAMES = {
    "light_infantry": "Light Infantry",
    "heavy_infantry": "Heavy Infantry",
    "light_cavalry": "Light Cavalry",
    "heavy_cavalry": "Heavy Cavalry",
    "horse_archer": "Horse-Archer",
    "camel": "Camel Troop",
    "elephant": "Elephant Corps",
    "galley": "Galley",
    "light_ship": "Light Ship",
    "transport": "Transport Ship",
    "heavy_ship": "Heavy Ship",
}


def csv_keys(path: Path, field: str) -> set[str]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        return {
            (row[field] or "").strip()
            for row in csv.DictReader(handle)
            if (row[field] or "").strip()
        }


def active_goods() -> set[str]:
    return set(json.loads(VANILLA_GOODS.read_text(encoding="utf-8-sig"))) | csv_keys(
        ACTIVE_GOODS, "good"
    )


def demand_groups() -> dict[str, list[tuple[str, str]]]:
    groups: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for row in bindings():
        if row.surface == "unit_demand":
            groups[row.target].append((row.good, row.value))
    return dict(groups)


def demand_category(target: str) -> str:
    if target.endswith("_construction"):
        suffix = "ship_construction" if target.startswith(
            ("galley_", "light_ship_", "transport_", "heavy_ship_")
        ) else "regiment_construction"
    elif target.endswith("_maintenance"):
        suffix = "ship_maintenance" if target.startswith(
            ("galley_", "light_ship_", "transport_", "heavy_ship_")
        ) else "regiment_maintenance"
    else:
        raise ValueError(f"unit demand target lacks cost phase: {target}")
    return suffix


def render_demands() -> str:
    lines = [
        "# Generated by tools/s2_goods_integration.py from docs/s2/goods_integration.csv.",
        "# Values are bounded supply classes, not reconstructed universal rations.",
        "",
    ]
    for target, rows in sorted(demand_groups().items()):
        lines.append(f"antq_{target} = {{")
        lines.extend(f"\t{good} = {value}" for good, value in rows)
        lines.extend((f"\tcategory = {demand_category(target)}", "}", ""))
    return "\n".join(lines)


def render_report() -> str:
    counts = Counter(row.surface for row in bindings())
    demand_packages = len(demand_groups()) // 2
    connected_goods = len({row.good for row in bindings()})
    return "\n".join((
        "# Goods integration",
        "",
        "Generated from `docs/s2/goods_integration.csv`.",
        "",
        f"- {len(bindings())} reviewed bindings; {connected_goods} goods.",
        f"- {counts['law_modifier']} law and {counts['privilege_modifier']} privilege effects.",
        f"- {counts['decision_market']} decision and "
        f"{counts['event_market'] + counts['event_rgo']} dated-event effects.",
        f"- {demand_packages} complete unit provisioning packages "
        f"({counts['unit_demand']} demand lines).",
        "",
    ))


def render_localization(language: str) -> str:
    lines = [f"l_{language}:"]
    for package, name in PACKAGE_NAMES.items():
        lines.append(
            f' antq_{package}_construction: "Ancient {name} Equipment"'
        )
        lines.append(
            f' antq_{package}_maintenance: "Ancient {name} Provisions"'
        )
    return "\n".join(lines) + "\n"


def expected_outputs() -> dict[Path, str]:
    outputs = {OUTPUT: render_demands(), REPORT: render_report()}
    for language in LANGUAGES:
        outputs[
            LOC_ROOT / language / f"antq_s2_goods_integration_l_{language}.yml"
        ] = render_localization(language)
    return outputs


def validate() -> None:
    failures: list[str] = []
    rows = bindings()
    goods = active_goods()
    laws = csv_keys(LAW_OPTIONS, "option")
    privileges = set().union(*(csv_keys(path, "key") for path in PRIVILEGES))
    decisions = csv_keys(DECISIONS, "id")
    events = csv_keys(TIMELINE, "key")
    unit_bases = {
        "light_infantry", "heavy_infantry", "light_cavalry", "heavy_cavalry",
        "horse_archer", "camel", "elephant", "galley", "light_ship",
        "transport", "heavy_ship",
    }
    seen: set[tuple[str, str, str, str]] = set()
    for row in rows:
        identity = (row.surface, row.target, row.good, row.mechanic)
        if identity in seen:
            failures.append(f"duplicate binding {identity}")
        seen.add(identity)
        if row.surface not in SURFACES:
            failures.append(f"{row.target}: unsupported surface {row.surface}")
        if not TOKEN.fullmatch(row.target) or not TOKEN.fullmatch(row.good):
            failures.append(f"{row.surface}: unsafe target/good {row.target}/{row.good}")
        if row.good not in goods:
            failures.append(f"{row.surface}/{row.target}: inactive good {row.good}")
        if row.confidence not in {"secure", "contested"} or not row.source or len(row.note) < 35:
            failures.append(f"{row.surface}/{row.target}/{row.good}: weak provenance")
        if row.surface in {"law_modifier", "privilege_modifier"}:
            if row.mechanic not in {"output_modifier", "pop_demand"} or not NUMBER.fullmatch(row.value):
                failures.append(f"{row.surface}/{row.target}: invalid modifier binding")
            else:
                key = modifier_name(row)
                mod_text = (
                    ROOT / "main_menu/common/modifier_type_definitions/00_antiquitas_goods.txt"
                ).read_text(encoding="utf-8-sig")
                game_text = (
                    Path(json.loads((ROOT / "config/local_paths.json").read_text(
                        encoding="utf-8-sig"
                    ))["game_dir"])
                    / "game/main_menu/common/modifier_type_definitions/00_modifier_types.txt"
                ).read_text(encoding="utf-8-sig")
                if f"{key}=" not in mod_text and f"{key}=" not in game_text:
                    failures.append(f"{row.surface}/{row.target}: missing modifier {key}")
        if row.surface == "law_modifier" and row.target not in laws:
            failures.append(f"law binding targets unknown option {row.target}")
        if row.surface == "privilege_modifier" and row.target not in privileges:
            failures.append(f"privilege binding targets unknown privilege {row.target}")
        if row.surface == "decision_market":
            if row.target not in decisions or row.mechanic != "threshold_supply":
                failures.append(f"invalid decision binding {row.target}")
            else:
                pieces = row.value.split("|")
                if len(pieces) != 2 or not NUMBER.fullmatch(pieces[0]) or pieces[1] not in MARKET_VALUES:
                    failures.append(f"decision {row.target} has invalid threshold/supply")
        if row.surface.startswith("event_") and row.target not in events:
            failures.append(f"event binding targets unknown current {row.target}")
        if row.surface == "event_market" and (
            row.mechanic != "supply" or row.value not in MARKET_VALUES
        ):
            failures.append(f"event {row.target} has invalid market effect")
        if row.surface == "event_rgo" and (
            row.mechanic != "change_raw_material" or row.value not in goods
        ):
            failures.append(f"event {row.target} has invalid RGO transition")
        if row.surface == "unit_demand" and (
            row.mechanic != "demand" or not NUMBER.fullmatch(row.value)
        ):
            failures.append(f"unit demand {row.target}/{row.good} is invalid")
    groups = demand_groups()
    expected_groups = {
        f"{base}_{phase}"
        for base in unit_bases
        for phase in ("construction", "maintenance")
    }
    if set(groups) != expected_groups:
        failures.append(
            "unit demand packages differ: missing "
            f"{sorted(expected_groups - set(groups))}; extra {sorted(set(groups) - expected_groups)}"
        )
    if len(rows) < 120:
        failures.append("goods integration must retain at least 120 reviewed bindings")
    if len(csv_keys(UNIT_LEDGER, "key")) < 50:
        failures.append("unit roster unexpectedly shallow")
    for path, expected in expected_outputs().items():
        if not path.is_file():
            failures.append(f"missing generated {path.relative_to(ROOT)}")
        elif path.read_text(encoding="utf-8-sig") != expected:
            failures.append(f"stale generated {path.relative_to(ROOT)}")
    if failures:
        raise ValueError("\n".join(failures))


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        if args.write:
            for path, content in expected_outputs().items():
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8-sig", newline="\n")
                print(f"s2_goods_integration: wrote {path.relative_to(ROOT)}")
        validate()
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"s2_goods_integration: FAIL\n  - {exc}")
        return 1
    counts = Counter(row.surface for row in bindings())
    print(
        "s2_goods_integration: PASS "
        f"({len(bindings())} bindings; {len(demand_groups()) // 2} provisioning "
        f"packages; " + ", ".join(f"{key}={counts[key]}" for key in sorted(counts)) + ")"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
