#!/usr/bin/env python3
"""Generate the lower-yield, ecology-gated ancient Cultivator building family."""
from __future__ import annotations

import argparse, csv, hashlib, json, subprocess, sys
from io import StringIO
from pathlib import Path
from PIL import Image, ImageDraw, ImageFilter, ImageOps
from m5_regional_buildings import good_prices

ROOT = Path(__file__).resolve().parents[1]
CSV = ROOT/"docs/m5/cultivator_buildings.csv"
OUT = ROOT/"in_game/common/building_types/00_antiquitas_cultivator_buildings.txt"
AVAIL = ROOT/"docs/m5/cultivator_availability.csv"
REPORT = ROOT/"docs/m5/CULTIVATOR_SYSTEM.md"
SHEETS = ROOT/"assets_queue/generated_sources/cultivator_buildings"
MASTERS = ROOT/"assets_queue/generated/cultivator_buildings"
ICONS = ROOT/"main_menu/gfx/interface/icons/buildings"
CONTACT = ROOT/"docs/m5/CULTIVATOR_ICON_CONTACT.png"
DDS = ROOT/"tools/dds.py"
LANGS=("english","french","german","spanish","polish","russian","braz_por","simp_chinese","japanese","korean","turkish")
FIELDS=("key","name","good","output","climates","topographies","vegetations","regions","water","max","source","icon_subject")
CELLS=("top_left","top_right","bottom_left","bottom_right")
CULTIVABLE_GOODS={
    "wheat","millet","antq_barley","rice","maize","legumes","fruit","olives",
    "antq_dates","antq_tree_nuts","antq_sesame","fiber_crops","cotton","dyes",
    "sugar","tea","medicaments","incense","antq_papyrus","antq_coconuts",
    "cocoa","tobacco","wine","saffron","pepper","cloves","chili","potato",
    "beeswax","silk","wool","livestock","horses","antq_camels",
}
REVIEWED_EXCLUSIONS={
    "coffee":"documented beverage cultivation is post-campaign",
    "antq_silphium":"extremely narrow Cyrenaican resource, not a transplantable tall-play crop",
}

def parts(v): return tuple(x for x in v.split("|") if x)
def load():
    with CSV.open(encoding="utf-8-sig",newline="") as f:
        r=csv.DictReader(f)
        if tuple(r.fieldnames or ()) != FIELDS: raise ValueError("cultivator ledger schema drift")
        rows=[{k:(v or "").strip() for k,v in x.items()} for x in r]
    if len(rows)<24 or len(rows)%4: raise ValueError("cultivators require >=24 entries and complete four-up sheets")
    return rows

def ors(trigger, values, prefix="", indent="\t\t"):
    if values==("ALL",): return []
    return [f"{indent}OR = {{",*(f"{indent}\t{trigger} = {prefix}{v}" for v in values),f"{indent}}}"]

def gate(r):
    x=ors("climate",parts(r["climates"]))+ors("topography",parts(r["topographies"]))+ors("vegetation",parts(r["vegetations"]))+ors("region",parts(r["regions"]),"region:")
    water=r["water"]
    if water=="river": x+=["\t\thas_river = yes"]
    elif water=="coast": x+=["\t\tis_port = yes"]
    elif water=="humid": x+=["\t\tOR = {","\t\t\tclimate = tropical","\t\t\tclimate = subtropical","\t\t\thas_river = yes","\t\t}"]
    elif water=="river_or_arid": x+=["\t\tOR = {","\t\t\thas_river = yes","\t\t\tclimate = arid","\t\t}"]
    elif water!="none": raise ValueError(f"unknown water gate {water}")
    return x

def building_text(rows):
    prices=good_prices()
    o=["# Generated by tools/s3_cultivator_buildings.py --write.","# Marginal peasant cultivation; native RGOs remain superior.",""]
    for r in rows:
        k=r["key"]; cap=int(r["max"])
        o += [f"{k} = {{","\taudio_tier = 1","\tis_foreign = no","\tpop_type = peasants","\tcategory = rgo_building_category",
              "\temployment_size = rural_peasant_produce_employment","\tstartup_ramp_target = rural_startup_ramp_target",
              "\trural_settlement = yes","\ttown = yes","\tcity = yes","\tmegalopolis = yes","\tbuild_time = rural_build_time",
              "\timportant_for_AI = yes","\tlocation_potential = {",*gate(r),"\t}","\tmax_levels = {","\t\tvalue = 1",
              "\t\tif = {","\t\t\tlimit = { vegetation = farmland }","\t\t\tadd = 1","\t\t}"]
        if cap==3: o += ["\t\tif = {","\t\t\tlimit = { has_river = yes }","\t\t\tadd = 1","\t\t}"]
        gross=prices[r["good"]]*float(r["output"]); target=gross/1.2
        # Labor remains the limiting factor; material upkeep is calibrated
        # per good to the engine's required 20% default-price margin.
        tools=target*.20/prices["tools"]; lumber=target*.30/prices["lumber"]; livestock=target*.50/prices["livestock"]
        o += [f"\t\tmin = {cap}","\t}","\tunique_production_methods = {",f"\t\t{k}_maintenance = {{",
              f"\t\t\ttools = {tools:.4f}",f"\t\t\tlumber = {lumber:.4f}",f"\t\t\tlivestock = {livestock:.4f}",f"\t\t\tproduced = {r['good']}",
              f"\t\t\toutput = {r['output']}","\t\t\tdebug_max_profit = rural_profit_margin",
              "\t\t\tcategory = building_maintenance","\t\t}","\t}","\tmodifier = {","\t\tlocal_food_capacity = 20",
              "\t\tlocal_peasants_estate_power = 0.05","\t}","\tconstruction_demand = farm_constructions",
              "\tcustom_tags = { antq_cultivator }","}",""]
    return "\n".join(o)

def loc_text(lang,rows):
    o=[f"l_{lang}:"]
    for r in rows:
        o += [f' {r["key"]}:0 "{r["name"]}"',
              f' {r["key"]}_desc:0 "Peasant cultivators extend {r["name"].lower()} beyond native resource sites at lower yield, within strict ancient climate and landscape limits."',
              f' {r["key"]}_maintenance:0 "{r["name"]} Upkeep"']
    return "\ufeff"+"\n".join(o)+"\n"

def sheet_cell(i): return f"cultivator_sheet_{i//4+1:02d}.png",CELLS[i%4]
def box(size,cell):
    w,h=size
    if w!=h or w<1024 or w%2: raise ValueError(f"bad four-up sheet size {size}")
    q=CELLS.index(cell); x=q%2; y=q//2; s=w//2
    return x*s,y*s,(x+1)*s,(y+1)*s
def convert(src,dst):
    subprocess.run([sys.executable,str(DDS),"convert",str(src),str(dst),"--compression","dxt5"],cwd=ROOT,check=True,stdout=subprocess.DEVNULL)

def art(rows):
    MASTERS.mkdir(parents=True,exist_ok=True); ICONS.mkdir(parents=True,exist_ok=True)
    opened={}; previews=[]
    try:
        for i,r in enumerate(rows):
            sheet,cell=sheet_cell(i); p=SHEETS/sheet
            if not p.is_file(): continue
            if sheet not in opened: opened[sheet]=Image.open(p).convert("RGBA")
            icon=ImageOps.fit(opened[sheet].crop(box(opened[sheet].size,cell)),(128,128),method=Image.Resampling.LANCZOS)
            # Active building icons use the installed circular dark-navy field.
            # Keep the crop legible in the centre and reserve a clean UI ring.
            field=Image.new("RGBA",(128,128),(16,25,43,255))
            inner=Image.new("L",(128,128),0)
            ImageDraw.Draw(inner).ellipse((15,15,112,112),fill=255)
            field.paste(icon,(0,0),inner.filter(ImageFilter.GaussianBlur(.7)))
            icon=field
            mask=Image.new("L",(128,128),0); ImageDraw.Draw(mask).ellipse((3,3,124,124),fill=255)
            icon.putalpha(mask.filter(ImageFilter.GaussianBlur(.7)))
            master=MASTERS/f"{r['key']}.png"; icon.save(master); convert(master,ICONS/f"{r['key']}.dds"); previews.append((r["key"],icon))
    finally:
        for im in opened.values(): im.close()
    if len(previews)==len(rows):
        height=((len(rows)+5)//6)*205
        canvas=Image.new("RGBA",(1080,height),(16,25,43,255)); d=ImageDraw.Draw(canvas)
        for i,(k,im) in enumerate(previews):
            x=(i%6)*180+10; y=(i//6)*205+3
            canvas.alpha_composite(im.resize((160,160),Image.Resampling.NEAREST),(x,y)); d.text((x,y+164),k[10:31],fill="white")
        canvas.convert("RGB").save(CONTACT)

def availability(rows):
    s=StringIO(newline=""); w=csv.writer(s,lineterminator="\n")
    w.writerow(("building","good","climates","topographies","vegetations","regions","water_gate","max_levels","output","native_rgo_superior"))
    for r in rows: w.writerow((r["key"],r["good"],len(parts(r["climates"])),len(parts(r["topographies"])),len(parts(r["vegetations"])),len(parts(r["regions"])),r["water"],r["max"],r["output"],"yes"))
    return s.getvalue()

def write(rows):
    OUT.write_text(building_text(rows),encoding="utf-8-sig",newline="\n")
    for lang in LANGS:
        p=ROOT/f"main_menu/localization/{lang}/antq_s3_cultivators_l_{lang}.yml"; p.write_text(loc_text(lang,rows),encoding="utf-8",newline="\n")
    AVAIL.write_text(availability(rows),encoding="utf-8-sig",newline="")
    REPORT.write_text(
        f"# Cultivator System\n\n"
        f"- {len(rows)} lower-yield peasant buildings from {len(rows)//4} four-up art sheets.\n"
        f"- {len(CULTIVABLE_GOODS)} reviewed cultivable goods covered; coffee and silphium remain explicit historical exclusions.\n"
        f"- Exact climate, topography, vegetation, region, river, and coast gates.\n"
        f"- Hard caps 2-3; outputs 0.18-0.38 versus native RGO production.\n",
        encoding="utf-8",
    )
    art(rows)

def check(rows):
    failures=[]; regions=set(json.loads((ROOT/"docs/vanilla_symbols/regions.json").read_text()))
    goods=set(json.loads((ROOT/"docs/vanilla_symbols/good.json").read_text()))
    with (ROOT/"docs/m5/custom_goods.csv").open(encoding="utf-8-sig",newline="") as f: goods.update(x["key"] for x in csv.DictReader(f))
    if len({r["key"] for r in rows})!=len(rows): failures.append("duplicate keys")
    covered={r["good"] for r in rows}
    if covered != CULTIVABLE_GOODS:
        failures.append(
            f"cultivable-good coverage drift: missing={sorted(CULTIVABLE_GOODS-covered)} "
            f"unexpected={sorted(covered-CULTIVABLE_GOODS)}"
        )
    if set(REVIEWED_EXCLUSIONS) & covered:
        failures.append("reviewed historical exclusions became cultivators")
    if not OUT.is_file() or OUT.read_text(encoding="utf-8-sig")!=building_text(rows): failures.append("building output stale")
    if not AVAIL.is_file() or AVAIL.read_text(encoding="utf-8-sig")!=availability(rows): failures.append("availability ledger stale")
    hashes={}
    for i,r in enumerate(rows):
        if r["good"] not in goods: failures.append(f"unknown good {r['good']}")
        if not .18<=float(r["output"])<=.40: failures.append(f"yield not marginal {r['key']}")
        unknown=set(parts(r["regions"]))-regions-{"ALL"}
        if unknown: failures.append(f"unknown regions {r['key']}: {unknown}")
        for p in (SHEETS/sheet_cell(i)[0],MASTERS/f"{r['key']}.png",ICONS/f"{r['key']}.dds"):
            if not p.is_file(): failures.append(f"missing direct art {p.relative_to(ROOT)}")
        p=ICONS/f"{r['key']}.dds"
        if p.is_file():
            h=hashlib.sha256(p.read_bytes()).hexdigest()
            if h in hashes: failures.append(f"art alias {hashes[h]} / {r['key']}")
            hashes[h]=r["key"]
    if not CONTACT.is_file(): failures.append("contact sheet missing")
    for lang in LANGS:
        p=ROOT/f"main_menu/localization/{lang}/antq_s3_cultivators_l_{lang}.yml"
        if not p.is_file() or p.read_text(encoding="utf-8-sig")!=loc_text(lang,rows).lstrip("\ufeff"): failures.append(f"localization stale {lang}")
    if failures: raise ValueError("\n".join(failures))

def main():
    p=argparse.ArgumentParser(); p.add_argument("--write",action="store_true"); p.add_argument("--check",action="store_true"); a=p.parse_args()
    if a.write==a.check: p.error("choose exactly one")
    try:
        rows=load()
        if a.write: write(rows)
        check(rows)
    except (OSError,ValueError,csv.Error,subprocess.CalledProcessError) as e:
        print(f"s3_cultivator_buildings: FAIL\n  - {e}"); return 1
    print(f"s3_cultivator_buildings: PASS ({len(rows)} ecology-gated peasant cultivators)"); return 0
if __name__=="__main__": raise SystemExit(main())
