#!/usr/bin/env python3
"""Generate the lower-yield, ecology-gated ancient Cultivator building family."""
from __future__ import annotations

import argparse, csv, hashlib, json, subprocess, sys
from io import StringIO
from pathlib import Path
from PIL import Image, ImageDraw, ImageFilter, ImageOps
from economy_chains import (
    AI_CAPITAL_RESERVE_MONTHS,
    AI_CAPITAL_SETTLEMENT_DATE,
    AI_CAPITAL_SURPLUS_DIVISOR,
    CULTIVATOR_CONSTRUCTION_PACKAGE,
    OPENING_CUSTOM_CULTIVATORS,
    PACKAGE_GOODS,
    ai_capital_affordability_trigger,
)
from m5_regional_buildings import good_prices, owner_regions
from s2_global_settlements import REGION_MACRO

ROOT = Path(__file__).resolve().parents[1]
CSV = ROOT/"docs/m5/cultivator_buildings.csv"
OUT = ROOT/"in_game/common/building_types/00_antiquitas_cultivator_buildings.txt"
METHODS = ROOT/"in_game/common/production_methods/00_antiquitas_cultivator_methods.txt"
METHOD_LEDGER = ROOT/"docs/m5/cultivator_production_methods.csv"
AVAIL = ROOT/"docs/m5/cultivator_availability.csv"
SEED_LEDGER = ROOT/"docs/m5/cultivator_opening_seeds.csv"
RGO_ANCHORS = ROOT/"docs/m5/rgo_anchors.csv"
REPORT = ROOT/"docs/m5/CULTIVATOR_SYSTEM.md"
SEED_FIELDS = ("key","family","location","macro","source","confidence","note")
SEED_CAP_PER_GOOD = 24
SHEETS = ROOT/"assets_queue/generated_sources/cultivator_buildings"
MASTERS = ROOT/"assets_queue/generated/cultivator_buildings"
ICONS = ROOT/"main_menu/gfx/interface/icons/buildings"
CONTACT = ROOT/"docs/m5/CULTIVATOR_ICON_CONTACT.png"
DDS = ROOT/"tools/dds.py"
LANGS=("english","french","german","spanish","polish","russian","braz_por","simp_chinese","japanese","korean","turkish")
FIELDS=("key","name","good","output","climates","topographies","vegetations","regions","water","max","source","icon_subject")
CELLS=("top_left","top_right","bottom_left","bottom_right")
METHOD_TIERS=(
    ("maintenance", "Established Practice", 1.00, 1.20, "opening", "shared"),
    ("managed", "Managed Rotation", 1.12, 1.20, "age_2_renaissance", "shared"),
    ("intensive", "Intensive Husbandry", 1.25, 1.20, "age_4_reformation", "shared"),
    ("specialized", "Regional Specialization", 1.35, 1.20, "age_6_revolutions", "shared"),
)
CULTIVABLE_GOODS={
    "wheat","millet","antq_barley","rice","maize","legumes","fruit","olives",
    "antq_dates","antq_tree_nuts","antq_sesame","fiber_crops","cotton","dyes",
    "sugar","tea","medicaments","incense","antq_papyrus","antq_coconuts",
    "cocoa","tobacco","wine","saffron","pepper","cloves","chili","potato",
    "beeswax","silk","wool","livestock","horses","antq_camels",
}
REVIEWED_EXCLUSIONS={
    "coffee":"documented beverage cultivation is post-campaign",
    "antq_silphium":"extremely narrow Cyrenaican resource, not a transplantable tall-play crop",
}

def parts(v): return tuple(x for x in v.split("|") if x)
def load():
    with CSV.open(encoding="utf-8-sig",newline="") as f:
        r=csv.DictReader(f)
        if tuple(r.fieldnames or ()) != FIELDS: raise ValueError("cultivator ledger schema drift")
        rows=[{k:(v or "").strip() for k,v in x.items()} for x in r]
    if len(rows)<24 or len(rows)%4: raise ValueError("cultivators require >=24 entries and complete four-up sheets")
    return rows

def ors(trigger, values, prefix="", indent="\t\t"):
    if values==("ALL",): return []
    return [f"{indent}OR = {{",*(f"{indent}\t{trigger} = {prefix}{v}" for v in values),f"{indent}}}"]

def gate(r):
    x=ors("climate",parts(r["climates"]))+ors("topography",parts(r["topographies"]))+ors("vegetation",parts(r["vegetations"]))+ors("region",parts(r["regions"]),"region:")
    water=r["water"]
    if water=="river": x+=["\t\thas_river = yes"]
    elif water=="coast": x+=["\t\tis_port = yes"]
    elif water=="humid": x+=["\t\tOR = {","\t\t\tclimate = tropical","\t\t\tclimate = subtropical","\t\t\thas_river = yes","\t\t}"]
    elif water=="river_or_arid": x+=["\t\tOR = {","\t\t\thas_river = yes","\t\t\tclimate = arid","\t\t}"]
    elif water!="none": raise ValueError(f"unknown water gate {water}")
    return x

def building_text(rows):
    o=["# Generated by tools/s3_cultivator_buildings.py --write.","# Marginal peasant cultivation; native RGOs remain superior.",""]
    for r in rows:
        k=r["key"]; cap=int(r["max"])
        o += [f"{k} = {{","\taudio_tier = 1","\tis_foreign = no","\tpop_type = peasants","\tcategory = rgo_building_category",
              "\temployment_size = rural_peasant_produce_employment","\tstartup_ramp_target = rural_startup_ramp_target",
              "\trural_settlement = yes","\ttown = yes","\tcity = yes","\tmegalopolis = yes","\tbuild_time = rural_build_time",
              "\tcountry_potential = {",*ai_capital_affordability_trigger(),"\t}","\tallow = {","\t\talways = yes","\t}",
              "\tlocation_potential = {",*gate(r),"\t}","\tmax_levels = {","\t\tvalue = 1",
              "\t\tif = {","\t\t\tlimit = { vegetation = farmland }","\t\t\tadd = 1","\t\t}"]
        if cap==3: o += ["\t\tif = {","\t\t\tlimit = { has_river = yes }","\t\t\tadd = 1","\t\t}"]
        o += [f"\t\tmin = {cap}","\t}","\tpossible_production_methods = {"]
        o += [f"\t\t{k}_{suffix}" for suffix, _name, _mult, _margin, _age, _profile in METHOD_TIERS]
        o += ["\t}","\tmodifier = {","\t\tlocal_food_capacity = 20",
              "\t\tlocal_peasants_estate_power = 0.05","\t}",f"\tconstruction_demand = {CULTIVATOR_CONSTRUCTION_PACKAGE}",
              "\tcustom_tags = { antq_cultivator }","}",""]
    return "\n".join(o)

def method_rows(rows):
    result=[]
    for r in rows:
        for suffix,name,mult,margin,age,profile in METHOD_TIERS:
            result.append({
                "key":f"{r['key']}_{suffix}", "building":r["key"], "tier":suffix,
                "name":name, "good":r["good"], "base_output":r["output"],
                "output_multiplier":f"{mult:.2f}", "output":f"{float(r['output'])*mult:.4f}",
                "default_margin":f"{margin:.2f}", "unlock_age":age,
                "profile":profile, "source":r["source"],
            })
    return result

def production_method_text(rows):
    prices=good_prices(); o=[
        "# Generated by tools/s3_cultivator_buildings.py --write.",
        "# Four bounded agronomic stages per family; native RGOs remain superior per level.", "",
    ]
    for m in method_rows(rows):
        gross=prices[m["good"]]*float(m["output"]); target=gross/float(m["default_margin"])
        # Later practice substitutes knowledge and tools for brute material use.
        # The installed rural-profit debug contract requires a 20% base-price
        # margin; construction pacing, not an inflated recipe profit, prevents
        # AI saturation of these marginal plots.
        tier=("maintenance","managed","intensive","specialized").index(m["tier"])
        shares=((.20,.30,.50),(.25,.30,.45),(.31,.29,.40),(.36,.28,.36))[tier]
        tools=target*shares[0]/prices["tools"]
        lumber=target*shares[1]/prices["lumber"]
        livestock=target*shares[2]/prices["livestock"]
        o += [f"{m['key']} = {{",f"\ttools = {tools:.4f}",f"\tlumber = {lumber:.4f}",
              f"\tlivestock = {livestock:.4f}",f"\tproduced = {m['good']}",
              f"\toutput = {m['output']}","\tdebug_max_profit = rural_profit_margin",
              "\tcategory = building_maintenance","}",""]
    return "\n".join(o)

def production_method_ledger(rows):
    fields=("key","building","tier","name","good","base_output","output_multiplier","output","default_margin","unlock_age","profile","source")
    s=StringIO(newline=""); w=csv.DictWriter(s,fieldnames=fields,lineterminator="\n")
    w.writeheader(); w.writerows(method_rows(rows)); return s.getvalue()

def loc_text(lang,rows):
    o=[f"l_{lang}:"]
    for r in rows:
        o += [f' {r["key"]}:0 "{r["name"]}"',
              f' {r["key"]}_desc:0 "Peasant cultivators extend {r["name"].lower()} beyond native resource sites at lower yield, within strict ancient climate and landscape limits."',
              *[f' {r["key"]}_{suffix}:0 "{r["name"]}: {name}"' for suffix,name,_mult,_margin,_age,_profile in METHOD_TIERS]]
    return "\ufeff"+"\n".join(o)+"\n"

def sheet_cell(i): return f"cultivator_sheet_{i//4+1:02d}.png",CELLS[i%4]
def box(size,cell):
    w,h=size
    if w!=h or w<1024 or w%2: raise ValueError(f"bad four-up sheet size {size}")
    q=CELLS.index(cell); x=q%2; y=q//2; s=w//2
    return x*s,y*s,(x+1)*s,(y+1)*s
def convert(src,dst):
    subprocess.run([sys.executable,str(DDS),"convert",str(src),str(dst),"--compression","dxt5"],cwd=ROOT,check=True,stdout=subprocess.DEVNULL)

def art(rows):
    MASTERS.mkdir(parents=True,exist_ok=True); ICONS.mkdir(parents=True,exist_ok=True)
    opened={}; previews=[]
    try:
        for i,r in enumerate(rows):
            sheet,cell=sheet_cell(i); p=SHEETS/sheet
            if not p.is_file(): continue
            if sheet not in opened: opened[sheet]=Image.open(p).convert("RGBA")
            icon=ImageOps.fit(opened[sheet].crop(box(opened[sheet].size,cell)),(128,128),method=Image.Resampling.LANCZOS)
            # Active building icons use the installed circular dark-navy field.
            # Keep the crop legible in the centre and reserve a clean UI ring.
            field=Image.new("RGBA",(128,128),(16,25,43,255))
            inner=Image.new("L",(128,128),0)
            ImageDraw.Draw(inner).ellipse((15,15,112,112),fill=255)
            field.paste(icon,(0,0),inner.filter(ImageFilter.GaussianBlur(.7)))
            icon=field
            mask=Image.new("L",(128,128),0); ImageDraw.Draw(mask).ellipse((3,3,124,124),fill=255)
            icon.putalpha(mask.filter(ImageFilter.GaussianBlur(.7)))
            master=MASTERS/f"{r['key']}.png"; icon.save(master); convert(master,ICONS/f"{r['key']}.dds"); previews.append((r["key"],icon))
    finally:
        for im in opened.values(): im.close()
    if len(previews)==len(rows):
        height=((len(rows)+5)//6)*205
        canvas=Image.new("RGBA",(1080,height),(16,25,43,255)); d=ImageDraw.Draw(canvas)
        for i,(k,im) in enumerate(previews):
            x=(i%6)*180+10; y=(i//6)*205+3
            canvas.alpha_composite(im.resize((160,160),Image.Resampling.NEAREST),(x,y)); d.text((x,y+164),k[10:31],fill="white")
        canvas.convert("RGB").save(CONTACT)

def opening_seed_rows(rows: list[dict[str, str]] | None = None) -> list[dict[str, str]]:
    """Place bounded AD 1 cultivators on reviewed custom-good RGO anchors.

    Live ``change_raw_material`` is unsafe on 1.3.11, so custom raw goods have
    no native extraction unless a peasant plot is already present.
    """
    families = {row["good"]: row for row in (rows or load())}
    regions = owner_regions()
    by_good: dict[str, list[dict[str, str]]] = {}
    with RGO_ANCHORS.open(encoding="utf-8-sig", newline="") as handle:
        for row in csv.DictReader(handle):
            good = (row.get("good") or "").strip()
            family_row = families.get(good)
            if family_row is None or family_row["key"] not in OPENING_CUSTOM_CULTIVATORS:
                continue
            location = (row.get("location") or "").strip()
            if location not in regions:
                continue
            by_good.setdefault(good, []).append(row)
    papyrus = families.get("antq_papyrus")
    if papyrus and papyrus["key"] in OPENING_CUSTOM_CULTIVATORS:
        extra = []
        for location in (
            "alexandria", "ashmunayn", "faiyum", "cairo", "minya", "giza", "qena",
            "akhmim", "aswan", "asyut", "atfih", "beni_suef", "bilbeis",
            "dakahla", "damanhur", "damietta", "edfu", "el_bahnasa",
            "el_balyana", "el_mahalla", "esna", "faqus", "fuwa", "memphis",
        ):
            extra.append({
                "location": location,
                "good": "antq_papyrus",
                "source": "P12.1;P12.3;PER",
                "confidence": "secure" if location == "alexandria" else "contested",
            })
        by_good["antq_papyrus"] = extra + by_good.get("antq_papyrus", [])
    seeds: list[dict[str, str]] = []
    seen: set[tuple[str, str]] = set()
    for good, anchors in sorted(by_good.items()):
        family = families[good]["key"]
        for row in anchors[:SEED_CAP_PER_GOOD]:
            location = row["location"].strip()
            pair = (family, location)
            if pair in seen or location not in regions:
                continue
            seen.add(pair)
            region = regions[location]
            macro = REGION_MACRO.get(region)
            if not macro:
                continue
            slug = location.replace("-", "_")
            seeds.append({
                "key": f"cult_{good.removeprefix('antq_')}_{slug}",
                "family": family,
                "building": family,
                "location": location,
                "level": "1",
                "macro": macro,
                "source": row.get("source") or "P12.1",
                "confidence": row.get("confidence") or "contested",
                "note": (
                    "Opening peasant extraction for a custom raw good whose "
                    "live RGO remap remains deferred."
                ),
            })
    if len(seeds) < 8:
        raise ValueError("custom-good cultivator opening seed sample is too shallow")
    return seeds


def seed_ledger(rows: list[dict[str, str]]) -> str:
    stream = StringIO(newline="")
    writer = csv.DictWriter(stream, fieldnames=list(SEED_FIELDS), lineterminator="\n")
    writer.writeheader()
    for row in opening_seed_rows(rows):
        writer.writerow({field: row[field] for field in SEED_FIELDS})
    return stream.getvalue()


def availability(rows):
    s=StringIO(newline=""); w=csv.writer(s,lineterminator="\n")
    w.writerow(("building","good","climates","topographies","vegetations","regions","water_gate","max_levels","output","native_rgo_superior"))
    for r in rows: w.writerow((r["key"],r["good"],len(parts(r["climates"])),len(parts(r["topographies"])),len(parts(r["vegetations"])),len(parts(r["regions"])),r["water"],r["max"],r["output"],"yes"))
    return s.getvalue()

def write(rows):
    OUT.write_text(building_text(rows),encoding="utf-8-sig",newline="\n")
    METHODS.parent.mkdir(parents=True,exist_ok=True)
    METHODS.write_text(production_method_text(rows),encoding="utf-8-sig",newline="\n")
    METHOD_LEDGER.write_text(production_method_ledger(rows),encoding="utf-8-sig",newline="")
    for lang in LANGS:
        p=ROOT/f"main_menu/localization/{lang}/antq_s3_cultivators_l_{lang}.yml"; p.write_text(loc_text(lang,rows),encoding="utf-8",newline="\n")
    AVAIL.write_text(availability(rows),encoding="utf-8-sig",newline="")
    SEED_LEDGER.write_text(seed_ledger(rows),encoding="utf-8-sig",newline="")
    REPORT.write_text(
        f"# Cultivator System\n\n"
        f"- {len(rows)} lower-yield peasant buildings from {len(rows)//4} four-up art sheets.\n"
        f"- {len(CULTIVABLE_GOODS)} reviewed cultivable goods covered; coffee and silphium remain explicit historical exclusions.\n"
        f"- Exact climate, topography, vegetation, region, river, and coast gates.\n"
        f"- Hard caps 2-3; baseline outputs 0.18-0.38 versus native RGO production.\n"
        f"- Recipes match the installed 20% rural-profit contract; ordinary AI evaluates plots without a high-frequency search override.\n"
        f"- Player construction remains available on day one; AI construction begins after {AI_CAPITAL_SETTLEMENT_DATE} only with no loans, {AI_CAPITAL_RESERVE_MONTHS} months of gross-income reserves, and a surplus above 1/{AI_CAPITAL_SURPLUS_DIVISOR} of gross income.\n"
        f"- {len(rows)*len(METHOD_TIERS)} methods: baseline plus three research-gated stages; maximum output multiplier 1.35.\n"
        f"- {len(opening_seed_rows(rows))} AD 1 custom-good cultivator seeds cover deferred RGO remaps.\n",
        encoding="utf-8",
    )
    art(rows)

def check(rows):
    failures=[]; regions=set(json.loads((ROOT/"docs/vanilla_symbols/regions.json").read_text()))
    goods=set(json.loads((ROOT/"docs/vanilla_symbols/good.json").read_text()))
    with (ROOT/"docs/m5/custom_goods.csv").open(encoding="utf-8-sig",newline="") as f: goods.update(x["key"] for x in csv.DictReader(f))
    if len({r["key"] for r in rows})!=len(rows): failures.append("duplicate keys")
    covered={r["good"] for r in rows}
    if covered != CULTIVABLE_GOODS:
        failures.append(
            f"cultivable-good coverage drift: missing={sorted(CULTIVABLE_GOODS-covered)} "
            f"unexpected={sorted(covered-CULTIVABLE_GOODS)}"
        )
    if set(REVIEWED_EXCLUSIONS) & covered:
        failures.append("reviewed historical exclusions became cultivators")
    expected_small_cost = (("lumber", "0.05"), ("tools", "0.01"))
    if PACKAGE_GOODS.get(CULTIVATOR_CONSTRUCTION_PACKAGE) != expected_small_cost:
        failures.append("cultivator household construction basket drift")
    if not OUT.is_file() or OUT.read_text(encoding="utf-8-sig")!=building_text(rows): failures.append("building output stale")
    if not METHODS.is_file() or METHODS.read_text(encoding="utf-8-sig")!=production_method_text(rows): failures.append("production method output stale")
    if not METHOD_LEDGER.is_file() or METHOD_LEDGER.read_text(encoding="utf-8-sig")!=production_method_ledger(rows): failures.append("production method ledger stale")
    if not AVAIL.is_file() or AVAIL.read_text(encoding="utf-8-sig")!=availability(rows): failures.append("availability ledger stale")
    if not SEED_LEDGER.is_file() or SEED_LEDGER.read_text(encoding="utf-8-sig")!=seed_ledger(rows): failures.append("opening cultivator seed ledger stale")
    if not {row["family"] for row in opening_seed_rows(rows)} <= OPENING_CUSTOM_CULTIVATORS:
        failures.append("opening cultivator seeds escaped the custom-good contract")
    hashes={}
    for i,r in enumerate(rows):
        if r["good"] not in goods: failures.append(f"unknown good {r['good']}")
        if not .18<=float(r["output"])<=.40: failures.append(f"yield not marginal {r['key']}")
        unknown=set(parts(r["regions"]))-regions-{"ALL"}
        if unknown: failures.append(f"unknown regions {r['key']}: {unknown}")
        for p in (SHEETS/sheet_cell(i)[0],MASTERS/f"{r['key']}.png",ICONS/f"{r['key']}.dds"):
            if not p.is_file(): failures.append(f"missing direct art {p.relative_to(ROOT)}")
        p=ICONS/f"{r['key']}.dds"
        if p.is_file():
            h=hashlib.sha256(p.read_bytes()).hexdigest()
            if h in hashes: failures.append(f"art alias {hashes[h]} / {r['key']}")
            hashes[h]=r["key"]
    methods=method_rows(rows)
    if len(methods)!=len(rows)*4 or len({m["key"] for m in methods})!=len(methods): failures.append("method ladder coverage or uniqueness drift")
    for r in rows:
        family=[m for m in methods if m["building"]==r["key"]]
        if tuple(m["tier"] for m in family) != tuple(x[0] for x in METHOD_TIERS): failures.append(f"method tier drift {r['key']}")
        multipliers=[float(m["output_multiplier"]) for m in family]
        if any(b/a>1.35 for a,b in zip(multipliers,multipliers[1:])) or multipliers[-1]>1.35: failures.append(f"unbounded method gain {r['key']}")
        if any(float(m["default_margin"]) != 1.20 for m in family): failures.append(f"rural profit contract drift {r['key']}")
    if "\timportant_for_AI = yes" in building_text(rows): failures.append("cultivators must use ordinary profitability-aware AI evaluation")
    rendered=building_text(rows)
    if rendered.count("\tcountry_potential = {") != len(rows): failures.append("cultivator country-affordability gate coverage drift")
    if rendered.count("\tallow = {") != len(rows): failures.append("cultivator live affordability gate coverage drift")
    if rendered.count("\n".join(ai_capital_affordability_trigger())) != len(rows): failures.append("cultivator country-affordability gate contract drift")
    if rendered.count("\tallow = {\n\t\talways = yes\n\t}") != len(rows): failures.append("cultivator live construction allow must be player-reachable")
    if not CONTACT.is_file(): failures.append("contact sheet missing")
    for lang in LANGS:
        p=ROOT/f"main_menu/localization/{lang}/antq_s3_cultivators_l_{lang}.yml"
        if not p.is_file() or p.read_text(encoding="utf-8-sig")!=loc_text(lang,rows).lstrip("\ufeff"): failures.append(f"localization stale {lang}")
    if failures: raise ValueError("\n".join(failures))

def main():
    p=argparse.ArgumentParser(); p.add_argument("--write",action="store_true"); p.add_argument("--check",action="store_true"); a=p.parse_args()
    if a.write==a.check: p.error("choose exactly one")
    try:
        rows=load()
        if a.write: write(rows)
        check(rows)
    except (OSError,ValueError,csv.Error,subprocess.CalledProcessError) as e:
        print(f"s3_cultivator_buildings: FAIL\n  - {e}"); return 1
    print(f"s3_cultivator_buildings: PASS ({len(rows)} ecology-gated peasant cultivators; {len(rows)*4} production methods)"); return 0
if __name__=="__main__": raise SystemExit(main())
